Repository HDR-Development/HewDraw-Remix, pull requests merged in 2022-03, with the labels that each got.

#202 Chrom - fix sideB JC immediately burning double jump
  fighters/chrom/src/opff.rs
Labels: semver:patch

#201 Sonic - revert dsmash to vanilla
  fighters/sonic/src/acmd/smashes.rs
Labels: semver:patch

#197 Mii Swordfighter - revert down specials 1 & 3
  fighters/miiswordsman/src/acmd/specials.rs
  fighters/miiswordsman/src/opff.rs
  fighters/miiswordsman/src/status.rs
Labels: semver:patch

#205 fixing updater
  .github/workflows/build_beta.yml
  plugin/src/updater.rs
Labels: semver:patch

#195 Mythra - Remove nair landing hitbox
  fighters/elight/src/acmd/aerials.rs
Labels: semver:patch

#207 Bowser Jr. - fix kart not respawning on upB AGT landing
  fighters/koopajr/src/opff.rs
Labels: semver:patch

#208 Young Link/Toon Link - upB slideoff ledgegrab
  fighters/common/src/function_hooks/ledges.rs
  fighters/toonlink/src/lib.rs
  fighters/toonlink/src/status.rs
  fighters/younglink/src/lib.rs
  fighters/younglink/src/status.rs
Labels: semver:patch

#211 fix building on windows
  scripts/build.py
Labels: semver:patch

#214 Kirby Homing Attack Fix
  fighters/sonic/src/acmd/specials.rs
Labels: semver:patch

#243 IRAR fix
  fighters/common/src/general_statuses/dash.rs
  fighters/common/src/general_statuses/jumpsquat.rs
  fighters/common/src/general_statuses/turn.rs
Labels: semver:patch

#241 Dark Pit Guardian Orbitar JC Fix
  fighters/pitb/src/opff.rs
Labels: semver:patch

#268 PR builds and dev builds packaged separately
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
  .github/workflows/pr_build.yml
  scripts/build.py
  scripts/pkgutil.py
Labels: infrastructure, semver:patch

#273 Change USER_PROFILE to rustup_home
  scripts/build.py
Labels: semver:patch

#244 (bugfix) tag: disable tag outside regular smash
  utils/src/game_modes.rs
  utils/src/offsets.rs
Labels: semver:patch

#259 Remove boosted wavelands out of hitstun
  fighters/common/src/general_statuses/airdodge.rs
Labels: semver:patch

#274 handle dev script on windows
  scripts/build.py
Labels: semver:patch

#277 Skip gimmick flash in results screen
  fighters/common/src/opff/gimmick.rs
Labels: semver:patch

#270 Fix development.nro path in build.py for Ryujinx
  scripts/build.py
Labels: semver:patch

#271 hdr version changes
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
  .github/workflows/pr_build.yml
  .gitignore
  plugin/build.rs
  plugin/src/lib.rs
  scripts/build.py
  scripts/pkgutil.py
Labels: semver:patch

#254 reducing drift di at very low horizontal kb
  romfs/source/fighter/common/hdr/param/common.xml
Labels: engine, semver:patch

#291 remove jam from being author
  plugin/Cargo.toml
Labels: semver:patch

#290 Make perfect pivots more consistent
  fighters/common/src/general_statuses/turn.rs
Labels: semver:patch

#287 Fix double traction
  fighters/common/src/function_hooks/get_param.rs
  fighters/common/src/opff/physics.rs
Labels: semver:patch

#285 fixing fallback detection
  scripts/build.py
Labels: semver:patch

#295 fix having to relink everything because of version text file
  plugin/build.rs
Labels: semver:patch

#286 approved duckhunt changes
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/transition.rs
  fighters/duckhunt/src/acmd/aerials.rs
  fighters/duckhunt/src/acmd/ground.rs
  fighters/duckhunt/src/acmd/other.rs
  fighters/duckhunt/src/acmd/smashes.rs
  fighters/duckhunt/src/acmd/specials.rs
  fighters/duckhunt/src/acmd/throws.rs
  fighters/duckhunt/src/lib.rs
  fighters/duckhunt/src/opff.rs
Labels: semver:patch

#321 Fixes the Final hit on Bowsers UpB
  fighters/koopa/src/acmd/specials.rs
Labels: bug, character change, semver:patch

#314 Palutena aegis reflector rebalancing
  dynamic/src/consts.rs
  fighters/palutena/src/acmd/other.rs
  fighters/palutena/src/acmd/specials.rs
  fighters/palutena/src/lib.rs
  fighters/palutena/src/opff.rs
Labels: semver:patch

#322 Falco adjustments
  fighters/falco/src/acmd/aerials.rs
  fighters/falco/src/acmd/specials.rs
Labels: character change, semver:patch

#311 Darkpit orbitar startup decrease
  fighters/pitb/src/acmd/specials.rs
  fighters/pitb/src/opff.rs
Labels: semver:patch

#326 incineroar cleanup and rename get_jump_count
  dynamic/src/ext.rs
  fighters/bayonetta/src/opff.rs
  fighters/captain/src/opff.rs
  fighters/chrom/src/opff.rs
  fighters/donkey/src/opff.rs
  fighters/gamewatch/src/opff.rs
  fighters/gaogaen/src/opff.rs
  fighters/gekkouga/src/opff.rs
  fighters/kirby/src/opff.rs
  fighters/littlemac/src/opff.rs
  fighters/lucario/src/opff.rs
  fighters/lucas/src/opff.rs
  fighters/lucina/src/opff.rs
  fighters/mewtwo/src/opff.rs
  fighters/miigunner/src/opff.rs
  fighters/miiswordsman/src/opff.rs
  fighters/miiswordsman/src/status.rs
  fighters/pit/src/opff.rs
  fighters/pitb/src/opff.rs
  fighters/pzenigame/src/opff.rs
  fighters/robot/src/opff.rs
  fighters/rockman/src/opff.rs
  fighters/sheik/src/opff.rs
  fighters/shizue/src/opff.rs
  fighters/szerosuit/src/opff.rs
  fighters/trail/src/opff.rs
  fighters/wolf/src/opff.rs
  fighters/zelda/src/opff.rs
Labels: semver:patch

#329 fixing rate limits on pr label changes by using release token
  .github/workflows/semver_label_check.yml
Labels: semver:patch

#333 create full packaging for nightlies
  .github/workflows/build_nightly.yml
  .gitignore
  scripts/full_package.py
Labels: semver:patch

#335 Revert changes to resolve match load crashes
  dynamic/src/consts.rs
  fighters/palutena/src/acmd/other.rs
  fighters/palutena/src/acmd/specials.rs
  fighters/palutena/src/lib.rs
  fighters/palutena/src/opff.rs
Labels: semver:patch

#337 nro chainloading and simple install validation
  plugin/src/lib.rs
  plugin/src/updater.rs
  scripts/build.py
  scripts/pkgutil.py
Labels: semver:patch

#328 Removes Incineroar UpB cancel.
  fighters/gaogaen/src/opff.rs
Labels: semver:patch

#320 Fix double traction during sliding attacks
  dynamic/src/consts.rs
  fighters/common/src/opff/physics.rs
Labels: semver:patch

#356 packaging updates
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
  .gitignore
  scripts/full_package.py
  scripts/hash_package.py
Labels: semver:patch

#358 minor fixes
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#359 more minor fixes for packaging
  .github/workflows/build_beta.yml
Labels: semver:patch

#345 Bowser Jr Up B Explosion adjustments
  fighters/koopajr/src/acmd/specials.rs
  fighters/koopajr/src/lib.rs
  fighters/koopajr/src/opff.rs
Labels: character change, semver:patch

#348 Jr side b jump transition into real jumpsquat
  fighters/common/src/function_hooks/change_status.rs
Labels: character change, semver:patch

#360 switching to release token to avoid api rate limits
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#355 fixing validation issues
  plugin/Cargo.toml
  plugin/src/lib.rs
  scripts/build.py
Labels: semver:patch

#361 use github token for this one
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#362 switching some back to github token
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#363 making sure to checkout
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#365 token changes
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#366 making changes to the packaging
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#371 IRAR rework v2
  fighters/common/src/general_statuses/jumpsquat.rs
Labels: semver:patch

#370 Aerial Magic Series now checks Player LR
  fighters/common/src/opff/shotos.rs
Labels: bug, semver:patch

#372 Fix double traction during sliding attacks (for real this time)
  fighters/common/src/opff/physics.rs
Labels: semver:patch

#378 Falco Nair will now pay taxes (removed autocancel through the whole move)
  fighters/falco/src/acmd/aerials.rs
Labels: bug, character change, semver:patch

#377 Jump adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/jumps.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/function_hooks/momentum_transfer.rs
  fighters/common/src/general_statuses/jump.rs
  fighters/common/src/lib.rs
  fighters/common/src/misc.rs
  fighters/common/src/opff/momentum_transfer_line.rs
Labels: enhancement, semver:patch

#380 Knockback buffer adjustments
  fighters/common/src/function_hooks/transition.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/common/src/opff/other.rs
Labels: bug, semver:patch, minor improvement

#379 Double traction refactor
  fighters/common/src/opff/physics.rs
Labels: semver:patch, minor improvement

#381 change to switch-package.zip
  .gitignore
  scripts/full_package.py
Labels: infrastructure, semver:patch

#392 update full packaging to always package latest arcropolis
  scripts/full_package.py
Labels: semver:patch

#393 Sonic - fair ACMD adjustments to match new anim
  fighters/sonic/src/acmd/aerials.rs
Labels: character change, semver:patch, minor improvement

#383 Center Falco shine
  fighters/falco/src/acmd/specials.rs
Labels: bug, character change, semver:patch

#394 Remove ability for on-hit cancelable moves to be canceled during hitlag
  fighters/bayonetta/src/opff.rs
  fighters/chrom/src/opff.rs
  fighters/edge/src/opff.rs
  fighters/falco/src/opff.rs
  fighters/fox/src/opff.rs
  fighters/gekkouga/src/opff.rs
  fighters/kirby/src/opff.rs
  fighters/littlemac/src/opff.rs
  fighters/lucario/src/opff.rs
  fighters/lucas/src/opff.rs
  fighters/lucina/src/opff.rs
  fighters/master/src/opff.rs
  fighters/miigunner/src/opff.rs
  fighters/miiswordsman/src/opff.rs
  fighters/miiswordsman/src/status.rs
  fighters/ness/src/opff.rs
  fighters/pitb/src/opff.rs
  fighters/pzenigame/src/opff.rs
  fighters/robot/src/opff.rs
  fighters/rockman/src/opff.rs
  fighters/shizue/src/opff.rs
  fighters/szerosuit/src/opff.rs
  fighters/wolf/src/opff.rs
  fighters/zelda/src/opff.rs
Labels: engine, semver:patch, minor improvement

#338 adding palu reflector changes back in (do not merge until tested)
  dynamic/src/consts.rs
  fighters/palutena/src/acmd/other.rs
  fighters/palutena/src/acmd/specials.rs
  fighters/palutena/src/lib.rs
  fighters/palutena/src/opff.rs
Labels: semver:patch

#399 minor main_nro argument mistake
  scripts/build.py
Labels: semver:patch

#405 Captain Falcon - shorthop height reduced
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, minor improvement

#396 B-reverse rework
  fighters/captain/src/opff.rs
  fighters/cloud/src/opff.rs
  fighters/common/src/opff/tech.rs
  fighters/donkey/src/opff.rs
  fighters/ganon/src/opff.rs
  fighters/ike/src/opff.rs
  fighters/kirby/src/opff.rs
  fighters/krool/src/opff.rs
  fighters/link/src/opff.rs
  fighters/littlemac/src/opff.rs
  fighters/mario/src/opff.rs
  fighters/miigunner/src/opff.rs
  fighters/pacman/src/opff.rs
  fighters/pikmin/src/opff.rs
  fighters/richter/src/opff.rs
  fighters/samus/src/opff.rs
  fighters/simon/src/opff.rs
  fighters/toonlink/src/opff.rs
  fighters/younglink/src/opff.rs
Labels: bug, enhancement, engine, semver:patch

#406 Reduce parry window 5f -> 3f
  romfs/source/fighter/common/param/common.prcxml
Labels: enhancement, engine, semver:patch

#391 Ledge occupancy bugfix + rework
  fighters/common/src/function_hooks/ledges.rs
  fighters/common/src/opff/ledges.rs
Labels: bug, semver:patch, minor improvement

#401 Falco Dair rework
  fighters/falco/src/acmd/aerials.rs
Labels: character change, semver:patch

#407 Reduced Knockback on Mario's Initial Fair
  fighters/mario/src/acmd/aerials.rs
Labels: semver:patch

#408 Chrom Utilt Initial Outer Hitbox KB Angle fix
  fighters/chrom/src/acmd/tilts.rs
Labels: semver:patch

#409 creating upgrade zip and deletions list for packaging
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
  .gitignore
  scripts/diff_lib.py
  scripts/full_package.py
  scripts/make_diff.py
Labels: infrastructure, semver:patch

#410 Falco - dair corrections
  fighters/falco/src/acmd/aerials.rs
Labels: bug, semver:patch, minor improvement
