Repository HDR-Development/HewDraw-Remix, pull requests merged in 2022-06, with the labels that each got.

#608 Reduce dash smash attack window from 6f to 2f
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#622 Double traction status added to standing grab
  fighters/common/src/opff/physics.rs
Labels: engine, semver:patch

#607 Terry GO! UI shows when you have Super Specials
  dynamic/src/offsets.rs
  fighters/dolly/src/opff.rs
  utils/src/modules/meter.rs
  utils/src/offsets.rs
Labels: enhancement, aesthetics, semver:patch

#638 Revert dash_s4_frame to 6f
  romfs/source/fighter/common/param/common.prcxml
Labels: semver:patch

#637 Add Cancel to Isabelle's Recovery
  fighters/shizue/src/acmd/specials.rs
  fighters/shizue/src/opff.rs
Labels: semver:patch

#644 Charizard Dair Landing Lag Correction
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: semver:patch

#642 Charizard Dtaunt windbox size reduction
  fighters/plizardon/src/acmd/other.rs
Labels: semver:patch

#643 Allow runbrake to teeter cancel
  fighters/common/src/opff/tech.rs
Labels: engine, semver:patch

#511 Link adjustments
  fighters/link/src/acmd/aerials.rs
  fighters/link/src/acmd/ground.rs
  fighters/link/src/acmd/other.rs
  fighters/link/src/acmd/smashes.rs
  fighters/link/src/acmd/specials.rs
  fighters/link/src/acmd/tilts.rs
  fighters/link/src/opff.rs
Labels: semver:patch

#649 Isabelle Recovery - Version 2
  dynamic/src/consts.rs
  fighters/shizue/src/acmd/specials.rs
  fighters/shizue/src/opff.rs
Labels: semver:patch

#630 Rework aerial glide tossing (airdodge cancelled item throws)
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/airdodge.rs
  fighters/common/src/opff/var_resets.rs
  romfs/source/fighter/toonlink/param/vl.prcxml
Labels: engine, semver:patch

#625 Duck Hunt - remove ability to fire Gunman when dead
  fighters/duckhunt/src/opff.rs
Labels: character change, semver:patch

#618 Little Mac - raise ledgegrab box
  romfs/source/fighter/littlemac/param/vl.prcxml
Labels: character change, semver:patch

#617 Falco - increase walljump height
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#655 switching to release token for artifact upload to hopefully get less errconnreset errors
  .github/workflows/build_nightly.yml
Labels: semver:patch

#656 Disable Byleth's Aymr stage 3
  fighters/master/src/acmd/specials.rs
Labels: character change, semver:patch

#661 Update Air Tether input logic
  fighters/common/src/general_statuses/jumpsquat.rs
  fighters/common/src/general_statuses/mod.rs
Labels: enhancement, engine, semver:patch

#492 Mk rework and Meta Quick mechanic
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/dash_dancing.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/function_hooks/momentum_transfer.rs
  fighters/common/src/general_statuses/dash.rs
  fighters/common/src/general_statuses/run.rs
  fighters/common/src/general_statuses/walk.rs
  fighters/common/src/misc.rs
  fighters/metaknight/src/acmd/aerials.rs
  fighters/metaknight/src/acmd/specials.rs
  fighters/metaknight/src/acmd/throws.rs
  fighters/metaknight/src/acmd/tilts.rs
  fighters/metaknight/src/lib.rs
  fighters/metaknight/src/meta_quick.rs
  fighters/metaknight/src/opff.rs
  romfs/source/fighter/metaknight/param/vl.prcxml
  scripts/build.py
Labels: semver:feature

#590 CSS, control, and random changes
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/controls.rs
  fighters/common/src/opff/tech.rs
  fighters/falco/src/opff.rs
  plugin/Cargo.toml
  plugin/src/controls.rs
  plugin/src/lib.rs
  plugin/src/lua.rs
  plugin/src/random.rs
  romfs/source/ui/message/msg_menu.xmsbt
  romfs/source/ui/script/menu/option/option_button_controller.lua
  scripts/build.py
  utils/build.rs
Labels: semver:feature

#673 blujay's stage hazards removal
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/function_hooks/stage_hazards.rs
  fighters/common/src/opff/tech.rs
Labels: semver:patch

#675 Lucas - reinstate frame-perfect DJCZ
  fighters/common/src/general_statuses/mod.rs
Labels: engine, semver:patch

#679 fix footstool crashing by making it a new button
  dynamic/src/ext.rs
  dynamic/src/modules.rs
  dynamic/src/modules/input.rs
  fighters/common/src/function_hooks/controls.rs
  fighters/common/src/function_hooks/jumps.rs
  fighters/common/src/general_statuses/footstool.rs
  fighters/common/src/general_statuses/jump.rs
  fighters/common/src/general_statuses/jumpsquat.rs
  fighters/common/src/general_statuses/shield/guard_damage/exit.rs
  fighters/common/src/general_statuses/shield/guard_damage/main.rs
  fighters/common/src/opff/tech.rs
  fighters/popo/src/opff.rs
  plugin/src/controls.rs
  scripts/build.py
  utils/src/modules.rs
  utils/src/modules/input.rs
Labels: semver:patch

#669 Roll and Spotdodge Normalization
  romfs/source/fighter/common/param/fighter_param_motion.prcxml
Labels: semver:patch

#683 fixing Shorthop-Button-cancelling behavior
  fighters/common/src/function_hooks/jumps.rs
Labels: semver:patch

#685 Working on econnreset
  .github/workflows/build_nightly.yml
Labels: semver:patch

#689 Update build_nightly.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#691 Update build_nightly.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#682 metaquick fx and remove lots of println
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/common/src/djc.rs
  fighters/elight/src/acmd/specials.rs
  fighters/elight/src/status/special_hi_jump.rs
  fighters/metaknight/src/acmd/aerials.rs
  fighters/metaknight/src/acmd/other.rs
  fighters/metaknight/src/acmd/specials.rs
  fighters/metaknight/src/lib.rs
  fighters/metaknight/src/meta_quick.rs
  fighters/metaknight/src/opff.rs
  fighters/pickel/src/opff.rs
  fighters/src/lib.rs
  plugin/src/controls.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  utils/src/modules/input.rs
  utils/src/modules/meter.rs
Labels: semver:patch

#627 Mii Swordfighter - slight adjustments
  fighters/miiswordsman/src/acmd/aerials.rs
  fighters/miiswordsman/src/acmd/ground.rs
  fighters/miiswordsman/src/acmd/smashes.rs
  fighters/miiswordsman/src/acmd/specials.rs
  fighters/miiswordsman/src/acmd/tilts.rs
  fighters/miiswordsman/src/opff.rs
Labels: character change, semver:patch

#692 Joker - Temporarily remove gun beam gfx
  fighters/jack/src/acmd/specials.rs
Labels: aesthetics, character change, semver:patch

#688 Reduce wavedash/waveland lengths globally
  romfs/source/fighter/common/param/fighter_param_motion.prcxml
Labels: engine, semver:patch

#694 waveland platdrop consistency improvements
  fighters/common/src/opff/tech.rs
  romfs/source/fighter/common/hdr/param/common.xml
Labels: semver:patch

#696 Revert wavedash changes
  romfs/source/fighter/common/param/fighter_param_motion.prcxml
Labels: semver:patch

#662 Small Dr. Mario changes
  fighters/mariod/src/acmd/aerials.rs
  fighters/mariod/src/acmd/specials.rs
Labels: character change, semver:patch

#716 remove c-stick drift
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/controls.rs
  fighters/common/src/function_hooks/energy.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/lib.rs
  fighters/common/src/opff/mod.rs
  plugin/Cargo.toml
  utils/Cargo.toml
Labels: semver:feature

#717 Hitstun mul reduction
  romfs/source/fighter/common/param/battle_object.prcxml
Labels: semver:patch

#707 Drift DI scaling adjustments
  fighters/common/src/function_hooks/controls.rs
  fighters/common/src/opff/tech.rs
  romfs/source/fighter/common/hdr/param/common.xml
Labels: semver:patch

#626 Pivot adjustments
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/dash.rs
  fighters/common/src/general_statuses/turn.rs
  fighters/common/src/opff/physics.rs
Labels: engine, semver:patch

#704 Pichu changes
  fighters/pichu/Cargo.toml
  fighters/pichu/src/acmd/aerials.rs
  fighters/pichu/src/acmd/ground.rs
  fighters/pichu/src/acmd/mod.rs
  fighters/pichu/src/acmd/other.rs
  fighters/pichu/src/acmd/smashes.rs
  fighters/pichu/src/acmd/specials.rs
  fighters/pichu/src/acmd/throws.rs
  fighters/pichu/src/acmd/tilts.rs
  fighters/pichu/src/lib.rs
  fighters/pichu/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/pichu/param/vl.prcxml
Labels: character change, semver:patch

#725 Falco changes
  fighters/common/src/opff/mod.rs
  fighters/falco/src/acmd/aerials.rs
  fighters/falco/src/acmd/specials.rs
  fighters/falco/src/opff.rs
  romfs/source/fighter/falco/param/vl.prcxml
Labels: character change, semver:patch

#723 Global ECB fixes/waveland adjustments
  dynamic/src/ext.rs
  fighters/buddy/src/opff.rs
  fighters/common/src/function_hooks/change_motion.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/general_statuses/airdodge.rs
  fighters/common/src/general_statuses/jump.rs
  fighters/common/src/general_statuses/jumpsquat.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/common/src/opff/momentum_transfer_line.rs
  fighters/common/src/opff/physics.rs
Labels: bug, enhancement, engine, semver:patch

#747 Ignore OSX-generated .DS_Store files
  .gitignore
Labels: infrastructure, semver:patch

#729 corrin activity adjustments
  fighters/kamui/src/acmd/aerials.rs
  fighters/kamui/src/acmd/tilts.rs
  romfs/source/fighter/kamui/param/vl.prcxml
Labels: character change, semver:patch

#710 Ganondorf Float Neutral Special
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/transition.rs
  fighters/common/src/opff/floats.rs
  fighters/ganon/src/acmd/specials.rs
  fighters/ganon/src/lib.rs
  fighters/ganon/src/opff.rs
  fighters/ganon/src/status.rs
  fighters/ganon/src/status/special_lw.rs
  fighters/ganon/src/status/special_n.rs
  fighters/ganon/src/status/special_n_float.rs
  fighters/src/lib.rs
Labels: character change, semver:patch

#750 Delete ui_stage_db.prcxml
  romfs/source/ui/param/database/ui_stage_db.prcxml
Labels: semver:patch

#753 Gnw bair correction
  fighters/gamewatch/src/acmd/aerials.rs
Labels: character change, semver:patch

#755 Fix VarModule init_settings crash
  dynamic/src/modules/var.rs
  fighters/common/src/function_hooks/init_settings.rs
  utils/src/modules/var.rs
Labels: bug, semver:patch
