Repository HDR-Development/HewDraw-Remix, pull requests merged in 2022-08, with the labels that each got.

#882 Firebrand adjustments
  fighters/mario/src/acmd/specials.rs
  fighters/mario/src/opff.rs
Labels: character change, semver:patch

#883 Kirby - add Kirbycide
  dynamic/src/ext.rs
  fighters/common/src/general_statuses/catchcut.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/common/src/opff/other.rs
  fighters/kirby/src/acmd/throws.rs
  fighters/kirby/src/status.rs
  romfs/source/fighter/common/hdr/param/common.xml
Labels: character change, semver:patch

#887 Boost Running bugfix
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/transition.rs
  fighters/common/src/general_statuses/dash.rs
  fighters/common/src/shoto_status.rs
Labels: bug, engine, semver:patch

#895 Disable shieldstun edge slideoff during Parry
  fighters/common/src/general_statuses/shield/guard_damage/init.rs
Labels: engine, semver:patch

#897 Mii Swordfighter - Skyward Slash Dash bugfixes
  dynamic/src/consts.rs
  fighters/bayonetta/src/acmd/ground.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/dolly/src/acmd/aerials.rs
  fighters/dolly/src/acmd/ground.rs
  fighters/dolly/src/opff.rs
  fighters/gaogaen/src/acmd/throws.rs
  fighters/gaogaen/src/acmd/tilts.rs
  fighters/ken/src/acmd/aerials.rs
  fighters/ken/src/acmd/ground.rs
  fighters/ken/src/opff.rs
  fighters/master/src/acmd/smashes.rs
  fighters/master/src/acmd/specials.rs
  fighters/miigunner/src/acmd/aerials.rs
  fighters/miigunner/src/acmd/throws.rs
  fighters/miiswordsman/src/acmd/other.rs
  fighters/miiswordsman/src/acmd/specials.rs
  fighters/miiswordsman/src/opff.rs
  fighters/miiswordsman/src/status.rs
  fighters/pickel/src/acmd/other.rs
  fighters/pickel/src/acmd/tilts.rs
  fighters/robot/src/acmd/aerials.rs
  fighters/robot/src/opff.rs
  fighters/rockman/src/acmd/tilts.rs
  fighters/rockman/src/opff.rs
  fighters/ryu/src/acmd/aerials.rs
  fighters/ryu/src/opff.rs
Labels: bug, character change, semver:patch

#885 Lucario - add Force Palm aerial dunk
  dynamic/src/consts.rs
  fighters/lucario/src/acmd/specials.rs
  fighters/lucario/src/lib.rs
  fighters/lucario/src/status.rs
  romfs/config.json
  romfs/source/fighter/lucario/param/hdr.xml
  utils/agent_params.txt
  utils/rom_watch.txt
Labels: character change, semver:patch

#892 Ike - down taunt adjustment
  fighters/ike/src/acmd/other.rs
Labels: character change, semver:patch

#898 Mr. Game & Watch - dthrow adjustments
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/gamewatch/src/acmd/throws.rs
Labels: character change, semver:patch

#903 Tumble Threshold Adjustment
  romfs/source/fighter/common/param/battle_object.prcxml
Labels: engine, semver:patch

#893 Little Mac - Dreamland Express adjustments
  dynamic/src/consts.rs
  fighters/littlemac/src/acmd/ground.rs
Labels: character change, semver:patch

#877 Ganondorf Float Cancel Fix
  fighters/ganon/src/status/special_n_float.rs
Labels: bug, character change, semver:patch

#880 Incineroar changes
  fighters/common/src/function_hooks/edge_slipoffs.rs
  fighters/gamewatch/src/acmd/throws.rs
  fighters/gaogaen/src/acmd/aerials.rs
  fighters/gaogaen/src/acmd/other.rs
  fighters/gaogaen/src/acmd/smashes.rs
  fighters/gaogaen/src/acmd/specials.rs
  fighters/gaogaen/src/acmd/throws.rs
  fighters/gaogaen/src/acmd/tilts.rs
  fighters/gaogaen/src/lib.rs
  fighters/gaogaen/src/opff.rs
  fighters/gaogaen/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/gaogaen/param/vl.prcxml
Labels: character change, semver:patch

#905 Fix wavelands after aerial attacks
  fighters/common/src/general_statuses/airdodge.rs
Labels: bug, engine, semver:patch

#899 Turnaround special/B-reverse reimplementation
  fighters/brave/src/opff.rs
  fighters/captain/src/opff.rs
  fighters/cloud/src/opff.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/common/src/opff/tech.rs
  fighters/donkey/src/opff.rs
  fighters/ganon/src/opff.rs
  fighters/ike/src/opff.rs
  fighters/kirby/src/opff.rs
  fighters/krool/src/opff.rs
  fighters/link/src/opff.rs
  fighters/littlemac/src/opff.rs
  fighters/mario/src/opff.rs
  fighters/metaknight/src/opff.rs
  fighters/miigunner/src/opff.rs
  fighters/pacman/src/opff.rs
  fighters/palutena/src/opff.rs
  fighters/pikmin/src/opff.rs
  fighters/richter/src/opff.rs
  fighters/samus/src/opff.rs
  fighters/simon/src/opff.rs
  fighters/toonlink/src/opff.rs
  fighters/younglink/src/opff.rs
  fighters/zelda/src/opff.rs
Labels: enhancement, engine, semver:patch

#906 Remove random tripping
  fighters/common/Cargo.toml
  fighters/common/src/function_hooks/attack.rs
  fighters/common/src/function_hooks/mod.rs
Labels: enhancement, engine, semver:feature

#908 Pichu - Charge State adjustments
  dynamic/src/consts.rs
  fighters/pichu/src/acmd/other.rs
  fighters/pichu/src/acmd/specials.rs
  fighters/pichu/src/opff.rs
Labels: character change, semver:patch

#907 Suicide throw adjustments
  dynamic/src/consts.rs
  fighters/common/src/opff/other.rs
  fighters/kirby/src/acmd/throws.rs
  romfs/source/fighter/common/hdr/param/common.xml
Labels: character change, semver:patch

#919 Fix JC usmash logic
  fighters/common/src/general_statuses/jumpsquat.rs
Labels: bug, enhancement, engine, semver:patch

#922 Reduce waveland snap threshold
  romfs/source/fighter/common/hdr/param/common.xml
Labels: engine, semver:patch

#925 Stick Sensitivity Adjustments
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#921 Falco slight rework
  fighters/falco/src/acmd/aerials.rs
  fighters/falco/src/acmd/specials.rs
  fighters/falco/src/acmd/tilts.rs
  fighters/falco/src/opff.rs
Labels: character change, semver:patch

#924 Aesthetic wavedash improvements
  fighters/common/src/function_hooks/change_motion.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/common/src/general_statuses/jumpsquat.rs
Labels: aesthetics, engine, semver:patch

#931 Drift DI rework
  dynamic/src/consts.rs
  fighters/common/src/opff/tech.rs
  romfs/source/fighter/common/hdr/param/common.xml
Labels: engine, semver:patch

#938 Remove Nok Nok Shell from Bowser
  dynamic/src/consts.rs
  fighters/koopa/src/acmd/other.rs
  fighters/koopa/src/opff.rs
Labels: character change, semver:patch

#923 Mii Swordfighter Adjustments
  fighters/miiswordsman/src/acmd/aerials.rs
  fighters/miiswordsman/src/acmd/ground.rs
  fighters/miiswordsman/src/acmd/smashes.rs
  fighters/miiswordsman/src/acmd/specials.rs
  fighters/miiswordsman/src/acmd/tilts.rs
  fighters/miiswordsman/src/opff.rs
  fighters/miiswordsman/src/status.rs
Labels: character change, semver:patch

#939 Chrom dair hitbox ID Fix
  fighters/chrom/src/acmd/aerials.rs
Labels: bug, semver:patch

#934 Reimpl'd Illusion
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/edge_slipoffs.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/falco/src/lib.rs
  fighters/falco/src/opff.rs
  fighters/falco/src/status.rs
  fighters/falco/src/status/special_s.rs
  fighters/fox/src/lib.rs
  fighters/fox/src/opff.rs
  fighters/fox/src/status.rs
  fighters/fox/src/status/special_s.rs
  fighters/wolf/src/lib.rs
  fighters/wolf/src/opff.rs
  fighters/wolf/src/status.rs
  fighters/wolf/src/status/special_s.rs
Labels: enhancement, character change, semver:patch

#942 Fix smash stick during dash
  fighters/common/src/opff/physics.rs
Labels: bug, engine, semver:patch

#950 fighter_param documentation
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: semver:patch

#940 Lingering ledge intangibility
  fighters/common/src/general_statuses/airdodge.rs
  fighters/common/src/general_statuses/cliff.rs
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:feature

#951 Update fighter_param
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: semver:patch

#960 Falco lasers stun reduction
  fighters/falco/src/acmd/other.rs
Labels: character change, semver:patch

#945 Corrin rework
  fighters/kamui/src/acmd/aerials.rs
  fighters/kamui/src/acmd/ground.rs
  fighters/kamui/src/acmd/other.rs
  fighters/kamui/src/acmd/smashes.rs
  fighters/kamui/src/acmd/specials.rs
  fighters/kamui/src/acmd/tilts.rs
  fighters/kamui/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/kamui/param/vl.prcxml
Labels: character change, semver:patch

#966 Mewtwo - recovery adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/opff/floats.rs
  fighters/mewtwo/src/acmd/specials.rs
  fighters/mewtwo/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/mewtwo/param/vl.prcxml
Labels: character change, semver:patch

#947 Robin - Elwind1 cancel adjustment
  dynamic/src/consts.rs
  fighters/robin/src/acmd/specials.rs
  fighters/robin/src/opff.rs
Labels: character change, semver:patch

#948 Adjust gimmick flash GFX
  fighters/common/src/opff/gimmick.rs
Labels: aesthetics, semver:patch

#961 Ridley - small changes
  fighters/ridley/src/acmd/aerials.rs
  fighters/ridley/src/opff.rs
Labels: character change, semver:patch

#969 Knockdown throw adjustments
  fighters/common/src/general_statuses/mod.rs
  fighters/gamewatch/src/acmd/throws.rs
  fighters/gaogaen/src/acmd/throws.rs
  fighters/kirby/src/acmd/throws.rs
Labels: engine, semver:patch

#975 Glide Toss rework
  dynamic/src/consts.rs
  fighters/bayonetta/src/status.rs
  fighters/common/src/general_statuses/airdodge.rs
  fighters/common/src/general_statuses/escape.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/common/src/opff/tech.rs
  romfs/source/fighter/common/hdr/param/common.xml
  romfs/source/fighter/common/param/item.prcxml
Labels: engine, semver:patch

#962 Palutena Adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/palutena/src/acmd/aerials.rs
  fighters/palutena/src/acmd/ground.rs
  fighters/palutena/src/acmd/other.rs
  fighters/palutena/src/acmd/smashes.rs
  fighters/palutena/src/acmd/tilts.rs
  fighters/palutena/src/opff.rs
  romfs/source/fighter/palutena/param/vl.prcxml
Labels: character change, semver:patch

#952 Bayonetta adjustments
  dynamic/src/consts.rs
  fighters/bayonetta/src/acmd/aerials.rs
  fighters/bayonetta/src/acmd/ground.rs
  fighters/bayonetta/src/acmd/other.rs
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/acmd/throws.rs
  fighters/bayonetta/src/acmd/tilts.rs
  fighters/bayonetta/src/opff.rs
  romfs/source/fighter/bayonetta/param/vl.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#970 Shield adjustments
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/common/src/general_statuses/shield/misc.rs
  fighters/common/src/general_statuses/shield/mod.rs
  fighters/common/src/opff/mod.rs
  fighters/common/src/opff/shields.rs
  fighters/common/src/opff/tech.rs
  romfs/source/fighter/common/hdr/param/common.xml
  romfs/source/fighter/common/param/battle_object.prcxml
  romfs/source/fighter/common/param/common.prcxml
  utils/src/modules/input.rs
Labels: engine, semver:patch

#977 Corrin bair rework and hotfix
  dynamic/src/consts.rs
  fighters/kamui/src/acmd/aerials.rs
Labels: character change, semver:patch

#976 Lingering ledge intangibility adjustments
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/airdodge.rs
  fighters/common/src/general_statuses/cliff.rs
  fighters/common/src/opff/other.rs
Labels: engine, semver:patch

#981 Tether ledge occupancy bugfixes
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/function_hooks/ledges.rs
Labels: bug, engine, semver:patch

#983 Reduce wall/ground/ceiling bounce hitstun multiplier
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#987 Bayonetta - Bats Within crash fix
  fighters/bayonetta/src/status.rs
Labels: crash, semver:patch

#956 Meta Knight - Meta Quick adjustments
  fighters/metaknight/src/acmd/specials.rs
  fighters/metaknight/src/meta_quick.rs
Labels: character change, semver:patch

#971 Salty Runback/Quick Exit graphical indicators
  fighters/common/src/opff/mod.rs
Labels: engine, semver:patch

#988 Fix item hold dash momentum
  fighters/common/src/function_hooks/energy.rs
Labels: bug, engine, semver:patch

#990 King Dedede - adjust bair hitbox positioning to fit new anim
  fighters/dedede/src/acmd/aerials.rs
Labels: character change, semver:patch

#958 ASDI implementation
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/damage.rs
  fighters/common/src/general_statuses/mod.rs
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:feature
