Repository HDR-Development/HewDraw-Remix, pull requests merged in 2022-07, with the labels that each got.

#748 ECB bugfixes/cleanup
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/change_motion.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/general_statuses/airdodge.rs
  fighters/common/src/general_statuses/jumpsquat.rs
  fighters/common/src/opff/physics.rs
Labels: bug, engine, crash, semver:patch

#761 Fixed Ganon's Float not resetting on death
  fighters/ganon/src/status.rs
  fighters/ganon/src/status/special_n.rs
  fighters/ganon/src/status/special_n_float.rs
Labels: bug, character change, semver:patch

#703 fixing new hazardless stages online
  fighters/common/src/function_hooks/stage_hazards.rs
Labels: semver:patch

#760 Marth shieldstun multiplier and special adjustments
  fighters/marth/src/acmd/aerials.rs
  fighters/marth/src/acmd/ground.rs
  fighters/marth/src/acmd/specials.rs
  fighters/marth/src/acmd/tilts.rs
Labels: character change, semver:patch

#742 Samus adjustments
  fighters/samus/src/acmd/aerials.rs
  fighters/samus/src/acmd/ground.rs
  fighters/samus/src/acmd/other.rs
  fighters/samus/src/acmd/smashes.rs
  fighters/samus/src/acmd/throws.rs
  fighters/samus/src/acmd/tilts.rs
  fighters/samusd/src/acmd/aerials.rs
  fighters/samusd/src/acmd/other.rs
  fighters/samusd/src/acmd/specials.rs
  fighters/samusd/src/opff.rs
  romfs/source/fighter/samus/param/vl.prcxml
  romfs/source/fighter/samusd/param/vl.prcxml
Labels: character change, semver:patch

#771 Add RoA wavedash macro + wavedash improvements
  dynamic/src/ext.rs
  fighters/common/src/general_statuses/jumpsquat.rs
  fighters/common/src/general_statuses/mod.rs
  utils/src/modules/input.rs
Labels: enhancement, engine, semver:patch

#798 fix to dash ftilt + change to fsmash leniency
  fighters/common/src/general_statuses/dash.rs
  romfs/source/fighter/common/param/common.prcxml
Labels: semver:patch

#801 Wavedash macro adjustment
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/general_statuses/jumpsquat.rs
Labels: engine, semver:patch, minor improvement

#807 Puff bair nerf
  fighters/purin/src/acmd/aerials.rs
Labels: good first issue, character change, semver:patch

#746 Ryu - various adjustments
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/general_statuses/airdodge.rs
  fighters/ryu/src/acmd/aerials.rs
  fighters/ryu/src/acmd/other.rs
  fighters/ryu/src/acmd/specials.rs
  fighters/ryu/src/opff.rs
  fighters/ryu/src/status.rs
  romfs/source/fighter/common/param/fighter_param_motion.prcxml
Labels: character change, semver:patch

#804 Add a seperate hitbox cancel to air Luigi Downb
  fighters/luigi/src/acmd/specials.rs
Labels: character change, semver:patch

#751 New Lucas just Dropped
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/attackdash.rs
  fighters/lucas/src/acmd/aerials.rs
  fighters/lucas/src/acmd/ground.rs
  fighters/lucas/src/acmd/other.rs
  fighters/lucas/src/acmd/smashes.rs
  fighters/lucas/src/acmd/specials.rs
  fighters/lucas/src/opff.rs
  fighters/lucas/src/status.rs
  romfs/config.json
  romfs/source/fighter/lucas/param/hdr.xml
  romfs/source/fighter/lucas/param/vl.prcxml
  utils/agent_params.txt
  utils/rom_watch.txt
Labels: enhancement, good first issue, character change, semver:feature

#780 Fox - Firefox startup ledgegrab
  fighters/common/src/function_hooks/ledges.rs
  fighters/fox/src/opff.rs
Labels: character change, semver:patch

#816 Quick Fix - Remove PK Freeze(Fire) HurtBox 2
  fighters/lucas/src/status.rs
  romfs/source/fighter/lucas/param/vl.prcxml
Labels: semver:patch

#818 Falco - Firebird startup ledgegrab
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/function_hooks/ledges.rs
  fighters/falco/src/opff.rs
Labels: character change, semver:patch

#734 Ledge behavior bugfixes/rework
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/function_hooks/ledges.rs
  fighters/common/src/general_statuses/cliff.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/common/src/opff/ledges.rs
Labels: engine, semver:patch

#793 Banjo - remove feather dthrow
  fighters/buddy/src/acmd/throws.rs
Labels: character change, semver:patch

#799 Pikachu - disable Quick Attack Jump Cancel after Quick Attack 2
  fighters/pikachu/src/opff.rs
Labels: character change, semver:patch

#773 Clear buffer on grounded damage/knockdown/trip slideoffs
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/opff/other.rs
Labels: enhancement, engine, semver:patch

#779 Robin - float rework + other adjustments
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/function_hooks/ledges.rs
  fighters/common/src/opff/floats.rs
  fighters/robin/src/acmd/smashes.rs
  fighters/robin/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/reflet/param/vl.prcxml
Labels: bug, character change, semver:feature

#821 Chrom Hitbox Adjustments
  fighters/chrom/src/acmd/aerials.rs
  fighters/chrom/src/acmd/ground.rs
  fighters/chrom/src/acmd/smashes.rs
  fighters/chrom/src/acmd/specials.rs
  fighters/chrom/src/acmd/tilts.rs
  fighters/chrom/src/opff.rs
Labels: character change, semver:patch

#764 Cstick adjustments
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/transition.rs
  fighters/common/src/general_statuses/dash.rs
  fighters/common/src/general_statuses/jumpsquat.rs
  fighters/common/src/general_statuses/turn.rs
  fighters/common/src/misc.rs
  fighters/common/src/opff/floats.rs
  fighters/common/src/opff/other.rs
  fighters/common/src/opff/physics.rs
  fighters/common/src/opff/tech.rs
  fighters/demon/src/opff.rs
  fighters/ken/src/opff.rs
  fighters/rockman/src/status.rs
  fighters/sonic/src/status.rs
  fighters/trail/src/opff.rs
Labels: enhancement, engine, semver:patch

#824 Richter Hitbox Adjustments
  fighters/richter/src/acmd/aerials.rs
  fighters/richter/src/acmd/ground.rs
  fighters/richter/src/acmd/smashes.rs
  fighters/richter/src/acmd/tilts.rs
  fighters/richter/src/opff.rs
Labels: character change, semver:patch

#825 Lucas Fixup #2: Fair, Bair, DSmash, Special S landing frames and OU into the cosmos fix.
  fighters/lucas/src/acmd/aerials.rs
  fighters/lucas/src/acmd/smashes.rs
  fighters/lucas/src/status.rs
  romfs/source/fighter/lucas/param/vl.prcxml
Labels: semver:patch

#828 Fix short-hop tilt attacks
  dynamic/src/ext.rs
Labels: semver:patch

#834 Reinstate wavedash item pickups
  fighters/common/src/general_statuses/airdodge.rs
Labels: bug, engine, semver:patch

#842 Ryu - fix airdash momentum out of hitstun
  fighters/ryu/src/status.rs
Labels: bug, character change, semver:patch

#806 Shine Adjustments and Jump Cancel Boma Extension
  dynamic/src/ext.rs
  fighters/falco/src/acmd/specials.rs
  fighters/falco/src/opff.rs
  fighters/fox/src/acmd/specials.rs
  fighters/fox/src/opff.rs
  fighters/ness/src/acmd/specials.rs
  fighters/ness/src/opff.rs
  fighters/wolf/src/acmd/specials.rs
  fighters/wolf/src/opff.rs
Labels: character change, semver:patch

#843 Arsene fair correction
  fighters/jack/src/acmd/aerials.rs
Labels: bug, character change, semver:patch

#846 Kamui FAF corrections two, minor adjustments.
  fighters/kamui/src/acmd/tilts.rs
Labels: character change, semver:patch

#851 Falco Shine Fix
  fighters/falco/src/opff.rs
Labels: bug, character change, semver:patch

#857 Various Terry Bug-Fixes
  dynamic/src/consts.rs
  fighters/dolly/src/acmd/specials.rs
Labels: bug, character change, semver:patch

#850 Bayonetta - fix Bullet Arts hit cancels
  dynamic/src/consts.rs
  fighters/bayonetta/src/acmd/aerials.rs
  fighters/bayonetta/src/acmd/ground.rs
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/acmd/tilts.rs
  fighters/bayonetta/src/opff.rs
Labels: bug, character change, semver:patch

#832 Chrom Hitbox Fixes
  fighters/chrom/src/acmd/smashes.rs
  fighters/chrom/src/acmd/tilts.rs
Labels: bug, character change, semver:patch

#866 Little Mac Fsmash and Ftilt angle adjustments.
  fighters/littlemac/src/acmd/smashes.rs
  fighters/littlemac/src/acmd/tilts.rs
Labels: good first issue, character change, semver:patch

#852 Fix FGCs buffered dash bug
  fighters/common/src/shoto_status.rs
  fighters/demon/src/status.rs
  fighters/dolly/src/status.rs
  fighters/ken/src/status.rs
  fighters/ryu/src/status.rs
Labels: bug, character change, semver:patch

#838 Ike - smash attack/dair GFX update
  fighters/ike/src/acmd/aerials.rs
  fighters/ike/src/acmd/smashes.rs
Labels: bug, aesthetics, semver:patch

#835 Pac-Man - remove ability to hold fruit by holding B during toss
  fighters/pacman/src/acmd/specials.rs
Labels: character change, semver:patch

#836 Dr. Mario - remove multihit upB variant
  dynamic/src/consts.rs
  fighters/mariod/src/acmd/specials.rs
  fighters/mariod/src/opff.rs
Labels: character change, semver:patch

#837 Mii Swordfighter - fix Warrior Wave momentum
  fighters/miiswordsman/src/acmd/specials.rs
Labels: bug, character change, semver:patch

#839 Robin - slight adjustments
  fighters/common/src/opff/floats.rs
  fighters/robin/src/opff.rs
Labels: character change, semver:patch

#849 Chrom/Lucina - add aerial sideB1 hop
  fighters/chrom/src/lib.rs
  fighters/chrom/src/status.rs
  fighters/common/src/opff/fe.rs
  fighters/lucina/src/lib.rs
  fighters/lucina/src/status.rs
Labels: character change, semver:patch

#864 Remove backwards teeter cancels
  fighters/common/src/opff/tech.rs
Labels: bug, engine, semver:patch

#782 Pichu changes pt. 2: Charge State
  dynamic/src/consts.rs
  fighters/pichu/src/acmd/aerials.rs
  fighters/pichu/src/acmd/ground.rs
  fighters/pichu/src/acmd/other.rs
  fighters/pichu/src/acmd/smashes.rs
  fighters/pichu/src/acmd/specials.rs
  fighters/pichu/src/acmd/tilts.rs
  fighters/pichu/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#856 Fix Falco shine jc lockout
  fighters/falco/src/opff.rs
Labels: bug, character change, semver:patch

#873 Revert "No longer gets cardiac arrest"
  fighters/dolly/src/acmd/specials.rs
Labels: bug, character change, semver:patch

#870 Falco - fix Shine stall
  fighters/falco/src/acmd/specials.rs
  fighters/falco/src/opff.rs
Labels: character change, semver:patch

#853 Simon hitbox adjustments + Minor Richter adjustment
  fighters/richter/src/acmd/aerials.rs
  fighters/simon/src/acmd/aerials.rs
  fighters/simon/src/acmd/smashes.rs
  fighters/simon/src/acmd/tilts.rs
  fighters/simon/src/opff.rs
Labels: bug, character change, semver:patch

#876 Small batch of Gnw adjustments
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/gamewatch/src/acmd/aerials.rs
  fighters/gamewatch/src/acmd/smashes.rs
  fighters/gamewatch/src/acmd/specials.rs
  fighters/gamewatch/src/acmd/throws.rs
  fighters/gamewatch/src/opff.rs
  romfs/source/fighter/gamewatch/param/vl.prcxml
Labels: character change, semver:patch

#805 Metaknight changes
  fighters/metaknight/src/acmd/aerials.rs
  fighters/metaknight/src/acmd/specials.rs
  fighters/metaknight/src/acmd/throws.rs
  fighters/metaknight/src/acmd/tilts.rs
  fighters/metaknight/src/meta_quick.rs
  fighters/metaknight/src/opff.rs
  romfs/source/fighter/metaknight/param/vl.prcxml
Labels: semver:patch
