Repository HDR-Development/HewDraw-Remix, pull requests merged in 2022-02, with the labels that each got.

#88 For #48
  fighters/younglink/src/acmd/specials.rs
Labels: bug

#96 add dacus params and fix dacus
  fighters/common/src/general_statuses/attackdash.rs
  romfs/source/fighter/common/hdr/param/common.xml
Labels: bug

#116 small fix for beta releases
  .github/workflows/build.yml
Labels: bug, infrastructure

#121 fix ryujinx packaging "sd" -> "sdcard"
  scripts/build.py
Labels: infrastructure
