Repository HDR-Development/HewDraw-Remix, pull requests merged in 2022-12, with the labels that each got.

#1230 Collision improvements
  fighters/common/src/function_hooks/change_motion.rs
  fighters/common/src/function_hooks/collision.rs
  fighters/common/src/opff/other.rs
  romfs/source/fighter/common/hdr/param/common.xml
  utils/src/game_modes.rs
Labels: bug, engine, semver:patch

#1234 Update full packaging to use the new launcher
  scripts/full_package.py
Labels: infrastructure, semver:feature

#1237 Falco Dair hotfix
  fighters/falco/src/acmd/aerials.rs
Labels: character change, semver:patch

#1220 Retain momentum on ground techs
  fighters/common/src/general_statuses/passive.rs
Labels: engine, semver:patch

#1244 Updating automatic changelog generation logic
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: infrastructure, semver:patch

#1181 increase asdi distance back to previous value
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#1174 Remove universal gravity-based vertical launch speed adjustment
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#1190 Fix landing momentum when landing on slopes
  fighters/common/src/function_hooks/change_motion.rs
  fighters/common/src/function_hooks/init_settings.rs
Labels: engine, semver:patch

#1199 Replace cancel code with boma extensions
  dynamic/src/ext.rs
  fighters/brave/src/opff.rs
  fighters/buddy/src/opff.rs
  fighters/chrom/src/opff.rs
  fighters/common/src/opff/shotos.rs
  fighters/diddy/src/opff.rs
  fighters/dolly/src/opff.rs
  fighters/donkey/src/opff.rs
  fighters/edge/src/opff.rs
  fighters/falco/src/opff.rs
  fighters/fox/src/opff.rs
  fighters/gamewatch/src/opff.rs
  fighters/gekkouga/src/opff.rs
  fighters/ike/src/opff.rs
  fighters/inkling/src/opff.rs
  fighters/kamui/src/opff.rs
  fighters/kirby/src/opff.rs
  fighters/koopa/src/opff.rs
  fighters/koopajr/src/opff.rs
  fighters/littlemac/src/opff.rs
  fighters/lucario/src/opff.rs
  fighters/lucas/src/opff.rs
  fighters/lucina/src/opff.rs
  fighters/master/src/opff.rs
  fighters/miifighter/src/opff.rs
  fighters/miigunner/src/opff.rs
  fighters/miiswordsman/src/opff.rs
  fighters/miiswordsman/src/status.rs
  fighters/ness/src/opff.rs
  fighters/pacman/src/opff.rs
  fighters/pfushigisou/src/opff.rs
  fighters/pichu/src/opff.rs
  fighters/pikachu/src/opff.rs
  fighters/pikmin/src/opff.rs
  fighters/pit/src/opff.rs
  fighters/pitb/src/opff.rs
  fighters/pzenigame/src/opff.rs
  fighters/robot/src/opff.rs
  fighters/rockman/src/opff.rs
  fighters/ryu/src/opff.rs
  fighters/sheik/src/opff.rs
  fighters/shizue/src/opff.rs
  fighters/simon/src/opff.rs
  fighters/szerosuit/src/opff.rs
  fighters/trail/src/opff.rs
  fighters/wolf/src/opff.rs
  fighters/yoshi/src/opff.rs
Labels: enhancement, infrastructure, semver:patch

#1226 King K. Rool minor adjustments
  fighters/krool/src/acmd/aerials.rs
  fighters/krool/src/acmd/ground.rs
  fighters/krool/src/acmd/smashes.rs
  fighters/krool/src/acmd/tilts.rs
Labels: character change, semver:patch

#1191 Dash/Turn/Run Turn tech reimplementation
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/energy.rs
  fighters/common/src/function_hooks/transition.rs
  fighters/common/src/general_statuses/airdodge.rs
  fighters/common/src/general_statuses/dash.rs
  fighters/common/src/general_statuses/run.rs
  fighters/common/src/general_statuses/turn.rs
  fighters/common/src/general_statuses/walk.rs
  fighters/common/src/opff/physics.rs
  fighters/common/src/opff/shotos.rs
  fighters/common/src/opff/tech.rs
  fighters/common/src/shoto_status.rs
  fighters/demon/src/opff.rs
  fighters/demon/src/status.rs
  fighters/dolly/src/opff.rs
  fighters/dolly/src/status.rs
  fighters/ken/src/status.rs
  fighters/ryu/src/status.rs
  romfs/source/fighter/common/hdr/param/common.xml
  romfs/source/fighter/common/param/common.prcxml
  utils/src/modules/input.rs
Labels: engine, semver:patch

#1227 Mii Swordfighter minor adjustments
  fighters/miiswordsman/src/acmd/aerials.rs
  fighters/miiswordsman/src/acmd/ground.rs
  fighters/miiswordsman/src/acmd/smashes.rs
  fighters/miiswordsman/src/acmd/tilts.rs
Labels: character change, semver:patch

#1246 Camera changes
  fighters/common/src/function_hooks/camera.rs
  fighters/common/src/function_hooks/mod.rs
Labels: engine, semver:patch

#1214 Byleth Adjustments
  dynamic/src/consts.rs
  fighters/master/src/acmd/aerials.rs
  fighters/master/src/acmd/ground.rs
  fighters/master/src/acmd/smashes.rs
  fighters/master/src/acmd/specials.rs
  fighters/master/src/acmd/tilts.rs
  fighters/master/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#1254 Remove electric move knockback smoke farts
  fighters/common/src/general_statuses/damage.rs
Labels: aesthetics, semver:patch

#1235 Yoshi Adjustments
  fighters/yoshi/src/acmd/aerials.rs
  fighters/yoshi/src/acmd/ground.rs
  fighters/yoshi/src/acmd/other.rs
  fighters/yoshi/src/acmd/smashes.rs
  fighters/yoshi/src/acmd/specials.rs
  fighters/yoshi/src/acmd/tilts.rs
  fighters/yoshi/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/yoshi/param/vl.prcxml
Labels: character change, semver:patch

#1222 Palutena Wall Fix and damage tweaks
  fighters/palutena/src/acmd/aerials.rs
  fighters/palutena/src/acmd/ground.rs
  fighters/palutena/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/palutena/param/vl.prcxml
Labels: bug, character change, semver:patch

#1241 Projectile spawn fix rework
  fighters/common/src/function_hooks/collision.rs
Labels: bug, engine, semver:patch

#1249 Amsah tech refinements
  fighters/common/src/general_statuses/passive.rs
  fighters/common/src/opff/physics.rs
Labels: bug, engine, semver:patch

#1255 Mii Swordfighter - remove heavy tornado variant
  fighters/miiswordsman/src/acmd/other.rs
  fighters/miiswordsman/src/acmd/specials.rs
  fighters/miiswordsman/src/opff.rs
Labels: bug, character change, semver:patch

#1238 Zelda small change
  fighters/zelda/src/acmd/specials.rs
  fighters/zelda/src/acmd/tilts.rs
Labels: character change, semver:patch

#1240 Decrease character model sizes
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: engine, semver:patch

#1261 Angle-able Sonic Blade
  fighters/trail/src/acmd/specials.rs
  fighters/trail/src/opff.rs
  fighters/trail/src/status.rs
  fighters/trail/src/status/attack_air.rs
  fighters/trail/src/status/special_s.rs
  romfs/source/fighter/trail/param/vl.prcxml
Labels: enhancement, character change, semver:patch

#1257 Restore Dreamland Express input
  dynamic/src/consts.rs
  fighters/littlemac/src/acmd/ground.rs
  fighters/littlemac/src/acmd/specials.rs
Labels: bug, semver:patch

#1250 Weaken getup attacks
  fighters/common/src/function_hooks/attack.rs
Labels: engine, semver:patch

#1256 Skip results screen with start button
  fighters/common/Cargo.toml
  fighters/common/src/function_hooks/controls.rs
Labels: enhancement, semver:patch

#1263 Allows Ganon to angle Float
  dynamic/src/consts.rs
  fighters/ganon/src/acmd/specials.rs
  fighters/ganon/src/status/special_n.rs
Labels: enhancement, character change, semver:patch

#1252 Incineroar Adjustments
  fighters/gaogaen/src/acmd/smashes.rs
  fighters/gaogaen/src/acmd/specials.rs
  fighters/gaogaen/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#1262 Corrin adjustments
  fighters/kamui/src/acmd/aerials.rs
  fighters/kamui/src/acmd/tilts.rs
Labels: character change, semver:patch

#1264 Bowser Jr. Adjustments
  fighters/koopajr/src/acmd/aerials.rs
  fighters/koopajr/src/acmd/smashes.rs
  fighters/koopajr/src/acmd/specials.rs
  fighters/koopajr/src/acmd/tilts.rs
  fighters/koopajr/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/koopajr/param/vl.prcxml
Labels: character change, semver:patch

#1260 Clank/Rebound Tweaks
  romfs/source/fighter/common/param/battle_object.prcxml
Labels: engine, semver:patch

#1268 Joker Aerial Grapple Hook Adjustments
  fighters/jack/src/acmd/specials.rs
Labels: character change, semver:patch

#1243 Villager Followup Adjustments
  fighters/murabito/src/acmd/aerials.rs
  fighters/murabito/src/acmd/ground.rs
  fighters/murabito/src/acmd/other.rs
  fighters/murabito/src/acmd/tilts.rs
  fighters/murabito/src/lib.rs
  fighters/murabito/src/opff.rs
  fighters/murabito/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/murabito/param/vl.prcxml
Labels: character change, semver:patch

#1248 ECB refinements
  fighters/common/src/function_hooks/collision.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/opff/other.rs
  fighters/ganon/src/acmd/aerials.rs
  romfs/source/fighter/common/hdr/param/common.xml
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: engine, semver:patch

#1270 ECB hotfix
  romfs/source/fighter/common/hdr/param/common.xml
Labels: engine, semver:patch

#1245 Samus Slight Adjustments
  fighters/samus/src/acmd/aerials.rs
  fighters/samus/src/acmd/ground.rs
  fighters/samus/src/acmd/other.rs
Labels: character change, semver:patch
