Repository HDR-Development/HewDraw-Remix, pull requests merged in 2022-04, with the labels that each got.

#413 adding version.txt creation
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#414 debugging infrastructure
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#415 debugging infra
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#416 debugging infra
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#417 only get the upgrade zip
  .github/workflows/build_nightly.yml
Labels: semver:patch

#390 Ground movement refactor
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/function_hooks/transition.rs
  fighters/common/src/general_statuses/dash.rs
  fighters/common/src/general_statuses/turn.rs
  fighters/common/src/general_statuses/walk.rs
  fighters/common/src/opff/other.rs
  fighters/common/src/opff/physics.rs
  fighters/common/src/opff/shotos.rs
  fighters/common/src/opff/tech.rs
  fighters/common/src/shoto_status.rs
  fighters/demon/src/opff.rs
  fighters/dolly/src/opff.rs
Labels: enhancement, engine, semver:patch

#418 Jab lock rework
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/downdamage.rs
  fighters/common/src/general_statuses/mod.rs
  romfs/source/fighter/common/param/battle_object.prcxml
Labels: enhancement, engine, semver:feature

#422 fixing make beta
  .github/workflows/build_beta.yml
Labels: semver:patch

#423 packaging smashline hook and nro hook again
  scripts/full_package.py
Labels: semver:patch

#424 Update full_package.py
  scripts/full_package.py
Labels: semver:patch

#426 Update build_beta.yml
  .github/workflows/build_beta.yml
Labels: semver:patch

#427 Update full_package.py
  scripts/full_package.py
Labels: semver:patch

#429 Update build_beta.yml
  .github/workflows/build_beta.yml
Labels: semver:patch

#430 Update build_beta.yml
  .github/workflows/build_beta.yml
Labels: semver:patch

#431 Update ui_stage_db.prcxml
  romfs/source/ui/param/database/ui_stage_db.prcxml
Labels: semver:patch

#434 change upgrade_artifacts to upload upgrade.zip
  .github/workflows/build_beta.yml
Labels: semver:patch

#436 Mk improvements/adjustments
  fighters/metaknight/src/acmd/aerials.rs
  fighters/metaknight/src/acmd/ground.rs
  fighters/metaknight/src/acmd/specials.rs
  romfs/source/fighter/metaknight/param/vl.prcxml
  scripts/build.py
  scripts/pkgutil.py
Labels: character change, semver:patch

#443 Packaging updates
  .github/workflows/build_beta.yml
Labels: semver:patch

#465 Duck Hunt Clay Pigeon Hitlag Reduction
  fighters/duckhunt/src/acmd/other.rs
Labels: character change, semver:patch

#450 Taunting from Dash/Run/Runbrake and Teeter Cancelling
  fighters/common/src/general_statuses/dash.rs
  fighters/common/src/general_statuses/run.rs
  fighters/common/src/opff/tech.rs
  fighters/common/src/shoto_status.rs
Labels: enhancement, engine, semver:feature

#451 Game and Watch changes
  fighters/common/src/opff/gentleman.rs
  fighters/gamewatch/src/acmd/aerials.rs
  fighters/gamewatch/src/acmd/ground.rs
  fighters/gamewatch/src/acmd/other.rs
  fighters/gamewatch/src/acmd/specials.rs
  fighters/gamewatch/src/acmd/throws.rs
  fighters/gamewatch/src/opff.rs
  romfs/source/fighter/gamewatch/param/vl.prcxml
Labels: character change, semver:patch

#462 Reinstate vanilla cstick IRAR behavior
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/jumpsquat.rs
  fighters/common/src/opff/other.rs
Labels: enhancement, engine, semver:patch

#482 Sephiroth changes
  fighters/edge/src/acmd/aerials.rs
  fighters/edge/src/acmd/ground.rs
  fighters/edge/src/acmd/other.rs
  fighters/edge/src/acmd/smashes.rs
  fighters/edge/src/acmd/specials.rs
  fighters/edge/src/acmd/tilts.rs
  fighters/edge/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/edge/param/vl.prcxml
Labels: character change, semver:patch

#480 Greninja changes
  fighters/gekkouga/src/acmd/aerials.rs
  fighters/gekkouga/src/acmd/ground.rs
  fighters/gekkouga/src/acmd/other.rs
  fighters/gekkouga/src/acmd/throws.rs
  fighters/gekkouga/src/acmd/tilts.rs
  romfs/source/fighter/gekkouga/param/vl.prcxml
Labels: character change, semver:patch

#460 Cleanups to Marth ftilt, utilt, dtilt, nair, and up b
  fighters/marth/src/acmd/aerials.rs
  fighters/marth/src/acmd/specials.rs
  fighters/marth/src/acmd/tilts.rs
  fighters/marth/src/lib.rs
  fighters/marth/src/opff.rs
  fighters/marth/src/status.rs
  romfs/source/fighter/marth/param/vl.prcxml
Labels: character change, semver:patch

#477 Antenna Pikmin Indicator
  fighters/pikmin/src/opff.rs
  romfs/source/fighter/pikmin/param/hdr.xml
  utils/agent_params.txt
  utils/rom_watch.txt
Labels: enhancement, semver:patch

#481 Roy changes
  fighters/roy/src/acmd/aerials.rs
  fighters/roy/src/acmd/ground.rs
  fighters/roy/src/acmd/smashes.rs
  fighters/roy/src/acmd/specials.rs
  fighters/roy/src/acmd/tilts.rs
Labels: character change, semver:patch

#454 Hitlag, hit effect size, and shieldstun readjustments
  romfs/source/fighter/common/param/battle_object.prcxml
  romfs/source/fighter/common/param/common.prcxml
Labels: aesthetics, engine, semver:patch

#467 Mythra up-special cancel
  dynamic/Cargo.toml
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  dynamic/src/modules.rs
  dynamic/src/modules/status.rs
  fighters/common/src/general_statuses/airdodge.rs
  fighters/elight/src/acmd/specials.rs
  fighters/elight/src/lib.rs
  fighters/elight/src/opff.rs
  fighters/elight/src/status.rs
  fighters/elight/src/status/special_hi.rs
  fighters/elight/src/status/special_hi_attack.rs
  fighters/elight/src/status/special_hi_finish.rs
  fighters/elight/src/status/special_hi_finish2.rs
  fighters/elight/src/status/special_hi_jump.rs
  fighters/src/lib.rs
  plugin/src/lib.rs
  utils/src/modules.rs
  utils/src/modules/status.rs
Labels: semver:patch

#487 Mega Man Dash Attack Update
  fighters/rockman/src/acmd/ground.rs
Labels: aesthetics, semver:patch

#489 this removes the "developer only" empty dropdown on pr builds
  .github/workflows/pr_comment.yml
Labels: semver:patch

#452 Falcon nair readjustments
  fighters/captain/src/acmd/aerials.rs
Labels: character change, semver:patch

#490 Forgot to add Olimar's hdr.prc to config.toml
  romfs/config.json
Labels: bug

#493 Revert mythra changes to resolve nightly crashes
  dynamic/Cargo.toml
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  dynamic/src/modules.rs
  dynamic/src/modules/status.rs
  fighters/common/src/general_statuses/airdodge.rs
  fighters/elight/src/acmd/specials.rs
  fighters/elight/src/lib.rs
  fighters/elight/src/opff.rs
  fighters/elight/src/status.rs
  fighters/elight/src/status/special_hi.rs
  fighters/elight/src/status/special_hi_attack.rs
  fighters/elight/src/status/special_hi_finish.rs
  fighters/elight/src/status/special_hi_finish2.rs
  fighters/elight/src/status/special_hi_jump.rs
  fighters/src/lib.rs
  plugin/src/lib.rs
  utils/src/modules.rs
  utils/src/modules/status.rs
Labels: semver:patch

#498 Palu Reflecter Training Mode Fix
  fighters/palutena/src/opff.rs
Labels: semver:patch

#495 re-adding back mythra uspecial changes
  dynamic/Cargo.toml
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  dynamic/src/modules.rs
  dynamic/src/modules/status.rs
  fighters/common/src/general_statuses/airdodge.rs
  fighters/elight/src/acmd/specials.rs
  fighters/elight/src/lib.rs
  fighters/elight/src/opff.rs
  fighters/elight/src/status.rs
  fighters/elight/src/status/special_hi.rs
  fighters/elight/src/status/special_hi_attack.rs
  fighters/elight/src/status/special_hi_finish.rs
  fighters/elight/src/status/special_hi_finish2.rs
  fighters/elight/src/status/special_hi_jump.rs
  fighters/miiswordsman/src/acmd/specials.rs
  fighters/src/lib.rs
  plugin/Cargo.toml
  plugin/src/lib.rs
  scripts/build.py
  utils/src/modules.rs
  utils/src/modules/status.rs
Labels: semver:patch

#510 Samus shinespark alternative visual with gimmick flash instead of blue glow
  fighters/samus/src/opff.rs
Labels: aesthetics

#507 Fix crawl momentum from right to left and when you have backward speed
  fighters/common/src/general_statuses/crawl.rs
  fighters/common/src/general_statuses/mod.rs
Labels: engine, semver:patch

#521 Tap buffer extension adjustments
  fighters/common/src/general_statuses/mod.rs
  fighters/common/src/general_statuses/shield/guard_damage/exit.rs
  fighters/common/src/general_statuses/shield/guard_damage/init.rs
  fighters/common/src/general_statuses/shield/guard_off/exit.rs
  fighters/common/src/general_statuses/shield/guard_off/init.rs
Labels: engine, semver:patch

#509 Knockback gravity and tumble readjustments
  romfs/source/fighter/common/param/battle_object.prcxml
  romfs/source/fighter/common/param/common.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: engine, semver:patch

#522 Update semver_label_check.yml
  .github/workflows/semver_label_check.yml
Labels: semver:patch

#525 workflow improvements and to-beta.zip and to-nightly.zip
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
  .github/workflows/pr_build.yml
  scripts/make_diff.py
Labels: semver:patch

#528 Fix visual glitches during elemental attack hitlag
  romfs/source/fighter/common/param/common.prcxml
Labels: bug, aesthetics, semver:patch

#529 The Return of Ryujinx Packaging
  scripts/full_package.py
Labels: semver:patch
