Repository HDR-Development/HewDraw-Remix, pull requests merged in 2022-11, with the labels that each got.

#1150 Yink Adjustments
  fighters/younglink/src/acmd/aerials.rs
  fighters/younglink/src/acmd/ground.rs
  fighters/younglink/src/acmd/other.rs
  fighters/younglink/src/acmd/specials.rs
  fighters/younglink/src/acmd/tilts.rs
  fighters/younglink/src/opff.rs
Labels: character change, semver:patch

#1062 Isabelle Tweaks
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/shizue/src/acmd/aerials.rs
  fighters/shizue/src/acmd/other.rs
  fighters/shizue/src/acmd/smashes.rs
  fighters/shizue/src/acmd/specials.rs
  fighters/shizue/src/acmd/throws.rs
  fighters/shizue/src/acmd/tilts.rs
  fighters/shizue/src/lib.rs
  fighters/shizue/src/opff.rs
  fighters/shizue/src/status.rs
  fighters/shizue/src/status/special_hi.rs
  romfs/source/fighter/shizue/param/vl.prcxml
Labels: character change, semver:patch

#1113 Bayonetta changes
  fighters/bayonetta/src/acmd/aerials.rs
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/acmd/tilts.rs
Labels: character change, semver:patch

#1160 Luigi changes
  fighters/luigi/src/acmd/aerials.rs
  fighters/luigi/src/acmd/ground.rs
  fighters/luigi/src/acmd/other.rs
  fighters/luigi/src/acmd/smashes.rs
  fighters/luigi/src/acmd/specials.rs
  fighters/luigi/src/acmd/throws.rs
  fighters/luigi/src/acmd/tilts.rs
  fighters/luigi/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/luigi/param/vl.prcxml
Labels: character change, semver:patch

#1165 Sonic touch-ups
  fighters/sonic/src/acmd/smashes.rs
  fighters/sonic/src/acmd/tilts.rs
  romfs/source/fighter/sonic/param/vl.prcxml
Labels: character change, semver:patch

#1159 Robin Adjustments
  fighters/robin/src/acmd/aerials.rs
  fighters/robin/src/acmd/ground.rs
  fighters/robin/src/acmd/other.rs
  fighters/robin/src/acmd/smashes.rs
  fighters/robin/src/acmd/specials.rs
  fighters/robin/src/acmd/tilts.rs
  fighters/robin/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/reflet/param/vl.prcxml
Labels: character change, semver:patch

#1167 Buff wavedashes universally to halfway between before and now
  fighters/common/src/general_statuses/airdodge.rs
  romfs/source/fighter/common/hdr/param/common.xml
  romfs/source/fighter/common/param/fighter_param_motion.prcxml
Labels: engine, semver:patch

#1157 ECB overhaul
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/change_motion.rs
  fighters/common/src/function_hooks/collision.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/general_statuses/airdodge.rs
  fighters/common/src/opff/gimmick.rs
  fighters/common/src/opff/physics.rs
  fighters/koopajr/src/status.rs
  fighters/pickel/src/opff.rs
  romfs/source/fighter/common/hdr/param/common.xml
  romfs/source/fighter/common/hdr/param/fighter_param.xml
Labels: engine, semver:feature

#1175 Sora Jab Correction
  fighters/trail/src/acmd/ground.rs
Labels: character change, semver:patch

#1172 Robin hotfix - fix infinite Elwinds
  fighters/robin/src/acmd/specials.rs
Labels: bug, character change, semver:patch

#1173 attempt to fix the megaman crash
  fighters/common/src/function_hooks/mod.rs
Labels: bug, semver:patch

#1086 Fix Chrom Double Edge Dance aerial momentum
  fighters/chrom/src/opff.rs
  romfs/source/fighter/chrom/param/vl.prcxml
Labels: bug, character change, semver:patch

#1168 Luigi hotfix
  fighters/luigi/src/acmd/other.rs
Labels: bug, semver:patch

#1178 Sora reinstated Jab Lock Hitboxes
  fighters/trail/src/acmd/ground.rs
Labels: bug, semver:patch

#1180 Fix GnW dair landing speed and move aerial landing scripts into proper file
  fighters/gamewatch/src/acmd/aerials.rs
  fighters/gamewatch/src/acmd/other.rs
Labels: bug, character change, semver:patch

#1179 Joker - restoration of pre-ECB change gundash window
  romfs/source/fighter/jack/param/vl.prcxml
Labels: character change, semver:patch

#1169 Small Plant adjustments
  fighters/packun/src/acmd/aerials.rs
  fighters/packun/src/acmd/ground.rs
  fighters/packun/src/acmd/tilts.rs
  romfs/source/fighter/packun/param/vl.prcxml
Labels: character change, semver:patch

#1183 setup support for hid stick mods
  plugin/Cargo.toml
  plugin/src/lib.rs
  scripts/full_package.py
Labels: semver:patch

#1187 Paged SSS + Stage Striking
  romfs/source/ui/script_patch/common/stage_select_actor3.lua
Labels: semver:feature

#1193 Merge Sonic changes into HDR-Dev sonic branch
  fighters/sonic/src/acmd/aerials.rs
  fighters/sonic/src/acmd/specials.rs
  romfs/source/fighter/sonic/param/vl.prcxml
Labels: semver:patch

#1186 Stick threshold adjustments for new GCC stick mappings
  romfs/source/fighter/common/hdr/param/common.xml
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#1192 Knockback bugfixes
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/general_statuses/damage.rs
  fighters/common/src/opff/other.rs
  fighters/common/src/opff/tech.rs
Labels: bug, engine, semver:patch

#1189 ECB landing bugfixes
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/change_motion.rs
  fighters/common/src/function_hooks/collision.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/opff/other.rs
Labels: bug, engine, semver:patch

#1139 Young Link Roll Dash Attack
  fighters/younglink/src/acmd/ground.rs
  fighters/younglink/src/opff.rs
Labels: character change, semver:patch

#1171 Some dk adjustments after using the recent new DK changes
  fighters/common/src/function_hooks/controls.rs
  fighters/donkey/src/acmd/ground.rs
  fighters/donkey/src/acmd/specials.rs
  fighters/donkey/src/status.rs
  fighters/donkey/src/status/cargo_carry.rs
  fighters/donkey/src/status/special_lw.rs
  romfs/source/fighter/common/param/common.prcxml
  utils/build.rs
Labels: character change, semver:patch

#1194 Sonic
  fighters/sonic/src/acmd/aerials.rs
  fighters/sonic/src/acmd/specials.rs
  romfs/source/fighter/sonic/param/vl.prcxml
Labels: character change, semver:patch

#1195 Pichu - Discharge buff
  fighters/pichu/src/acmd/specials.rs
  fighters/pichu/src/opff.rs
  romfs/config.json
  romfs/source/fighter/pichu/param/hdr.xml
  utils/agent_params.txt
  utils/rom_watch.txt
Labels: character change, semver:patch

#1196 Steve Changes
  fighters/common/src/function_hooks/get_param.rs
  fighters/pickel/src/acmd/aerials.rs
  fighters/pickel/src/acmd/tilts.rs
  romfs/source/fighter/pickel/param/vl.prcxml
Labels: character change, semver:patch

#1201 Jigglypuff - on-hit Rest visual change
  fighters/purin/src/status.rs
Labels: character change, semver:patch

#1197 CC buff
  fighters/common/src/function_hooks/change_status.rs
Labels: engine, semver:patch

#1205 Changed the logic for clearing STATUS vars
  fighters/common/src/function_hooks/init_settings.rs
Labels: bug, engine, semver:patch

#1206 Fixing automatic build queuing
  .github/workflows/build_nightly.yml
Labels: infrastructure, semver:patch

#1210 Revert hid and stick thresholds
  plugin/Cargo.toml
  plugin/src/lib.rs
  romfs/source/fighter/common/hdr/param/common.xml
  romfs/source/fighter/common/param/common.prcxml
  scripts/full_package.py
Labels: engine, semver:patch

#1204 Mewtwo Fair Rework
  fighters/mewtwo/src/acmd/aerials.rs
Labels: character change, semver:patch

#1211 Fixes the meter UI and related control menu crash
  utils/src/ui.rs
Labels: bug, semver:patch

#1217 Dark Samus vfx hotfix
  fighters/samusd/src/acmd/ground.rs
Labels: aesthetics, semver:patch

#1216 Gnw nair hotfix
  fighters/gamewatch/src/acmd/aerials.rs
Labels: bug, semver:patch

#1203 ZSS changes
  dynamic/src/consts.rs
  fighters/szerosuit/src/acmd/aerials.rs
  fighters/szerosuit/src/acmd/ground.rs
  fighters/szerosuit/src/acmd/other.rs
  fighters/szerosuit/src/acmd/smashes.rs
  fighters/szerosuit/src/acmd/specials.rs
  fighters/szerosuit/src/acmd/throws.rs
  fighters/szerosuit/src/acmd/tilts.rs
  fighters/szerosuit/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/szerosuit/param/vl.prcxml
Labels: character change, semver:patch

#1182 Wavedash/waveland landing speed readjustment
  fighters/common/src/general_statuses/airdodge.rs
Labels: engine, semver:patch

#1202 Projectile behavior fix
  fighters/common/src/function_hooks/collision.rs
Labels: bug, engine, semver:patch

#1208 Joker Adjustments
  fighters/jack/src/acmd/aerials.rs
  fighters/jack/src/acmd/smashes.rs
  romfs/source/fighter/jack/param/vl.prcxml
Labels: character change, semver:patch

#1207 Robin Nair/Thoron tweaks
  fighters/robin/src/acmd/aerials.rs
  fighters/robin/src/acmd/specials.rs
Labels: character change, semver:patch

#1219 New Modes hotfix
  romfs/source/ui/docs/gamemodes.html
Labels: bug, semver:patch

#1185 Villager changes!
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/murabito/src/acmd/aerials.rs
  fighters/murabito/src/acmd/other.rs
  fighters/murabito/src/acmd/smashes.rs
  fighters/murabito/src/acmd/specials.rs
  fighters/murabito/src/acmd/tilts.rs
  fighters/murabito/src/opff.rs
Labels: character change, semver:patch

#1218 Fix up ZSS dair, dash grab, and pivot grab
  fighters/szerosuit/src/acmd/aerials.rs
  fighters/szerosuit/src/acmd/other.rs
  fighters/szerosuit/src/acmd/specials.rs
  fighters/szerosuit/src/acmd/tilts.rs
  fighters/szerosuit/src/opff.rs
Labels: character change, semver:patch

#1209 Zelda adjustments
  dynamic/src/consts.rs
  fighters/zelda/src/acmd/aerials.rs
  fighters/zelda/src/acmd/ground.rs
  fighters/zelda/src/acmd/other.rs
  fighters/zelda/src/acmd/smashes.rs
  fighters/zelda/src/acmd/specials.rs
  fighters/zelda/src/acmd/tilts.rs
  fighters/zelda/src/lib.rs
  fighters/zelda/src/opff.rs
  fighters/zelda/src/status.rs
  fighters/zelda/src/status/dein.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/zelda/param/vl.prcxml
Labels: character change, semver:patch

#1225 Improve matching against previous merges for queued nightlies
  .github/workflows/build_nightly.yml
Labels: infrastructure, semver:patch

#1224 Joker DAIR and Recovery Hotfix
  fighters/jack/src/acmd/aerials.rs
  romfs/source/fighter/jack/param/vl.prcxml
Labels: bug, semver:patch

#1228 Rocket league car
  dynamic/src/game_modes.rs
  plugin/src/lib.rs
  plugin/src/online.rs
  romfs/source/ui/docs/gamemodes.html
  utils/src/game_modes.rs
  utils/src/lib.rs
Labels: infrastructure, semver:feature

#1229 Increase beta tag search limit to fix beta build
  .github/workflows/build_beta.yml
Labels: infrastructure, semver:patch
