Repository HDR-Development/HewDraw-Remix, pull requests merged in 2022-09, with the labels that each got.

#1002 Merge spike overhaul into main repo
  fighters/captain/src/acmd/tilts.rs
  fighters/chrom/src/acmd/aerials.rs
  fighters/dolly/src/acmd/specials.rs
  fighters/edge/src/acmd/aerials.rs
  fighters/falco/src/acmd/other.rs
  fighters/gekkouga/src/acmd/aerials.rs
  fighters/ken/src/acmd/aerials.rs
  fighters/lucas/src/acmd/aerials.rs
  fighters/mario/src/acmd/aerials.rs
  fighters/marth/src/acmd/aerials.rs
  fighters/marth/src/acmd/specials.rs
  fighters/miifighter/src/acmd/aerials.rs
  fighters/miigunner/src/acmd/aerials.rs
  fighters/miigunner/src/acmd/specials.rs
  fighters/packun/src/acmd/aerials.rs
  fighters/pichu/src/acmd/aerials.rs
  fighters/richter/src/acmd/aerials.rs
  fighters/robin/src/acmd/aerials.rs
  fighters/robin/src/acmd/other.rs
  fighters/robot/src/acmd/aerials.rs
  fighters/rockman/src/acmd/other.rs
  fighters/ryu/src/acmd/aerials.rs
  fighters/samusd/src/acmd/aerials.rs
  fighters/shulk/src/acmd/aerials.rs
Labels: enhancement, engine, semver:patch

#1005 Json content hashes
  .gitignore
  scripts/full_package.py
  scripts/hash_package.py
Labels: infrastructure, semver:patch

#1004 check for fighter or weapon
  fighters/common/src/function_hooks/change_motion.rs
  fighters/common/src/function_hooks/djcancel.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/common/src/function_hooks/is_flag.rs
  fighters/common/src/function_hooks/transition.rs
  plugin/Cargo.toml
Labels: bug, semver:patch

#997 Add double traction during item throws
  fighters/common/src/opff/physics.rs
Labels: engine, semver:patch

#1001 Turnaround improvements
  fighters/common/src/function_hooks/is_flag.rs
  fighters/common/src/general_statuses/mod.rs
Labels: engine, semver:patch

#1010 Directional airdodge adjustments
  dynamic/src/ext.rs
  fighters/common/src/general_statuses/airdodge.rs
Labels: engine, semver:patch

#1017 Perfect Pivot window adjustment
  romfs/source/fighter/common/hdr/param/common.xml
Labels: engine, semver:patch

#1012 Prevent grab input from triggering attack/shield on ground
  fighters/common/src/general_statuses/mod.rs
Labels: engine, semver:patch

#1025 Fix tilt button causing shield drop
  dynamic/src/ext.rs
Labels: bug, engine, semver:patch

#1019 Add support for changing the cliff hangdata at runtime
  dynamic/src/ext.rs
Labels: engine, semver:patch

#1026 Incineroar - adjust dsmash hitboxes
  fighters/gaogaen/src/acmd/smashes.rs
Labels: character change, semver:patch

#1014 Common parameter adjustments
  romfs/source/fighter/common/param/common.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: engine, semver:patch

#1033 Spike adjustments hotfix
  fighters/demon/src/acmd/smashes.rs
  fighters/marth/src/acmd/aerials.rs
Labels: bug, character change, semver:patch

#1015 Small batch of Bayonetta changes
  fighters/bayonetta/src/acmd/aerials.rs
  fighters/bayonetta/src/acmd/ground.rs
  fighters/bayonetta/src/acmd/tilts.rs
  fighters/bayonetta/src/opff.rs
  romfs/source/fighter/bayonetta/param/vl.prcxml
Labels: character change, semver:patch

#1030 Knockback adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/effect.rs
  fighters/common/src/general_statuses/damage.rs
  fighters/common/src/general_statuses/dead.rs
  fighters/common/src/general_statuses/mod.rs
  romfs/source/fighter/common/param/battle_object.prcxml
Labels: engine, semver:patch

#1032 Fix edge slipoffs after dash attack
  fighters/common/src/general_statuses/attackdash.rs
Labels: engine, semver:patch

#1040 Update lib.rs
  plugin/src/lib.rs
Labels: bug, crash, semver:patch

#1034 Zair landing lag adjustments
  fighters/lucas/src/acmd/aerials.rs
  fighters/samus/src/acmd/aerials.rs
  fighters/samusd/src/acmd/aerials.rs
  fighters/szerosuit/src/acmd/aerials.rs
  fighters/toonlink/src/acmd/aerials.rs
  fighters/younglink/src/acmd/aerials.rs
Labels: character change, semver:patch

#1029 Zelda rework
  fighters/zelda/src/acmd/aerials.rs
  fighters/zelda/src/acmd/ground.rs
  fighters/zelda/src/acmd/other.rs
  fighters/zelda/src/acmd/smashes.rs
  fighters/zelda/src/acmd/specials.rs
  fighters/zelda/src/acmd/tilts.rs
  fighters/zelda/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/zelda/param/vl.prcxml
Labels: character change, semver:patch

#1044 Bats Within/Foresight adjustments
  fighters/bayonetta/src/acmd/other.rs
  romfs/source/fighter/common/param/fighter_param_motion.prcxml
  romfs/source/fighter/elight/param/vl.prcxml
Labels: character change, semver:patch

#1038 Revert B-Reverse/turnaround B stick threshold
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#1037 Fix grounded spikes causing "void" bug
  fighters/common/src/function_hooks/effect.rs
  fighters/common/src/general_statuses/damage.rs
Labels: bug, engine, semver:patch

#1046 Suicide throw mash-out adjustment
  fighters/common/src/opff/other.rs
  romfs/source/fighter/common/hdr/param/common.xml
Labels: engine, semver:patch

#1016 Dark Samus adjustments
  dynamic/src/consts.rs
  fighters/samusd/src/acmd/aerials.rs
  fighters/samusd/src/acmd/ground.rs
  fighters/samusd/src/acmd/other.rs
  fighters/samusd/src/acmd/specials.rs
  fighters/samusd/src/acmd/tilts.rs
  fighters/samusd/src/lib.rs
  fighters/samusd/src/opff.rs
  fighters/samusd/src/status.rs
  romfs/source/fighter/samusd/param/vl.prcxml
Labels: character change, semver:patch

#1039 King Dedede - Gordo Throw adjustments
  fighters/dedede/src/acmd/aerials.rs
  fighters/dedede/src/acmd/other.rs
  fighters/dedede/src/opff.rs
  romfs/source/fighter/dedede/param/vl.prcxml
Labels: character change, semver:patch

#1036 ASDI adjustments
  fighters/common/src/general_statuses/airdodge.rs
  fighters/common/src/general_statuses/damage.rs
  romfs/source/fighter/common/param/battle_object.prcxml
  romfs/source/fighter/common/param/common.prcxml
Labels: bug, engine, semver:patch

#1041 Duck Hunt Tweaks
  fighters/duckhunt/src/acmd/aerials.rs
  fighters/duckhunt/src/acmd/ground.rs
  fighters/duckhunt/src/acmd/other.rs
  fighters/duckhunt/src/acmd/specials.rs
  fighters/duckhunt/src/acmd/tilts.rs
  fighters/duckhunt/src/lib.rs
  fighters/duckhunt/src/opff.rs
Labels: character change, semver:patch

#1056 Increase dash stick threshold
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch
