Repository HDR-Development/HewDraw-Remix, pull requests merged in 2022-05, with the labels that each got.

#534 Fix Marth not running the common FE OPFF appropriately
  fighters/common/src/opff/fe.rs
  fighters/marth/src/opff.rs
Labels: bug, character change, semver:patch

#553 Fix Villager/Steve aerial attack momentum
  fighters/common/src/general_statuses/jump.rs
Labels: bug, semver:patch

#544 Delete ui_tips_db.prcxml
  romfs/source/ui/param/database/ui_tips_db.prcxml
Labels: semver:patch

#561 Fix jab 2 and 3 still coming out under certain circumstances
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: bug, character change, semver:patch

#464 Fix tethers not being edgehoggable
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/function_hooks/ledges.rs
  fighters/common/src/opff/ledges.rs
  romfs/source/fighter/common/param/common.prcxml
Labels: bug, engine, semver:patch

#560 Ike rework
  dynamic/src/consts.rs
  fighters/ike/src/acmd/aerials.rs
  fighters/ike/src/acmd/ground.rs
  fighters/ike/src/acmd/other.rs
  fighters/ike/src/acmd/smashes.rs
  fighters/ike/src/acmd/specials.rs
  fighters/ike/src/acmd/throws.rs
  fighters/ike/src/acmd/tilts.rs
  fighters/ike/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/ike/param/vl.prcxml
Labels: character change, semver:patch

#514 Dark Pit adjustments
  fighters/pitb/src/acmd/aerials.rs
  fighters/pitb/src/acmd/smashes.rs
  fighters/pitb/src/acmd/specials.rs
  fighters/pitb/src/acmd/tilts.rs
Labels: semver:patch

#518 Little Mac adjustments
  dynamic/src/consts.rs
  fighters/littlemac/src/acmd/aerials.rs
  fighters/littlemac/src/acmd/ground.rs
  fighters/littlemac/src/acmd/other.rs
  fighters/littlemac/src/acmd/smashes.rs
  fighters/littlemac/src/acmd/specials.rs
  fighters/littlemac/src/acmd/tilts.rs
Labels: semver:patch

#595 Decrease jostle overlap rate 0.66 -> 0.3, remove vanilla jostle during standing/dashgrabs
  fighters/common/src/function_hooks/init_settings.rs
  romfs/source/fighter/common/param/battle_object.prcxml
Labels: engine, semver:patch

#562 Snake changes
  fighters/snake/src/acmd/aerials.rs
  fighters/snake/src/acmd/ground.rs
  fighters/snake/src/acmd/other.rs
  fighters/snake/src/acmd/specials.rs
  fighters/snake/src/acmd/tilts.rs
  fighters/snake/src/lib.rs
  fighters/snake/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/snake/param/vl.prcxml
Labels: character change, semver:patch

#563 Lucas changes
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/ledges.rs
  fighters/lucas/src/acmd/aerials.rs
  fighters/lucas/src/acmd/ground.rs
  fighters/lucas/src/acmd/other.rs
  fighters/lucas/src/acmd/smashes.rs
  fighters/lucas/src/acmd/specials.rs
  fighters/lucas/src/acmd/throws.rs
  fighters/lucas/src/acmd/tilts.rs
  fighters/lucas/src/opff.rs
  fighters/lucas/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/lucas/param/vl.prcxml
Labels: character change, semver:patch

#592 Revert long jab lock animation KB threshold to vanilla
  romfs/source/fighter/common/param/battle_object.prcxml
Labels: engine, semver:patch

#581 Hero changes
  fighters/brave/src/acmd/aerials.rs
  fighters/brave/src/acmd/ground.rs
  fighters/brave/src/acmd/mod.rs
  fighters/brave/src/acmd/other.rs
  fighters/brave/src/acmd/smashes.rs
  fighters/brave/src/acmd/specials.rs
  fighters/brave/src/acmd/tilts.rs
  fighters/brave/src/opff.rs
  romfs/source/fighter/brave/param/vl.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#569 Kazuya changes
  dynamic/src/consts.rs
  fighters/demon/src/acmd/aerials.rs
  fighters/demon/src/acmd/ground.rs
  fighters/demon/src/acmd/specials.rs
  fighters/demon/src/acmd/tilts.rs
  fighters/demon/src/opff.rs
  fighters/demon/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/demon/param/vl.prcxml
Labels: character change, semver:patch

#565 Diddy changes
  fighters/common/src/function_hooks/ledges.rs
  fighters/diddy/src/acmd/aerials.rs
  fighters/diddy/src/acmd/ground.rs
  fighters/diddy/src/acmd/smashes.rs
  fighters/diddy/src/acmd/specials.rs
  fighters/diddy/src/acmd/throws.rs
  fighters/diddy/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/diddy/param/vl.prcxml
  romfs/source/item/banana/param/param.prcxml
Labels: character change, semver:patch

#457 Banjo changes
  dynamic/src/consts.rs
  fighters/buddy/src/acmd/aerials.rs
  fighters/buddy/src/acmd/ground.rs
  fighters/buddy/src/acmd/mod.rs
  fighters/buddy/src/acmd/other.rs
  fighters/buddy/src/acmd/smashes.rs
  fighters/buddy/src/acmd/specials.rs
  fighters/buddy/src/acmd/throws.rs
  fighters/buddy/src/acmd/tilts.rs
  fighters/buddy/src/opff.rs
  romfs/source/fighter/buddy/param/vl.prcxml
Labels: character change, semver:patch

#585 Dedede changes
  fighters/dedede/src/acmd/aerials.rs
  fighters/dedede/src/acmd/ground.rs
  fighters/dedede/src/acmd/other.rs
  fighters/dedede/src/acmd/smashes.rs
  fighters/dedede/src/acmd/specials.rs
  fighters/dedede/src/acmd/throws.rs
  fighters/dedede/src/acmd/tilts.rs
  fighters/dedede/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/dedede/param/vl.prcxml
Labels: character change, semver:patch

#567 Steve changes
  dynamic/src/consts.rs
  fighters/pickel/src/acmd/aerials.rs
  fighters/pickel/src/acmd/other.rs
  fighters/pickel/src/acmd/tilts.rs
  fighters/pickel/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#572 Inkling changes
  dynamic/src/consts.rs
  fighters/inkling/src/acmd/aerials.rs
  fighters/inkling/src/acmd/ground.rs
  fighters/inkling/src/acmd/other.rs
  fighters/inkling/src/acmd/smashes.rs
  fighters/inkling/src/acmd/specials.rs
  fighters/inkling/src/acmd/throws.rs
  fighters/inkling/src/acmd/tilts.rs
  fighters/inkling/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/inkling/param/vl.prcxml
Labels: character change, semver:patch

#574 Bayonetta changes
  dynamic/src/consts.rs
  fighters/bayonetta/src/acmd/aerials.rs
  fighters/bayonetta/src/acmd/ground.rs
  fighters/bayonetta/src/acmd/other.rs
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/acmd/tilts.rs
  fighters/bayonetta/src/opff.rs
  romfs/source/fighter/bayonetta/param/vl.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#573 ZSS changes
  fighters/szerosuit/src/acmd/aerials.rs
  fighters/szerosuit/src/acmd/ground.rs
  fighters/szerosuit/src/acmd/other.rs
  fighters/szerosuit/src/acmd/specials.rs
  fighters/szerosuit/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/szerosuit/param/vl.prcxml
Labels: character change, semver:patch

#564 Wario changes
  fighters/wario/src/acmd/aerials.rs
  fighters/wario/src/acmd/ground.rs
  fighters/wario/src/acmd/smashes.rs
  fighters/wario/src/acmd/specials.rs
  fighters/wario/src/acmd/throws.rs
  fighters/wario/src/acmd/tilts.rs
  fighters/wario/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/wario/param/vl.prcxml
Labels: character change, semver:patch

#568 Mii Brawler changes
  dynamic/src/consts.rs
  fighters/miifighter/src/acmd/aerials.rs
  fighters/miifighter/src/acmd/ground.rs
  fighters/miifighter/src/acmd/other.rs
  fighters/miifighter/src/acmd/smashes.rs
  fighters/miifighter/src/acmd/specials.rs
  fighters/miifighter/src/acmd/throws.rs
  fighters/miifighter/src/acmd/tilts.rs
  fighters/miifighter/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/miifighter/param/vl.prcxml
Labels: character change, semver:patch

#576 Incineroar changes
  dynamic/src/consts.rs
  fighters/gaogaen/src/acmd/aerials.rs
  fighters/gaogaen/src/acmd/ground.rs
  fighters/gaogaen/src/acmd/smashes.rs
  fighters/gaogaen/src/acmd/specials.rs
  fighters/gaogaen/src/acmd/throws.rs
  fighters/gaogaen/src/acmd/tilts.rs
  fighters/gaogaen/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#580 Sheik changes
  fighters/sheik/src/acmd/aerials.rs
  fighters/sheik/src/acmd/ground.rs
  fighters/sheik/src/acmd/other.rs
  fighters/sheik/src/acmd/smashes.rs
  fighters/sheik/src/acmd/specials.rs
  fighters/sheik/src/acmd/tilts.rs
  fighters/sheik/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/sheik/param/vl.prcxml
Labels: character change, semver:patch

#579 Cloud changes
  fighters/cloud/src/acmd/aerials.rs
  fighters/cloud/src/acmd/ground.rs
  fighters/cloud/src/acmd/other.rs
  fighters/cloud/src/acmd/smashes.rs
  fighters/cloud/src/acmd/tilts.rs
  romfs/source/fighter/cloud/param/vl.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#583 Mario changes
  dynamic/src/consts.rs
  fighters/mario/src/acmd/aerials.rs
  fighters/mario/src/acmd/ground.rs
  fighters/mario/src/acmd/other.rs
  fighters/mario/src/acmd/smashes.rs
  fighters/mario/src/acmd/specials.rs
  fighters/mario/src/acmd/tilts.rs
  fighters/mario/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/mario/param/vl.prcxml
Labels: character change, semver:patch

#584 Dr. Mario changes
  dynamic/src/consts.rs
  fighters/mariod/src/acmd/aerials.rs
  fighters/mariod/src/acmd/ground.rs
  fighters/mariod/src/acmd/other.rs
  fighters/mariod/src/acmd/smashes.rs
  fighters/mariod/src/acmd/specials.rs
  fighters/mariod/src/acmd/throws.rs
  fighters/mariod/src/acmd/tilts.rs
  fighters/mariod/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/mariod/param/vl.prcxml
Labels: character change, semver:patch

#577 Ryu changes
  dynamic/src/consts.rs
  fighters/common/src/opff/shotos.rs
  fighters/ryu/src/acmd/aerials.rs
  fighters/ryu/src/acmd/ground.rs
  fighters/ryu/src/acmd/other.rs
  fighters/ryu/src/acmd/smashes.rs
  fighters/ryu/src/acmd/specials.rs
  fighters/ryu/src/acmd/tilts.rs
  fighters/ryu/src/lib.rs
  fighters/ryu/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/common/param/fighter_param_motion.prcxml
Labels: character change, semver:patch

#575 Ken changes
  fighters/common/src/opff/shotos.rs
  fighters/ken/src/acmd/aerials.rs
  fighters/ken/src/acmd/ground.rs
  fighters/ken/src/acmd/mod.rs
  fighters/ken/src/acmd/other.rs
  fighters/ken/src/acmd/smashes.rs
  fighters/ken/src/acmd/specials.rs
  fighters/ken/src/acmd/throws.rs
  fighters/ken/src/acmd/tilts.rs
  fighters/ken/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/common/param/fighter_param_motion.prcxml
  romfs/source/fighter/ken/param/vl.prcxml
Labels: character change, semver:patch

#558 Byleth changes
  dynamic/src/consts.rs
  fighters/master/src/acmd/aerials.rs
  fighters/master/src/acmd/ground.rs
  fighters/master/src/acmd/other.rs
  fighters/master/src/acmd/smashes.rs
  fighters/master/src/acmd/specials.rs
  fighters/master/src/acmd/throws.rs
  fighters/master/src/acmd/tilts.rs
  fighters/master/src/opff.rs
  romfs/source/fighter/master/param/vl.prcxml
Labels: character change, semver:patch

#548 Zelda changes
  fighters/zelda/src/acmd/aerials.rs
  fighters/zelda/src/acmd/ground.rs
  fighters/zelda/src/acmd/other.rs
  fighters/zelda/src/acmd/specials.rs
  fighters/zelda/src/acmd/tilts.rs
  fighters/zelda/src/lib.rs
  fighters/zelda/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/zelda/param/vl.prcxml
Labels: character change, semver:patch

#541 Sora
  dynamic/src/consts.rs
  fighters/trail/src/acmd/aerials.rs
  fighters/trail/src/acmd/ground.rs
  fighters/trail/src/acmd/mod.rs
  fighters/trail/src/acmd/other.rs
  fighters/trail/src/acmd/smashes.rs
  fighters/trail/src/acmd/specials.rs
  fighters/trail/src/acmd/tilts.rs
  fighters/trail/src/opff.rs
  fighters/trail/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/trail/param/vl.prcxml
Labels: character change, semver:patch

#587 Fox changes
  fighters/fox/src/acmd/aerials.rs
  fighters/fox/src/acmd/ground.rs
  fighters/fox/src/acmd/specials.rs
  fighters/fox/src/acmd/throws.rs
  fighters/fox/src/acmd/tilts.rs
  fighters/fox/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/fox/param/vl.prcxml
Labels: character change, semver:patch

#582 Falco changes
  fighters/falco/src/acmd/aerials.rs
  fighters/falco/src/acmd/ground.rs
  fighters/falco/src/acmd/other.rs
  fighters/falco/src/acmd/specials.rs
  fighters/falco/src/acmd/tilts.rs
  fighters/falco/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/falco/param/vl.prcxml
Labels: character change, semver:patch

#588 Wolf changes
  fighters/wolf/src/acmd/aerials.rs
  fighters/wolf/src/acmd/other.rs
  fighters/wolf/src/acmd/smashes.rs
  fighters/wolf/src/acmd/specials.rs
  fighters/wolf/src/acmd/throws.rs
  fighters/wolf/src/acmd/tilts.rs
  fighters/wolf/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/wolf/param/vl.prcxml
Labels: character change, semver:patch

#570 Joker changes
  fighters/jack/src/acmd/aerials.rs
  fighters/jack/src/acmd/other.rs
  fighters/jack/src/acmd/smashes.rs
  fighters/jack/src/acmd/specials.rs
  fighters/jack/src/acmd/tilts.rs
  fighters/jack/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/jack/param/vl.prcxml
Labels: character change, semver:patch

#578 Daisy changes
  fighters/daisy/src/acmd/aerials.rs
  fighters/daisy/src/acmd/ground.rs
  fighters/daisy/src/acmd/other.rs
  fighters/daisy/src/acmd/smashes.rs
  fighters/daisy/src/acmd/specials.rs
  fighters/daisy/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/daisy/param/vl.prcxml
Labels: character change, semver:patch

#559 Terry changes
  dynamic/src/consts.rs
  fighters/dolly/src/acmd/aerials.rs
  fighters/dolly/src/acmd/ground.rs
  fighters/dolly/src/acmd/other.rs
  fighters/dolly/src/acmd/smashes.rs
  fighters/dolly/src/acmd/specials.rs
  fighters/dolly/src/acmd/tilts.rs
  fighters/dolly/src/opff.rs
  romfs/source/fighter/common/param/common.prcxml
  romfs/source/fighter/dolly/param/vl.prcxml
Labels: character change, semver:patch

#539 Dark Samus adjustments
  fighters/common/src/opff/floats.rs
  fighters/samusd/src/acmd/aerials.rs
  fighters/samusd/src/acmd/ground.rs
  fighters/samusd/src/acmd/other.rs
  fighters/samusd/src/acmd/smashes.rs
  fighters/samusd/src/acmd/tilts.rs
Labels: character change, semver:patch

#571 R.O.B. changes
  dynamic/src/consts.rs
  fighters/robot/src/acmd/aerials.rs
  fighters/robot/src/acmd/ground.rs
  fighters/robot/src/acmd/other.rs
  fighters/robot/src/acmd/specials.rs
  fighters/robot/src/acmd/throws.rs
  fighters/robot/src/acmd/tilts.rs
  fighters/robot/src/opff.rs
  romfs/source/fighter/robot/param/vl.prcxml
Labels: character change, semver:feature

#599 Small Quick Draw instakill charge nerfs
  fighters/ike/src/opff.rs
  romfs/source/fighter/ike/param/vl.prcxml
Labels: character change, semver:patch

#593 Ness - PM PK Rocket behavior
  fighters/common/src/function_hooks/ledges.rs
  fighters/ness/src/status.rs
Labels: enhancement, character change, semver:patch

#605 Updated Dark Samus missing params
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/samusd/param/vl.prcxml
Labels: character change, semver:patch

#616 updating the docker image
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
  .github/workflows/pr_build.yml
Labels: semver:patch
