Repository HDR-Development/HewDraw-Remix, pull requests merged in 2022-10, with the labels that each got.

#1055 Teching adjustments
  fighters/common/src/general_statuses/airdodge.rs
  fighters/common/src/general_statuses/passive.rs
Labels: bug, engine, semver:patch

#1050 Small Incineroar changes
  fighters/gaogaen/src/acmd/other.rs
  fighters/gaogaen/src/acmd/specials.rs
  fighters/gaogaen/src/acmd/throws.rs
Labels: character change, semver:patch

#1047 Small set of Marth changes
  fighters/marth/src/acmd/aerials.rs
  fighters/marth/src/acmd/smashes.rs
  fighters/marth/src/acmd/specials.rs
  fighters/marth/src/acmd/tilts.rs
  romfs/source/fighter/marth/param/vl.prcxml
Labels: character change, semver:patch

#1069 Merging into Corrin changes
  fighters/kamui/src/acmd/ground.rs
  fighters/kamui/src/acmd/specials.rs
  fighters/kamui/src/acmd/tilts.rs
  fighters/kamui/src/opff.rs
Labels: character change, semver:patch

#1075 Merging Corrin Stuff
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/kamui/src/acmd/aerials.rs
  fighters/kamui/src/acmd/ground.rs
  fighters/kamui/src/acmd/specials.rs
  fighters/kamui/src/acmd/throws.rs
  fighters/kamui/src/opff.rs
Labels: character change, semver:patch

#1063 More knockback adjustments
  fighters/common/src/function_hooks/effect.rs
  fighters/common/src/general_statuses/damage.rs
  romfs/source/fighter/common/param/effect.prcxml
Labels: bug, aesthetics, semver:patch

#1077 King K. Rool Adjustments
  fighters/krool/src/acmd/aerials.rs
  fighters/krool/src/acmd/ground.rs
  fighters/krool/src/acmd/smashes.rs
  fighters/krool/src/acmd/specials.rs
  fighters/krool/src/acmd/throws.rs
  fighters/krool/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#1043 Pichu - Charge State adjustments
  dynamic/src/consts.rs
  fighters/pichu/src/acmd/specials.rs
  fighters/pichu/src/opff.rs
Labels: character change, semver:patch

#1080 Jump Squat Adjustments
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#1048 Kazuya changes
  fighters/demon/Cargo.toml
  fighters/demon/src/acmd/aerials.rs
  fighters/demon/src/acmd/ground.rs
  fighters/demon/src/acmd/other.rs
  fighters/demon/src/acmd/specials.rs
  fighters/demon/src/acmd/throws.rs
  fighters/demon/src/acmd/tilts.rs
  fighters/demon/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#1076 Dr. Mario - slight adjustments
  dynamic/src/consts.rs
  fighters/mariod/src/acmd/aerials.rs
  fighters/mariod/src/acmd/smashes.rs
  fighters/mariod/src/acmd/specials.rs
  fighters/mariod/src/acmd/tilts.rs
Labels: bug, character change, semver:patch

#1060 Banjo's falling shockpad hitbox more accurately reflects its model
  fighters/buddy/src/acmd/other.rs
Labels: character change, semver:patch

#1073 Non-tumble hitstun landing adjustment
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/mod.rs
Labels: engine, semver:patch

#1095 Add .gitattributes file to standardize autocrlf
  .gitattributes
Labels: infrastructure, semver:patch

#1021 Falco laser fixes + adjustments
  fighters/falco/src/acmd/other.rs
Labels: character change, semver:patch

#1096 Adding deletion lists for nightly-beta switching
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: infrastructure, semver:patch

#1097 minor fix to deletions script
  scripts/diff_lib.py
Labels: semver:patch

#1093 Mewtwo Upthrow and Aerial Disable Adjustments
  fighters/mewtwo/src/acmd/specials.rs
  fighters/mewtwo/src/acmd/throws.rs
Labels: character change, semver:patch

#1053 Fix projectiles dying inside platforms/ground
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/collision.rs
  fighters/common/src/function_hooks/mod.rs
Labels: bug, engine, semver:patch

#1103 Increase jostle on dash grabs
  fighters/common/src/general_statuses/catch/catchcut.rs
  fighters/common/src/general_statuses/catch/catchdash.rs
  fighters/common/src/general_statuses/catch/mod.rs
  fighters/common/src/general_statuses/mod.rs
Labels: engine, semver:patch

#1101 Allow Taunt Footstools to High-Jump
  fighters/common/src/general_statuses/footstool.rs
Labels: bug, engine, semver:patch

#1051 Implement Dash Attack Slip-Offs and Roll-Offs
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/attackdash.rs
Labels: engine, semver:patch

#1100 Dark Samus - Charge Shot audio fix and Nair changes
  fighters/samusd/src/acmd/aerials.rs
  fighters/samusd/src/acmd/other.rs
  fighters/samusd/src/acmd/specials.rs
Labels: character change, semver:patch

#1109 bye bye phantoms (pog)
  fighters/common/src/function_hooks/mod.rs
Labels: semver:patch

#1067 Corrin re-rework
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/kamui/src/acmd/aerials.rs
  fighters/kamui/src/acmd/ground.rs
  fighters/kamui/src/acmd/smashes.rs
  fighters/kamui/src/acmd/specials.rs
  fighters/kamui/src/acmd/throws.rs
  fighters/kamui/src/acmd/tilts.rs
  fighters/kamui/src/lib.rs
  fighters/kamui/src/opff.rs
  fighters/kamui/src/status.rs
  fighters/kamui/src/status/special_lw.rs
Labels: character change, semver:patch

#1110 change flick y impl for dash drop
  dynamic/src/ext.rs
  fighters/common/src/opff/tech.rs
Labels: semver:patch

#1112 Weight Adjustment List
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#1107 Disable Aerial Jumps while Floating
  fighters/common/src/function_hooks/transition.rs
Labels: bug, engine, semver:patch

#994 Shulk adjustments
  fighters/shulk/src/acmd/aerials.rs
  fighters/shulk/src/acmd/ground.rs
  fighters/shulk/src/acmd/smashes.rs
  fighters/shulk/src/acmd/specials.rs
  fighters/shulk/src/acmd/throws.rs
  fighters/shulk/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/shulk/param/vl.prcxml
Labels: character change, semver:patch

#1135 Shulk hotfix
  fighters/shulk/src/acmd/aerials.rs
  fighters/shulk/src/acmd/ground.rs
  fighters/shulk/src/acmd/tilts.rs
Labels: bug, semver:patch

#1094 Remove extra hold frames on smash attacks
  romfs/source/fighter/common/param/common.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: engine, semver:patch

#1079 Falco aim lasers during up throw and back throw
  fighters/falco/src/acmd/throws.rs
  fighters/falco/src/opff.rs
Labels: character change, semver:patch

#1066 Gnw changes
  fighters/gamewatch/src/acmd/aerials.rs
  fighters/gamewatch/src/acmd/ground.rs
  fighters/gamewatch/src/acmd/specials.rs
  fighters/gamewatch/src/acmd/throws.rs
  fighters/gamewatch/src/acmd/tilts.rs
  fighters/gamewatch/src/lib.rs
  fighters/gamewatch/src/opff.rs
  fighters/gamewatch/src/status.rs
  fighters/gamewatch/src/status/landing_attack_air.rs
  romfs/source/fighter/gamewatch/param/vl.prcxml
Labels: character change, semver:patch

#1089 King K. Rool Adjustments
  fighters/krool/src/acmd/aerials.rs
  fighters/krool/src/acmd/ground.rs
  fighters/krool/src/acmd/smashes.rs
  fighters/krool/src/acmd/specials.rs
  fighters/krool/src/acmd/throws.rs
  fighters/krool/src/acmd/tilts.rs
  fighters/krool/src/lib.rs
  fighters/krool/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#1141 Krool hotfix
  fighters/krool/src/acmd/specials.rs
Labels: bug, semver:patch

#1140 Slide-offs are now properly disable when ENABLE_FALL is off
  fighters/common/src/general_statuses/attackdash.rs
Labels: bug, semver:patch

#991 Sonic + Sora Changes
  fighters/sonic/src/acmd/aerials.rs
  fighters/sonic/src/acmd/ground.rs
  fighters/sonic/src/acmd/other.rs
  fighters/sonic/src/acmd/smashes.rs
  fighters/sonic/src/acmd/specials.rs
  fighters/sonic/src/acmd/throws.rs
  fighters/sonic/src/acmd/tilts.rs
  fighters/sonic/src/opff.rs
  fighters/sonic/src/status.rs
  fighters/trail/src/acmd/aerials.rs
  fighters/trail/src/acmd/smashes.rs
  fighters/trail/src/acmd/specials.rs
  fighters/trail/src/acmd/tilts.rs
  fighters/trail/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/sonic/param/vl.prcxml
Labels: character change, semver:patch

#1144 Small Sonic Fixes (branch merge)
  fighters/sonic/src/acmd/aerials.rs
  fighters/sonic/src/acmd/ground.rs
  fighters/sonic/src/acmd/smashes.rs
Labels: bug, semver:patch

#1145 Sonic Hot Fix
  fighters/sonic/src/acmd/aerials.rs
  fighters/sonic/src/acmd/ground.rs
  fighters/sonic/src/acmd/smashes.rs
Labels: bug, semver:patch

#1090 Pichu Changes pt. 3
  fighters/pichu/src/acmd/aerials.rs
  fighters/pichu/src/acmd/other.rs
  fighters/pichu/src/acmd/smashes.rs
  fighters/pichu/src/acmd/specials.rs
  fighters/pichu/src/acmd/throws.rs
  fighters/pichu/src/acmd/tilts.rs
  fighters/pichu/src/opff.rs
  romfs/source/fighter/pichu/param/vl.prcxml
Labels: character change, semver:patch

#1049 Captain Falcon adjustments
  fighters/captain/src/acmd/aerials.rs
  fighters/captain/src/acmd/ground.rs
  fighters/captain/src/acmd/smashes.rs
  fighters/captain/src/acmd/specials.rs
  fighters/captain/src/acmd/tilts.rs
  romfs/source/fighter/captain/param/vl.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#1142 add shoto + terry meter ui
  dynamic/src/lib.rs
  dynamic/src/ui.rs
  fighters/common/src/opff/shotos.rs
  fighters/dolly/src/opff.rs
  fighters/donkey/src/opff.rs
  utils/Cargo.toml
  utils/src/lib.rs
  utils/src/ui.rs
  utils/src/ui/ex_meter.rs
  utils/src/ui/ff_meter.rs
Labels: semver:feature

#1148 Sora Traction Fix
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: bug, semver:patch

#1143 Remove gordo double hits part 2
  fighters/dedede/src/acmd/other.rs
Labels: character change, semver:patch

#1084 Fox adjustments
  fighters/fox/src/acmd/aerials.rs
  fighters/fox/src/acmd/smashes.rs
  fighters/fox/src/acmd/specials.rs
  fighters/fox/src/acmd/throws.rs
  fighters/fox/src/acmd/tilts.rs
  fighters/fox/src/opff.rs
Labels: character change, semver:patch

#1153 King K. Rool Crownerang Hotfix
  fighters/krool/src/acmd/specials.rs
Labels: character change, semver:patch

#1154 Small Gnw adjustment
  fighters/gamewatch/src/acmd/specials.rs
Labels: character change, semver:patch

#1106 Dk Moveset Updates
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/attackdash.rs
  fighters/common/src/misc.rs
  fighters/donkey/Cargo.toml
  fighters/donkey/src/acmd/aerials.rs
  fighters/donkey/src/acmd/ground.rs
  fighters/donkey/src/acmd/smashes.rs
  fighters/donkey/src/acmd/specials.rs
  fighters/donkey/src/acmd/tilts.rs
  fighters/donkey/src/opff.rs
  fighters/donkey/src/status.rs
  fighters/donkey/src/status/catch_pull.rs
  fighters/donkey/src/status/item_throw_heavy.rs
  fighters/donkey/src/status/link_event.rs
  fighters/donkey/src/status/special_hi.rs
  fighters/donkey/src/status/special_lw.rs
  romfs/source/fighter/common/hdr/param/fighter_param.xml
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/donkey/param/vl.prcxml
Labels: enhancement, character change, semver:patch

#1156 DK Air Cargo Carry Fixes
  fighters/donkey/src/acmd/specials.rs
  fighters/donkey/src/opff.rs
  fighters/donkey/src/status/catch_pull.rs
Labels: bug, semver:patch

#1149 Sonic small fixes
  fighters/samusd/src/acmd/other.rs
  fighters/sonic/src/acmd/aerials.rs
  fighters/sonic/src/acmd/ground.rs
  fighters/sonic/src/acmd/smashes.rs
  fighters/sonic/src/acmd/specials.rs
Labels: character change, semver:patch

#1147 Aegis changes
  fighters/eflame/src/acmd/aerials.rs
  fighters/eflame/src/acmd/ground.rs
  fighters/eflame/src/acmd/smashes.rs
  fighters/eflame/src/acmd/specials.rs
  fighters/elight/src/acmd/aerials.rs
  fighters/elight/src/acmd/ground.rs
  fighters/elight/src/acmd/smashes.rs
  fighters/elight/src/acmd/specials.rs
  fighters/elight/src/acmd/throws.rs
  fighters/elight/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch
