Repository HDR-Development/HewDraw-Remix, pull requests merged in 2023-09, with the labels that each got.

#1932 Fixes an issue causing workflows to skip grabbing the correct romfs release
  .github/workflows/build_beta.yml
Labels: infrastructure, semver:patch

#1926 Shine reflect bugfixes
  fighters/fox/src/status/special_lw.rs
  fighters/wolf/src/status/special_lw.rs
Labels: bug, semver:patch

#1939 update build workflows
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: infrastructure, semver:patch

#1930 Slow pummel near-reversion
  fighters/bayonetta/src/acmd/other.rs
  fighters/common/src/function_hooks/attack.rs
  fighters/common/src/general_statuses/catch/catchattack.rs
  fighters/packun/src/acmd/other.rs
  romfs/source/fighter/common/hdr/param/common.xml
Labels: engine, semver:patch

#1941 Camera minimum zoom decrease
  fighters/common/src/function_hooks/camera.rs
Labels: engine, semver:patch

#1944 C-stick bugfixes
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/controls.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/general_statuses/jumpsquat.rs
Labels: bug, engine, semver:patch

#1942 Update semver_label_check.yml
  .github/workflows/semver_label_check.yml
Labels: infrastructure, semver:patch

#1949 Rosalina teleport bugfix
  fighters/rosetta/src/opff.rs
Labels: bug, semver:patch

#1743 Isabelle Tweaks (Pt. 2)
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/shizue/src/acmd/aerials.rs
  fighters/shizue/src/acmd/smashes.rs
  fighters/shizue/src/acmd/specials.rs
  fighters/shizue/src/acmd/throws.rs
  fighters/shizue/src/lib.rs
  fighters/shizue/src/opff.rs
  romfs/source/fighter/shizue/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1745 Duck Hunt Tweaks
  dynamic/src/consts.rs
  fighters/duckhunt/src/acmd/aerials.rs
  fighters/duckhunt/src/acmd/ground.rs
  fighters/duckhunt/src/acmd/other.rs
  fighters/duckhunt/src/acmd/specials.rs
  fighters/duckhunt/src/acmd/tilts.rs
  fighters/duckhunt/src/opff.rs
  romfs/source/fighter/duckhunt/motion/body/motion_patch.yaml
  romfs/source/fighter/duckhunt/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1812 Simon changes
  fighters/simon/src/acmd/aerials.rs
  fighters/simon/src/acmd/ground.rs
  fighters/simon/src/acmd/other.rs
  fighters/simon/src/acmd/smashes.rs
  fighters/simon/src/acmd/throws.rs
  fighters/simon/src/acmd/tilts.rs
  fighters/simon/src/opff.rs
Labels: character change, semver:patch, backroom approved

#1883 Cloud uair & dair nerfs + vfx timing
  fighters/cloud/src/acmd/aerials.rs
Labels: character change, semver:patch, backroom approved

#1935 Intangibility Corrections/Adjustments
  romfs/source/fighter/bayonetta/motion/body/motion_patch.yaml
  romfs/source/fighter/chrom/motion/body/motion_patch.yaml
  romfs/source/fighter/daisy/motion/body/motion_patch.yaml
  romfs/source/fighter/fox/motion/body/motion_patch.yaml
  romfs/source/fighter/gekkouga/motion/body/motion_patch.yaml
  romfs/source/fighter/ike/motion/body/motion_patch.yaml
  romfs/source/fighter/jack/motion/body/motion_patch.yaml
  romfs/source/fighter/littlemac/motion/body/motion_patch.yaml
  romfs/source/fighter/marth/motion/body/motion_patch.yaml
  romfs/source/fighter/miifighter/motion/body/motion_patch.yaml
  romfs/source/fighter/miiswordsman/motion/body/motion_patch.yaml
  romfs/source/fighter/peach/motion/body/motion_patch.yaml
  romfs/source/fighter/purin/motion/body/motion_patch.yaml
  romfs/source/fighter/reflet/motion/body/motion_patch.yaml
  romfs/source/fighter/roy/motion/body/motion_patch.yaml
  romfs/source/fighter/shizue/motion/body/motion_patch.yaml
  romfs/source/fighter/shulk/motion/body/motion_patch.yaml
  romfs/source/fighter/trail/motion/body/motion_patch.yaml
  romfs/source/fighter/wolf/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#1936 Corrin followup adjustments
  fighters/kamui/src/acmd/specials.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/kamui/motion/body/motion_patch.yaml
  romfs/source/fighter/kamui/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1857 Ness Kit touchups + Lucas Tweaks
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/edge_slipoffs.rs
  fighters/common/src/function_hooks/energy/motion.rs
  fighters/lucas/src/acmd/aerials.rs
  fighters/lucas/src/acmd/specials.rs
  fighters/lucas/src/acmd/throws.rs
  fighters/lucas/src/acmd/tilts.rs
  fighters/lucas/src/opff.rs
  fighters/ness/src/acmd/aerials.rs
  fighters/ness/src/acmd/ground.rs
  fighters/ness/src/acmd/other.rs
  fighters/ness/src/acmd/smashes.rs
  fighters/ness/src/acmd/specials.rs
  fighters/ness/src/acmd/throws.rs
  fighters/ness/src/acmd/tilts.rs
  fighters/ness/src/opff.rs
  fighters/ness/src/status.rs
  romfs/config.json
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/lucas/param/vl.prcxml
  romfs/source/fighter/ness/param/hdr.xml
  romfs/source/fighter/ness/param/vl.prcxml
  utils/agent_params.txt
  utils/rom_watch.txt
Labels: character change, semver:patch, backroom approved, includes assets

#1928 Banjo Adjustments
  fighters/buddy/src/acmd/aerials.rs
  fighters/buddy/src/acmd/ground.rs
  fighters/buddy/src/acmd/smashes.rs
  fighters/buddy/src/acmd/specials.rs
  fighters/buddy/src/acmd/tilts.rs
  fighters/buddy/src/opff.rs
  fighters/buddy/src/status.rs
Labels: character change, semver:patch, backroom approved

#1947 DACUS rework
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/attack/attackdash.rs
  fighters/common/src/general_statuses/attack/attackx4.rs
  romfs/source/fighter/common/hdr/param/common.xml
  romfs/source/fighter/common/hdr/param/fighter_param.xml
Labels: character change, engine, semver:patch, backroom approved

#1951 Greninja adjustments
  fighters/gekkouga/src/acmd/aerials.rs
  fighters/gekkouga/src/acmd/ground.rs
  fighters/gekkouga/src/acmd/tilts.rs
  romfs/source/fighter/gekkouga/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#1955 Minmin dtilt fix
  fighters/tantan/src/acmd/tilts.rs
Labels: bug, semver:patch

#1958 Fixes Bayonetta Crashing due to Motion Patch
  romfs/source/fighter/bayonetta/motion/body/motion_patch.yaml
Labels: bug, semver:patch

#1959 Spring bugfix
  romfs/source/fighter/rockman/param/vl.prcxml
  romfs/source/fighter/sonic/param/vl.prcxml
Labels: bug, semver:patch

#1828 Sonic Touch ups
  fighters/sonic/src/acmd/aerials.rs
  fighters/sonic/src/acmd/smashes.rs
  fighters/sonic/src/acmd/specials.rs
  fighters/sonic/src/acmd/tilts.rs
  fighters/sonic/src/opff.rs
  fighters/sonic/src/status.rs
  fighters/sonic/src/status/special_n.rs
  fighters/sonic/src/status/special_s.rs
  romfs/source/fighter/sonic/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1921 Recovery adjustments
  dynamic/src/consts.rs
  fighters/elight/src/opff.rs
  fighters/inkling/src/acmd/specials.rs
  fighters/koopajr/src/status.rs
  fighters/luigi/src/opff.rs
  fighters/mario/src/acmd/specials.rs
  fighters/mario/src/opff.rs
  fighters/pikachu/src/opff.rs
  fighters/robot/src/opff.rs
  fighters/rosetta/src/opff.rs
  fighters/roy/src/acmd/specials.rs
  fighters/sheik/src/acmd/specials.rs
  fighters/sheik/src/status/mod.rs
  fighters/sheik/src/status/special_hi.rs
  fighters/wiifit/src/acmd/specials.rs
  fighters/wiifit/src/lib.rs
  fighters/wiifit/src/status/mod.rs
  fighters/wiifit/src/status/special_s.rs
  romfs/source/fighter/common/param/common.prcxml
  romfs/source/fighter/master/param/vl.prcxml
  romfs/source/fighter/nana/param/vl.prcxml
  romfs/source/fighter/peach/param/vl.prcxml
  romfs/source/fighter/popo/param/vl.prcxml
  romfs/source/fighter/robot/param/vl.prcxml
  romfs/source/fighter/wiifit/param/vl.prcxml
  romfs/source/fighter/wolf/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1937 Misc adjustments
  dynamic/src/consts.rs
  fighters/buddy/src/opff.rs
  fighters/captain/src/acmd/aerials.rs
  fighters/dedede/src/acmd/aerials.rs
  fighters/ganon/src/acmd/aerials.rs
  fighters/ganon/src/acmd/specials.rs
  fighters/gekkouga/src/acmd/ground.rs
  fighters/inkling/src/acmd/aerials.rs
  fighters/inkling/src/acmd/other.rs
  fighters/inkling/src/opff.rs
  fighters/koopa/src/acmd/smashes.rs
  fighters/koopajr/src/acmd/aerials.rs
  fighters/koopajr/src/acmd/specials.rs
  fighters/koopajr/src/acmd/throws.rs
  fighters/littlemac/src/acmd/tilts.rs
  fighters/mario/src/acmd/specials.rs
  fighters/mariod/src/acmd/aerials.rs
  fighters/mariod/src/status/special_n.rs
  fighters/metaknight/src/acmd/aerials.rs
  fighters/metaknight/src/acmd/ground.rs
  fighters/metaknight/src/acmd/smashes.rs
  fighters/metaknight/src/acmd/specials.rs
  fighters/metaknight/src/acmd/throws.rs
  fighters/miifighter/src/acmd/specials.rs
  fighters/miiswordsman/src/acmd/other.rs
  fighters/packun/src/acmd/other.rs
  fighters/packun/src/opff.rs
  fighters/pichu/src/acmd/aerials.rs
  fighters/pikmin/src/acmd/aerials.rs
  fighters/pikmin/src/acmd/mod.rs
  fighters/pit/src/acmd/aerials.rs
  fighters/pitb/src/acmd/aerials.rs
  fighters/plizardon/src/acmd/tilts.rs
  fighters/purin/src/acmd/specials.rs
  fighters/richter/src/acmd/specials.rs
  fighters/robot/src/opff.rs
  fighters/samus/src/acmd/aerials.rs
  fighters/sheik/src/acmd/smashes.rs
  fighters/sheik/src/acmd/tilts.rs
  fighters/simon/src/acmd/aerials.rs
  fighters/simon/src/opff.rs
  fighters/tantan/src/acmd/aerials.rs
  fighters/wario/src/acmd/aerials.rs
  fighters/wario/src/acmd/ground.rs
  fighters/wario/src/acmd/smashes.rs
  fighters/wolf/src/acmd/specials.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/inkling/motion/body/motion_patch.yaml
  romfs/source/fighter/mariod/motion/body/motion_patch.yaml
  romfs/source/fighter/metaknight/motion/body/motion_patch.yaml
  romfs/source/fighter/samus/param/vl.prcxml
  romfs/source/fighter/sheik/motion/body/motion_patch.yaml
  romfs/source/fighter/shizue/param/vl.prcxml
  utils/src/ui/power_board.rs
Labels: character change, semver:patch, backroom approved

#1960 Sonic Touchups
  fighters/kirby/src/status/sonic.rs
  fighters/sonic/src/acmd/other.rs
  fighters/sonic/src/status.rs
  fighters/sonic/src/status/special_s.rs
  fighters/sonic/src/status/wait.rs
  romfs/source/fighter/sonic/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#1821 Copy Ability Adjustments + small fix
  dynamic/src/consts.rs
  fighters/captain/src/acmd/specials.rs
  fighters/common/src/function_hooks/edge_slipoffs.rs
  fighters/donkey/src/acmd/specials.rs
  fighters/inkling/src/acmd/specials.rs
  fighters/ken/src/acmd/specials.rs
  fighters/kirby/src/acmd/copyspecials.rs
  fighters/kirby/src/acmd/mod.rs
  fighters/kirby/src/acmd/smashes.rs
  fighters/kirby/src/acmd/specials.rs
  fighters/kirby/src/lib.rs
  fighters/kirby/src/opff.rs
  fighters/kirby/src/status.rs
  fighters/kirby/src/status/ganon_special_n.rs
  fighters/kirby/src/status/ganon_special_n_float.rs
  fighters/kirby/src/status/gaogaen_special_n.rs
  fighters/kirby/src/status/koopa_special_n.rs
  fighters/kirby/src/status/littlemac_special_n_cancel.rs
  fighters/kirby/src/status/lucas_special_n.rs
  fighters/kirby/src/status/mariod_special_n.rs
  fighters/kirby/src/status/ridley_special_n.rs
  fighters/lucas/src/acmd/specials.rs
  fighters/lucas/src/status.rs
  fighters/ridley/src/status.rs
  fighters/ryu/src/acmd/specials.rs
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#1972 Ganon fast fall bug fix
  fighters/ganon/src/acmd/specials.rs
Labels: bug, semver:patch

#1515 Sora Blizzaga Rework + Changes
  dynamic/src/ext.rs
  fighters/trail/src/acmd/specials.rs
  fighters/trail/src/opff.rs
  fighters/trail/src/status.rs
  fighters/trail/src/status/special_n.rs
Labels: aesthetics, character change, semver:patch, backroom approved

#1975 Steve Down Tilt Fire Effect Fix
  fighters/pickel/src/acmd/other.rs
Labels: aesthetics, semver:patch

#1969 Enable Levin Z Aerials
  fighters/robin/src/opff.rs
Labels: character change, semver:patch, backroom approved

#1961 Lucario Meter Followup Changes
  fighters/lucario/src/lib.rs
  fighters/lucario/src/opff.rs
  fighters/lucario/src/status.rs
  romfs/source/fighter/lucario/param/hdr.xml
  utils/src/modules/meter.rs
  utils/src/ui/aura_meter.rs
Labels: character change, semver:patch, backroom approved

#1967 Jiggs touchup
  fighters/purin/src/acmd/aerials.rs
  fighters/purin/src/acmd/throws.rs
Labels: character change, semver:patch, backroom approved

#1885 Gordo rework part 2 and Special Adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/edge_slipoffs.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/dedede/src/acmd/aerials.rs
  fighters/dedede/src/acmd/other.rs
  fighters/dedede/src/acmd/specials.rs
  fighters/dedede/src/acmd/tilts.rs
  fighters/dedede/src/lib.rs
  fighters/dedede/src/opff.rs
  fighters/dedede/src/status.rs
  romfs/source/fighter/dedede/motion/body/motion_patch.yaml
  romfs/source/fighter/dedede/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1761 Young link 2 hit Usmash and hitbox tweaks
  fighters/younglink/src/acmd/aerials.rs
  fighters/younglink/src/acmd/ground.rs
  fighters/younglink/src/acmd/smashes.rs
  fighters/younglink/src/acmd/throws.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/younglink/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#1946 Ganondorf Tweaks and slight Reworks
  fighters/ganon/src/acmd/specials.rs
  fighters/ganon/src/acmd/throws.rs
Labels: character change, semver:patch, backroom approved

#1924 Parry button and Rivals wall jump
  dynamic/Cargo.toml
  dynamic/src/ext.rs
  dynamic/src/modules/input.rs
  fighters/common/src/function_hooks/controls.rs
  fighters/common/src/function_hooks/transition.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/ike/src/opff.rs
  plugin/src/controls.rs
  plugin/src/lua.rs
  romfs/source/ui/message/msg_menu.xmsbt
  romfs/source/ui/script/menu/option/option_button_controller.lua
  utils/src/modules/input.rs
Labels: engine, semver:feature, includes assets

#1979 Rivals Wall Jump followup
  romfs/source/fighter/common/hdr/param/common.xml
  utils/src/modules/input.rs
Labels: bug, engine, semver:patch

#1965 Use heavy landing animations for jumpsquat
  fighters/common/src/function_hooks/change_motion.rs
  fighters/common/src/function_hooks/controls.rs
  fighters/common/src/function_hooks/effect.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/function_hooks/sound.rs
  fighters/common/src/general_statuses/jumpsquat.rs
  fighters/dedede/src/acmd/other.rs
  fighters/donkey/src/acmd/other.rs
  fighters/koopa/src/acmd/other.rs
  fighters/krool/src/acmd/other.rs
  fighters/plizardon/src/acmd/other.rs
  fighters/ridley/src/acmd/other.rs
Labels: aesthetics, engine, semver:patch

#1984 Sora - Blizzaga follow-up adjustments
  fighters/trail/src/acmd/specials.rs
  fighters/trail/src/opff.rs
  romfs/source/fighter/trail/motion/flower/motion_patch.yaml
Labels: bug, aesthetics, semver:patch

#1982 Peanut Popgun Charge Cancel + Kirby Offense Up Bugfix
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/diddy/src/opff.rs
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
Labels: bug, semver:patch

#1981 Krool Gut Check bugfix
  fighters/krool/src/acmd/specials.rs
  fighters/krool/src/opff.rs
  fighters/shizue/src/opff.rs
  romfs/source/fighter/krool/motion/body/motion_patch.yaml
Labels: bug, semver:patch, includes assets

#1948 WuBor Mega Man
  dynamic/src/consts.rs
  fighters/rockman/Cargo.toml
  fighters/rockman/src/acmd/aerials.rs
  fighters/rockman/src/acmd/ground.rs
  fighters/rockman/src/acmd/other.rs
  fighters/rockman/src/acmd/smashes.rs
  fighters/rockman/src/acmd/specials.rs
  fighters/rockman/src/acmd/tilts.rs
  fighters/rockman/src/lib.rs
  fighters/rockman/src/opff.rs
  fighters/rockman/src/status.rs
  fighters/rockman/src/status/attack.rs
  fighters/rockman/src/status/attack_air.rs
  fighters/rockman/src/status/attack_s3.rs
  fighters/rockman/src/status/attack_s4.rs
  fighters/rockman/src/status/chargeshot.rs
  fighters/rockman/src/status/helper.rs
  fighters/rockman/src/status/ladder_attack.rs
  fighters/rockman/src/status/rockbuster.rs
  fighters/rockman/src/status/rockbuster/helper.rs
  fighters/rockman/src/status/rockbuster/shoot_air.rs
  fighters/rockman/src/status/rockbuster/shoot_jump.rs
  fighters/rockman/src/status/rockbuster/shoot_jump_squat.rs
  fighters/rockman/src/status/rockbuster/shoot_landing.rs
  fighters/rockman/src/status/rockbuster/shoot_turn.rs
  fighters/rockman/src/status/rockbuster/shoot_wait.rs
  fighters/rockman/src/status/rockbuster/shoot_walk.rs
  fighters/rockman/src/status/special_lw.rs
  fighters/rockman/src/status/special_n.rs
  fighters/rockman/src/status/special_s.rs
  fighters/rockman/src/status/walk.rs
  fighters/rockman/src/vl.rs
  fighters/rockman/src/vtable_hook.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/rockman/motion/body/motion_patch.yaml
  romfs/source/fighter/rockman/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1915 Robin throw changes
  fighters/robin/src/acmd/other.rs
  fighters/robin/src/acmd/throws.rs
  romfs/source/fighter/reflet/param/vl.prcxml
Labels: character change, semver:patch, backroom approved
