Repository HDR-Development/HewDraw-Remix, pull requests merged in 2023-05, with the labels that each got.

#1582 Sonic - upB bugfixes
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/change_motion.rs
  fighters/common/src/function_hooks/ledges.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/sonic/src/opff.rs
Labels: bug, semver:patch

#1546 Camera parameter standardization + camera adjustments
  fighters/common/src/function_hooks/camera.rs
Labels: engine, semver:patch, includes assets

#1573 Little Mac - Aerial Straight Lunge cancel animation
  fighters/littlemac/src/acmd/specials.rs
  fighters/littlemac/src/status/special_n_cancel.rs
Labels: aesthetics, semver:patch, includes assets

#1584 Palutena Teleport Hotfix
  fighters/palutena/src/opff.rs
Labels: bug, semver:patch

#1613 Terry - fix Burn Knuckle distance
  fighters/common/src/function_hooks/mod.rs
Labels: bug, semver:patch

#1614 Marth - fix tipper hitsounds
  fighters/marth/src/acmd/ground.rs
  fighters/marth/src/acmd/smashes.rs
  fighters/marth/src/acmd/tilts.rs
Labels: aesthetics, semver:patch

#1574 Command grab jump refresh
  fighters/common/src/opff/physics.rs
Labels: engine, semver:patch

#1592 Waveland snap improvements
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/collision.rs
  fighters/common/src/general_statuses/airdodge.rs
Labels: engine, semver:patch

#1616 Reset tech lockout timer on hit
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/damage.rs
Labels: engine, semver:patch

#1561 Fixes a crash when switching to Ivysaur
  dynamic/src/util.rs
Labels: crash, semver:patch

#1589 Rising platwarp removal logic rework
  fighters/common/src/function_hooks/collision.rs
  fighters/common/src/opff/physics.rs
Labels: bug, engine, semver:patch

#1624 Enable zair edge cancels
  fighters/common/src/function_hooks/edge_slipoffs.rs
Labels: engine, semver:patch

#1634 Daisy - remove multihits on Parasol
  fighters/daisy/src/acmd/specials.rs
Labels: character change, semver:patch

#1606 Kirby - grounded upB bugfix
  fighters/kirby/src/opff.rs
Labels: bug, semver:patch

#1639 Recovery sweep hotfixes part 2
  dynamic/src/consts.rs
  fighters/duckhunt/src/opff.rs
  fighters/krool/src/acmd/other.rs
  fighters/krool/src/lib.rs
  fighters/krool/src/opff.rs
  fighters/mario/src/acmd/specials.rs
  fighters/pit/src/acmd/specials.rs
  fighters/pit/src/opff.rs
  fighters/pitb/src/acmd/specials.rs
  romfs/config.json
  romfs/source/fighter/duckhunt/param/hdr.xml
  romfs/source/fighter/duckhunt/param/vl.prcxml
  romfs/source/fighter/krool/param/hdr.xml
  romfs/source/fighter/shizue/param/vl.prcxml
  utils/agent_params.txt
  utils/rom_watch.txt
Labels: bug, semver:patch

#1535 Move parry from shield release to dedicated input
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  dynamic/src/modules/input.rs
  fighters/common/src/function_hooks/controls.rs
  fighters/common/src/general_statuses/shield/fighter_status_guard/mod.rs
  fighters/common/src/general_statuses/shield/guard/end.rs
  fighters/common/src/general_statuses/shield/guard/exec.rs
  fighters/common/src/general_statuses/shield/guard/exit.rs
  fighters/common/src/general_statuses/shield/guard/init.rs
  fighters/common/src/general_statuses/shield/guard/main.rs
  fighters/common/src/general_statuses/shield/guard/pre.rs
  fighters/common/src/general_statuses/shield/guard_damage/end.rs
  fighters/common/src/general_statuses/shield/guard_damage/exec.rs
  fighters/common/src/general_statuses/shield/guard_damage/exit.rs
  fighters/common/src/general_statuses/shield/guard_damage/init.rs
  fighters/common/src/general_statuses/shield/guard_damage/main.rs
  fighters/common/src/general_statuses/shield/guard_damage/mod.rs
  fighters/common/src/general_statuses/shield/guard_damage/pre.rs
  fighters/common/src/general_statuses/shield/guard_off/end.rs
  fighters/common/src/general_statuses/shield/guard_off/exec.rs
  fighters/common/src/general_statuses/shield/guard_off/exit.rs
  fighters/common/src/general_statuses/shield/guard_off/init.rs
  fighters/common/src/general_statuses/shield/guard_off/main.rs
  fighters/common/src/general_statuses/shield/guard_off/pre.rs
  fighters/common/src/general_statuses/shield/guard_on/end.rs
  fighters/common/src/general_statuses/shield/guard_on/exec.rs
  fighters/common/src/general_statuses/shield/guard_on/exit.rs
  fighters/common/src/general_statuses/shield/guard_on/init.rs
  fighters/common/src/general_statuses/shield/guard_on/main.rs
  fighters/common/src/general_statuses/shield/guard_on/pre.rs
  fighters/common/src/general_statuses/shield/misc.rs
  fighters/common/src/general_statuses/shield/mod.rs
  fighters/common/src/misc.rs
  fighters/dolly/src/status.rs
  fighters/donkey/src/status.rs
  fighters/inkling/src/lib.rs
  fighters/inkling/src/opff.rs
  fighters/inkling/src/status.rs
  fighters/ken/src/status.rs
  fighters/pickel/src/status.rs
  fighters/ryu/src/status.rs
  fighters/yoshi/src/status.rs
  plugin/src/lua.rs
  plugin/src/online.rs
  romfs/source/fighter/common/param/common.prcxml
  utils/src/modules/input.rs
Labels: engine, semver:feature, includes assets

#1379 Piranha Plant Rework (Redux): Adaptive Roots
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/packun/src/acmd/aerials.rs
  fighters/packun/src/acmd/ground.rs
  fighters/packun/src/acmd/mod.rs
  fighters/packun/src/acmd/other.rs
  fighters/packun/src/acmd/smashes.rs
  fighters/packun/src/acmd/specials.rs
  fighters/packun/src/acmd/throws.rs
  fighters/packun/src/acmd/tilts.rs
  fighters/packun/src/lib.rs
  fighters/packun/src/opff.rs
  fighters/packun/src/status/special_hi.rs
Labels: character change, semver:patch, backroom approved

#1501 Ganondorf adjustments
  fighters/ganon/src/acmd/aerials.rs
  fighters/ganon/src/acmd/ground.rs
  fighters/ganon/src/acmd/smashes.rs
  fighters/ganon/src/acmd/specials.rs
  fighters/ganon/src/acmd/tilts.rs
Labels: character change, semver:patch, backroom approved, includes assets

#1541 Brawler Specials Rework
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/edge_slipoffs.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/miifighter/src/acmd/specials.rs
  fighters/miifighter/src/lib.rs
  fighters/miifighter/src/opff.rs
  fighters/miifighter/src/status.rs
  romfs/source/fighter/miifighter/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1570 Hero menu overhaul
  dynamic/src/consts.rs
  fighters/brave/Cargo.toml
  fighters/brave/src/acmd/aerials.rs
  fighters/brave/src/acmd/ground.rs
  fighters/brave/src/acmd/mod.rs
  fighters/brave/src/acmd/other.rs
  fighters/brave/src/acmd/smashes.rs
  fighters/brave/src/acmd/specials.rs
  fighters/brave/src/acmd/throws.rs
  fighters/brave/src/acmd/tilts.rs
  fighters/brave/src/lib.rs
  fighters/brave/src/opff.rs
  fighters/brave/src/status.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/common/src/misc.rs
  romfs/source/fighter/brave/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1551 Mario Throw Changes
  fighters/mario/src/acmd/throws.rs
Labels: character change, semver:patch, backroom approved

#1503 Minmin overhaul
  dynamic/src/consts.rs
  fighters/tantan/src/acmd/aerials.rs
  fighters/tantan/src/acmd/ground.rs
  fighters/tantan/src/acmd/other.rs
  fighters/tantan/src/acmd/smashes.rs
  fighters/tantan/src/acmd/specials.rs
  fighters/tantan/src/acmd/tilts.rs
  fighters/tantan/src/opff.rs
  fighters/tantan/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/tantan/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets
