Repository HDR-Development/HewDraw-Remix, pull requests merged in 2023-10, with the labels that each got.

#1989 Revert WuBor Mega Man
  dynamic/src/consts.rs
  fighters/rockman/Cargo.toml
  fighters/rockman/src/acmd/aerials.rs
  fighters/rockman/src/acmd/ground.rs
  fighters/rockman/src/acmd/other.rs
  fighters/rockman/src/acmd/smashes.rs
  fighters/rockman/src/acmd/specials.rs
  fighters/rockman/src/acmd/tilts.rs
  fighters/rockman/src/lib.rs
  fighters/rockman/src/opff.rs
  fighters/rockman/src/status.rs
  fighters/rockman/src/status/attack.rs
  fighters/rockman/src/status/attack_air.rs
  fighters/rockman/src/status/attack_s3.rs
  fighters/rockman/src/status/attack_s4.rs
  fighters/rockman/src/status/chargeshot.rs
  fighters/rockman/src/status/helper.rs
  fighters/rockman/src/status/ladder_attack.rs
  fighters/rockman/src/status/rockbuster.rs
  fighters/rockman/src/status/rockbuster/helper.rs
  fighters/rockman/src/status/rockbuster/shoot_air.rs
  fighters/rockman/src/status/rockbuster/shoot_jump.rs
  fighters/rockman/src/status/rockbuster/shoot_jump_squat.rs
  fighters/rockman/src/status/rockbuster/shoot_landing.rs
  fighters/rockman/src/status/rockbuster/shoot_turn.rs
  fighters/rockman/src/status/rockbuster/shoot_wait.rs
  fighters/rockman/src/status/rockbuster/shoot_walk.rs
  fighters/rockman/src/status/special_lw.rs
  fighters/rockman/src/status/special_n.rs
  fighters/rockman/src/status/special_s.rs
  fighters/rockman/src/status/walk.rs
  fighters/rockman/src/vl.rs
  fighters/rockman/src/vtable_hook.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/rockman/motion/body/motion_patch.yaml
  romfs/source/fighter/rockman/param/vl.prcxml
Labels: semver:patch

#1991 Fox & Falco Shine Effect Cleanup
  fighters/falco/src/acmd/specials.rs
  fighters/fox/src/acmd/specials.rs
Labels: aesthetics, semver:patch

#1993 Support TNN's stage config and blujay's stage alts
  romfs/source/ui/script_patch/common/stage_select_actor3.lua
  romfs/source/ui/script_patch/common/stage_select_actor3.tourney.lua
  scripts/full_package.py
Labels: semver:feature

#1994 disable lvd_extract
  .github/workflows/build_nightly.yml
Labels: semver:patch

#1995 Disable all LVD processing
  .github/workflows/build_nightly.yml
Labels: semver:patch

#1988 DK adjustments
  fighters/common/src/misc.rs
  fighters/donkey/src/acmd/aerials.rs
  fighters/donkey/src/acmd/specials.rs
  fighters/donkey/src/acmd/throws.rs
  fighters/donkey/src/status/special_lw.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/donkey/motion/body/motion_patch.yaml
  romfs/source/item/common/param/param.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1996 GHZ Hook Fix
  fighters/common/src/function_hooks/stage_hazards.rs
Labels: bug, semver:patch, stages

#1987 Kirby - Sora Specials & Wavedash Effect fix
  fighters/kirby/src/acmd/other.rs
  fighters/kirby/src/opff.rs
  fighters/trail/src/acmd/specials.rs
Labels: bug, semver:patch

#1940 Captain Falcon Up Special Adjustments
  fighters/captain/src/acmd/specials.rs
  fighters/captain/src/acmd/throws.rs
  romfs/source/fighter/captain/param/hdr.xml
Labels: character change, semver:patch, backroom approved

#2005 Fix grounded knockback freezing bug
  fighters/common/src/general_statuses/mod.rs
Labels: bug, engine, semver:patch

#1997 Add plat drop lockout to initial dash for FGC characters
  fighters/common/src/general_statuses/dash.rs
  fighters/common/src/shoto_status.rs
  romfs/source/fighter/demon/param/hdr.xml
  romfs/source/fighter/dolly/param/hdr.xml
  romfs/source/fighter/ken/param/hdr.xml
  romfs/source/fighter/ryu/param/hdr.xml
Labels: character change, engine, semver:patch, backroom approved

#1986 Sora - Reorder Magic Cycle
  dynamic/src/consts.rs
  fighters/kirby/src/opff.rs
  fighters/kirby/src/status.rs
  fighters/trail/src/acmd/specials.rs
  fighters/trail/src/lib.rs
  fighters/trail/src/opff.rs
  fighters/trail/src/status/special_n.rs
Labels: character change, semver:patch, backroom approved, includes assets

#2009 Fix Ryu and Ken crashing upon trying to grab plat drop params
  romfs/config.json
  utils/agent_params.txt
  utils/rom_watch.txt
Labels: bug, semver:patch

#1985 Mii Swordfighter specials adjustments
  dynamic/src/consts.rs
  fighters/miiswordsman/src/acmd/other.rs
  fighters/miiswordsman/src/acmd/specials.rs
  fighters/miiswordsman/src/lib.rs
  fighters/miiswordsman/src/opff.rs
  romfs/source/fighter/miiswordsman/motion/body/motion_patch.yaml
  romfs/source/fighter/miiswordsman/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#2008 Olimar Quick Fixes
  fighters/pikmin/src/acmd/specials.rs
  romfs/source/fighter/pikmin/motion/body/motion_patch.yaml
Labels: bug, character change, semver:patch, backroom approved

#2000 Kazuya rework
  fighters/demon/src/acmd/aerials.rs
  fighters/demon/src/acmd/ground.rs
  fighters/demon/src/acmd/jabs.rs
  fighters/demon/src/acmd/smashes.rs
  fighters/demon/src/acmd/specials.rs
  fighters/demon/src/acmd/throws.rs
  fighters/demon/src/acmd/tilts.rs
  fighters/demon/src/opff.rs
  fighters/demon/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#2012 i'm going to kill myself
  README.md
Labels: semver:feature

#2014 Fixes the emulator check for Ryujinx
  plugin/src/lib.rs
Labels: bug, semver:patch

#2020 Fixes UI Crashing in Mii Maker
  utils/src/ui.rs
Labels: bug, semver:patch

#2021 Fixes Inkling being able to cancel Splattershot in the air
  fighters/inkling/src/opff.rs
Labels: bug, semver:patch

#2029 Fix Additional Stage Alts
  fighters/common/src/function_hooks/stage_hazards.rs
  romfs/source/ui/script_patch/common/stage_select_actor3.lua
  romfs/source/ui/script_patch/common/stage_select_actor3.tourney.lua
Labels: bug, semver:patch

#2030 MiiSF Apply X Speed Mul to Grounded USpecial3
  fighters/miiswordsman/src/acmd/specials.rs
Labels: bug, character change, semver:patch, backroom approved

#2034 redistribution disclaimer
  README.md
Labels: semver:patch

#2035 Update stage_select_actor3.lua
  romfs/source/ui/script_patch/common/stage_select_actor3.lua
Labels: bug, semver:patch

#2031 Tiny adjustments
  fighters/gamewatch/src/acmd/specials.rs
  fighters/miigunner/src/acmd/other.rs
Labels: bug, character change, semver:patch, backroom approved

#2026 ECB Bugfix for certain projectiles and Jigglypuff
  fighters/buddy/src/acmd/other.rs
  fighters/dedede/src/acmd/other.rs
  fighters/ken/src/acmd/other.rs
  fighters/purin/src/acmd/specials.rs
  fighters/robin/src/acmd/other.rs
  romfs/source/fighter/ken/param/vl.prcxml
Labels: bug, semver:patch

#2039 Changes Robin's name to Reflet in source code
  dynamic/src/consts.rs
  fighters/Cargo.toml
  fighters/reflet/Cargo.toml
  fighters/reflet/src/acmd/aerials.rs
  fighters/reflet/src/acmd/ground.rs
  fighters/reflet/src/acmd/mod.rs
  fighters/reflet/src/acmd/other.rs
  fighters/reflet/src/acmd/smashes.rs
  fighters/reflet/src/acmd/specials.rs
  fighters/reflet/src/acmd/throws.rs
  fighters/reflet/src/acmd/tilts.rs
  fighters/reflet/src/lib.rs
  fighters/reflet/src/opff.rs
  fighters/reflet/src/status.rs
  fighters/src/lib.rs
  plugin/Cargo.toml
  scripts/characters.py
Labels: semver:patch

#2001 Robot 2.0
  dynamic/src/consts.rs
  fighters/robot/src/acmd/aerials.rs
  fighters/robot/src/acmd/specials.rs
  fighters/robot/src/lib.rs
  fighters/robot/src/opff.rs
  fighters/robot/src/status.rs
  romfs/source/fighter/robot/motion/body/motion_patch.yaml
  romfs/source/fighter/robot/param/vl.prcxml
Labels: semver:patch, includes assets

#2013 WuBor Mega Man (He's Back)
  dynamic/src/consts.rs
  fighters/rockman/Cargo.toml
  fighters/rockman/src/acmd/aerials.rs
  fighters/rockman/src/acmd/ground.rs
  fighters/rockman/src/acmd/other.rs
  fighters/rockman/src/acmd/smashes.rs
  fighters/rockman/src/acmd/specials.rs
  fighters/rockman/src/acmd/tilts.rs
  fighters/rockman/src/lib.rs
  fighters/rockman/src/opff.rs
  fighters/rockman/src/status.rs
  fighters/rockman/src/status/attack.rs
  fighters/rockman/src/status/attack_air.rs
  fighters/rockman/src/status/attack_s3.rs
  fighters/rockman/src/status/attack_s4.rs
  fighters/rockman/src/status/chargeshot.rs
  fighters/rockman/src/status/helper.rs
  fighters/rockman/src/status/ladder_attack.rs
  fighters/rockman/src/status/rockbuster.rs
  fighters/rockman/src/status/rockbuster/helper.rs
  fighters/rockman/src/status/rockbuster/shoot_air.rs
  fighters/rockman/src/status/rockbuster/shoot_jump.rs
  fighters/rockman/src/status/rockbuster/shoot_jump_squat.rs
  fighters/rockman/src/status/rockbuster/shoot_landing.rs
  fighters/rockman/src/status/rockbuster/shoot_turn.rs
  fighters/rockman/src/status/rockbuster/shoot_wait.rs
  fighters/rockman/src/status/rockbuster/shoot_walk.rs
  fighters/rockman/src/status/special_lw.rs
  fighters/rockman/src/status/special_n.rs
  fighters/rockman/src/status/special_s.rs
  fighters/rockman/src/status/walk.rs
  fighters/rockman/src/vl.rs
  fighters/rockman/src/vtable_hook.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/rockman/motion/body/motion_patch.yaml
  romfs/source/fighter/rockman/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2045 ROB Bugfix
  fighters/robot/src/acmd/specials.rs
  fighters/robot/src/opff.rs
  fighters/robot/src/status.rs
Labels: bug, semver:patch

#2046 restructure into workspace
  Cargo.toml
  build.rs
  crates/build-tools/Cargo.toml
  crates/build-tools/src/lib.rs
  crates/build-tools/src/main.rs
  fighters/src/lib.rs
  hdr-macros/Cargo.toml
  hdr-macros/src/lib.rs
  hdr_version.txt
  plugin/Cargo.toml
  plugin/build.rs
  plugin/link.ld
  plugin/rust-toolchain
  plugin/src/updater.rs
  romfs/agent_params.txt
  romfs/rom_watch.txt
  scripts/build.py
  scripts/pkgutil.py
  src/controls.rs
  src/fighters.rs
  src/lib.rs
  src/lua.rs
  src/online.rs
  src/random.rs
  utils/Cargo.toml
  utils/src/modules/param.rs
Labels: semver:patch

#2047 update source loc for hdr_version.txt
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch
