Repository HDR-Development/HewDraw-Remix, pull requests merged in 2023-07, with the labels that each got.

#1711 Allow fastfall during airdodge
  fighters/common/src/general_statuses/airdodge.rs
Labels: engine, semver:patch

#1729 Daisy - fix float out of double jump
  fighters/common/src/function_hooks/change_status.rs
  fighters/daisy/src/opff.rs
Labels: bug, semver:patch

#1723 Increase parry hitlag multiplier
  fighters/common/src/general_statuses/shield/guard_damage/init.rs
Labels: engine, semver:patch

#1627 Young Link Balance Adjustments
  fighters/miiswordsman/src/status.rs
  fighters/toonlink/src/status.rs
  fighters/younglink/src/acmd/aerials.rs
  fighters/younglink/src/acmd/ground.rs
  fighters/younglink/src/acmd/smashes.rs
  fighters/younglink/src/acmd/specials.rs
  fighters/younglink/src/acmd/throws.rs
  fighters/younglink/src/acmd/tilts.rs
  fighters/younglink/src/status.rs
Labels: character change, semver:patch, backroom approved, includes assets

#1702 Prevent jostle edge slipoffs
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/function_hooks/mod.rs
Labels: engine, semver:patch

#1707 Fix DJC character jump aerial momentum
  fighters/common/src/djc.rs
  fighters/peach/src/status/attack_air.rs
  fighters/trail/src/status/attack_air.rs
Labels: bug, engine, semver:patch

#1716 DPit NAir Hotfix
  fighters/pitb/src/acmd/aerials.rs
Labels: character change, semver:patch, backroom approved

#1726 Sonic Adjustments
  fighters/sonic/src/acmd/aerials.rs
  fighters/sonic/src/acmd/ground.rs
  fighters/sonic/src/acmd/smashes.rs
  fighters/sonic/src/acmd/specials.rs
  fighters/sonic/src/acmd/tilts.rs
  romfs/source/fighter/sonic/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1730 Mii Brawler followup followup
  fighters/miifighter/src/acmd/specials.rs
  fighters/miifighter/src/opff.rs
  romfs/source/fighter/miifighter/param/hdr.xml
Labels: character change, semver:patch, backroom approved, includes assets

#1696 Mewtwo Adjustment + Resource Restrictions
  fighters/common/src/function_hooks/get_param.rs
  fighters/common/src/opff/floats.rs
  fighters/mewtwo/src/acmd/aerials.rs
  fighters/mewtwo/src/acmd/ground.rs
  fighters/mewtwo/src/acmd/smashes.rs
  fighters/mewtwo/src/opff.rs
Labels: character change, semver:patch, backroom approved, includes assets

#1733 Byleth hotfixes
  fighters/master/src/acmd/aerials.rs
  fighters/master/src/acmd/ground.rs
  fighters/master/src/acmd/specials.rs
Labels: character change, semver:patch, backroom approved

#1690 Ken Followup Adjustments
  fighters/ken/src/acmd/finals.rs
  fighters/ken/src/acmd/ground.rs
  fighters/ken/src/acmd/throws.rs
  fighters/ken/src/acmd/tilts.rs
  fighters/ken/src/opff.rs
  fighters/ken/src/status.rs
Labels: character change, semver:patch, backroom approved

#1717 Marth animation adjustments
  fighters/marth/src/acmd/aerials.rs
  fighters/marth/src/acmd/smashes.rs
Labels: aesthetics, semver:patch

#1715 Dk minor adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/donkey/src/acmd/throws.rs
Labels: character change, semver:patch, backroom approved

#1665 Standardize Getup Attacks Reverse Hit
  fighters/common/src/function_hooks/attack.rs
Labels: engine, semver:patch

#1718 Re-add support for hid-hdr
  fighters/common/src/opff/tech.rs
  plugin/Cargo.toml
  plugin/src/lib.rs
  romfs/source/fighter/common/hdr/param/common.xml
  romfs/source/fighter/common/param/common.prcxml
  scripts/full_package.py
Labels: semver:feature

#1700 Fix amsah tech momentum + double traction refactor
  fighters/common/src/function_hooks/energy/control.rs
  fighters/common/src/function_hooks/energy/motion.rs
  fighters/common/src/function_hooks/energy/stop.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/general_statuses/down.rs
  fighters/common/src/general_statuses/downstand.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/common/src/general_statuses/passive.rs
  fighters/common/src/opff/physics.rs
  romfs/source/fighter/common/param/common.prcxml
Labels: bug, engine, semver:patch

#1738 Pichu meter color adjustment
  dynamic/src/ui.rs
  fighters/pichu/src/opff.rs
  utils/src/ui.rs
  utils/src/ui/pichu_meter.rs
Labels: aesthetics, semver:patch

#1747 Only apply double traction on common statuses
  fighters/common/src/function_hooks/energy/motion.rs
  fighters/common/src/function_hooks/energy/stop.rs
  fighters/common/src/function_hooks/mod.rs
Labels: engine, semver:patch

#1748 DK Barrel hotfix
  fighters/common/src/misc.rs
Labels: bug, semver:patch

#1739 UpB bugfixes
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/opff/edge_slipoffs.rs
Labels: bug, engine, semver:patch

#1737 Link Boomerang and Arrow Tweaks
  fighters/link/src/acmd/other.rs
  romfs/source/fighter/link/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1741 Snake followup adjustments
  dynamic/src/consts.rs
  fighters/snake/src/acmd/other.rs
  fighters/snake/src/acmd/specials.rs
  fighters/snake/src/opff.rs
Labels: character change, semver:patch, backroom approved

#1746 Parry input adjustment
  dynamic/src/ext.rs
  dynamic/src/util.rs
  fighters/bayonetta/src/status/attack.rs
  fighters/bayonetta/src/status/batwithin.rs
  fighters/bayonetta/src/status/escape.rs
  fighters/bayonetta/src/status/mod.rs
  fighters/common/src/function_hooks/controls.rs
  fighters/common/src/general_statuses/shield/misc.rs
  fighters/common/src/opff/other.rs
  fighters/snake/src/status.rs
  fighters/snake/src/status/appeal.rs
  fighters/snake/src/status/attack_s4.rs
  fighters/snake/src/status/catch.rs
  fighters/snake/src/status/mod.rs
  fighters/snake/src/status/special_s.rs
Labels: bug, engine, semver:patch

#1680 MinMin fix duplicating double jump effect during arms attack
  fighters/tantan/src/acmd/other.rs
  fighters/tantan/src/status.rs
Labels: bug, semver:patch

#1749 Joker DAIR and UPAIR Hotfix
  fighters/jack/src/acmd/aerials.rs
Labels: bug, semver:patch

#1752 Taunt parry hotfix
  dynamic/src/ext.rs
  fighters/common/src/general_statuses/shield/misc.rs
  fighters/common/src/opff/other.rs
Labels: bug, engine, semver:patch

#1753 Fix rising aerial platwarps (again)
  fighters/common/src/function_hooks/collision.rs
Labels: engine, semver:patch

#1755 Parry Sound Bugfix
  fighters/common/src/opff/other.rs
Labels: aesthetics, semver:patch

#1727 Lucas Up-Air FAF Fix
  fighters/lucas/src/acmd/aerials.rs
Labels: semver:patch

#1757 Swordfighter small adjustment
  fighters/miiswordsman/src/acmd/other.rs
Labels: character change, semver:patch, backroom approved

#1758 Fix grounded damage edge slipoffs
  fighters/common/src/function_hooks/edge_slipoffs.rs
Labels: bug, engine, semver:patch

#1759 Jostle overlap mul reset is_fighter check
  fighters/common/src/function_hooks/mod.rs
Labels: semver:patch

#1751 Fix sonic spring snap
  fighters/sonic/src/opff.rs
  fighters/sonic/src/status.rs
  fighters/sonic/src/status/special_hi.rs
Labels: bug, semver:patch

#1765 Robin Levin Buffer/Switch
  fighters/robin/src/opff.rs
Labels: bug, semver:patch

#1768 Revert airdodge fastfall
  fighters/common/src/general_statuses/airdodge.rs
Labels: engine, semver:patch

#1673 Bayonetta Hotfix: Jump, Effects, Misc.
  dynamic/src/consts.rs
  fighters/bayonetta/src/acmd/ground.rs
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/acmd/tilts.rs
  fighters/bayonetta/src/opff.rs
  fighters/bayonetta/src/status/attack.rs
  fighters/common/src/function_hooks/change_status.rs
  romfs/source/fighter/bayonetta/param/vl.prcxml
Labels: bug, semver:patch

#1740 Float Hotfix (pt 2)
  fighters/common/src/opff/floats.rs
Labels: bug, enhancement, semver:patch

#1766 Controls screen crash fix
  plugin/src/lua.rs
Labels: bug, crash, semver:patch

#1780 Double traction hotfix
  fighters/common/src/function_hooks/energy/motion.rs
  fighters/common/src/function_hooks/energy/stop.rs
Labels: bug, engine, semver:patch

#1775 fix stage hazards online
  fighters/common/src/function_hooks/stage_hazards.rs
Labels: semver:patch

#1779 Meta Knight - revert max DACUS distance
  fighters/metaknight/src/acmd/ground.rs
Labels: character change, semver:patch

#1771 Fix Pichu and Piranha Plant copy abilities
  fighters/packun/src/acmd/other.rs
  fighters/pichu/src/acmd/specials.rs
Labels: bug, semver:patch

#1783 remove at least 1f of input delay globally
  plugin/src/controls.rs
Labels: engine, semver:feature

#1786 Double traction hotfix again (fix wavedash lengths)
  fighters/common/src/function_hooks/energy/motion.rs
  fighters/common/src/function_hooks/energy/stop.rs
Labels: bug, engine, semver:patch

#1789 remove arena ferox screen shake
  fighters/common/src/function_hooks/stage_hazards.rs
Labels: semver:patch

#1793 UpB bounce bugfixes
  fighters/falco/src/status/special_hi.rs
  fighters/fox/src/status/special_hi.rs
  fighters/lucario/src/status.rs
  fighters/wolf/src/status/special_hi.rs
  romfs/source/fighter/falco/param/vl.prcxml
  romfs/source/fighter/wolf/param/vl.prcxml
Labels: bug, semver:patch

#1794 Falcon Kick/Wizard's Foot/Power Thrust fixes
  fighters/captain/src/status/special_lw.rs
  fighters/ganon/src/status/special_lw.rs
  fighters/miiswordsman/src/acmd/specials.rs
Labels: bug, semver:patch

#1785 Add print debug
  dynamic/src/consts.rs
  fighters/common/src/opff/other.rs
Labels: enhancement, engine, semver:patch

#1801 Shield release FAF bugfix
  fighters/common/src/general_statuses/shield/guard_off/main.rs
  romfs/source/fighter/common/hdr/param/common.xml
Labels: bug, engine, semver:patch

#1802 Fix arena lobby hang
  plugin/src/lib.rs
Labels: bug, semver:patch

#1803 Fix debug VarModule overlap
  dynamic/src/consts.rs
Labels: bug, semver:patch

#1722 Clank lag + electric hitlag changes
  fighters/common/src/function_hooks/mod.rs
Labels: engine, semver:patch

#1776 Changes when ROMFS files are built
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
  .github/workflows/pr_build.yml
  fighters/Cargo.toml
  fighters/build.rs
  fighters/rom_watch.txt
  plugin/Cargo.toml
  plugin/build.rs
  utils/Cargo.toml
Labels: bug, semver:patch

#1815 fix nightly issues (hopefully)
  fighters/common/src/function_hooks/stage_hazards.rs
Labels: semver:patch

#1816 Revert unintended additions to .gitignore
  .gitignore
Labels: infrastructure

#1818 Stage code changes
  fighters/common/src/function_hooks/stage_hazards.rs
Labels: semver:patch, stages

#1760 Weaken getup/ledge attacks
  fighters/common/src/function_hooks/attack.rs
Labels: engine, semver:patch

#1800 Update Wavedrop Thresholds Again
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/opff/tech.rs
  fighters/mario/src/opff.rs
  romfs/source/fighter/common/hdr/param/common.xml
Labels: engine, semver:patch

#1817 Luigi Training mode misfire toggle
  dynamic/src/consts.rs
  fighters/luigi/src/opff.rs
Labels: character change, semver:patch

#1823 Luigi training mode misfire Variable edit
  dynamic/src/consts.rs
Labels: semver:patch

#1824 Update full_package.py
  scripts/full_package.py
Labels: semver:patch

#1782 Cast-wide jump speed adjustments
  fighters/common/src/function_hooks/energy/control.rs
  fighters/ike/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#1772 Reduce electric multihit effectiveness
  fighters/lucas/src/acmd/specials.rs
  fighters/pikachu/src/acmd/aerials.rs
  fighters/robin/src/acmd/other.rs
  fighters/rockman/src/acmd/smashes.rs
  fighters/samusd/src/acmd/aerials.rs
  fighters/szerosuit/src/acmd/specials.rs
Labels: character change, semver:patch, backroom approved

#1819 Automate positional transition for edited dash animations
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/dash.rs
  fighters/common/src/general_statuses/run.rs
  fighters/common/src/opff/other.rs
Labels: aesthetics, semver:patch

#1804 Make smoke GFX a bit less opaque
  fighters/common/src/function_hooks/effect.rs
Labels: aesthetics, semver:patch

#1773 Final Smash bugfixes
  fighters/common/src/function_hooks/mod.rs
Labels: bug, engine, semver:patch

#1827 Wolf animation adjustments
  fighters/wolf/src/acmd/aerials.rs
  fighters/wolf/src/acmd/smashes.rs
  romfs/source/fighter/wolf/motion/body/motion_patch.yaml
Labels: aesthetics, semver:patch

#1830 Squirtle - reduce dash/run GFX
  fighters/pzenigame/src/acmd/other.rs
Labels: aesthetics, semver:patch

#1831 Reintroduce heavy landing screenshake on non-wavedashes
  fighters/dedede/src/acmd/other.rs
  fighters/donkey/src/acmd/other.rs
  fighters/koopa/src/acmd/other.rs
  fighters/krool/src/acmd/other.rs
  fighters/plizardon/src/acmd/other.rs
  fighters/ridley/src/acmd/other.rs
Labels: aesthetics, semver:patch

#1834 Grounded move sliding bugfixes
  fighters/common/src/function_hooks/energy/motion.rs
  fighters/common/src/general_statuses/attack/attack.rs
  fighters/common/src/general_statuses/attack/attackdash.rs
  fighters/common/src/general_statuses/attack/attackx4.rs
  fighters/common/src/general_statuses/attack/mod.rs
  fighters/common/src/general_statuses/attackhi4.rs
  fighters/common/src/general_statuses/attacklw4.rs
  fighters/common/src/general_statuses/mod.rs
  romfs/source/fighter/bayonetta/motion/body/motion_patch.yaml
  romfs/source/fighter/mario/motion/body/motion_patch.yaml
  romfs/source/fighter/mariod/motion/body/motion_patch.yaml
Labels: bug, engine, semver:patch

#1790 Bayonetta: Neutral B Cancel Fix
  fighters/bayonetta/src/opff.rs
Labels: bug, semver:patch

#1811 Replace Bayonetta Dive Kick Input With Attack Input
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/opff.rs
  romfs/source/fighter/bayonetta/motion/body/motion_patch.yaml
  romfs/source/fighter/bayonetta/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1835 Squirtle - fix sliding ftilt
  romfs/source/fighter/pzenigame/motion/body/motion_patch.yaml
Labels: bug, semver:patch

#1842 DACDS bugfix
  fighters/common/src/general_statuses/attack/attackx4.rs
Labels: bug, engine, semver:patch

#1845 Wolf - fix rotation bug
  fighters/wolf/src/status/special_s.rs
Labels: bug, semver:patch

#1844 Fix spike crashes
  dynamic/src/ext.rs
  dynamic/src/frame_info.rs
  fighters/packun/src/acmd/mod.rs
  fighters/pikmin/src/acmd/mod.rs
  plugin/src/lib.rs
  utils/src/game_modes/tag.rs
  utils/src/modules/input.rs
  utils/src/modules/meter.rs
  utils/src/modules/param.rs
  utils/src/modules/status.rs
  utils/src/modules/var.rs
  utils/src/offsets.rs
  utils/src/ui.rs
  utils/src/ui/ex_meter.rs
  utils/src/ui/ff_meter.rs
  utils/src/ui/pichu_meter.rs
Labels: crash, semver:patch

#1847 Menu Bugfix
  romfs/source/ui/script/menu/main/main_menu_layer_online.lua
  romfs/source/ui/script/menu/main/main_menu_layer_top.lua
Labels: bug, semver:patch

#1542 Wario Shake Up Adjustments
  fighters/common/src/opff/other.rs
  fighters/wario/src/acmd/aerials.rs
  fighters/wario/src/acmd/ground.rs
  fighters/wario/src/acmd/other.rs
  fighters/wario/src/acmd/smashes.rs
  fighters/wario/src/acmd/throws.rs
  fighters/wario/src/acmd/tilts.rs
  fighters/wario/src/opff.rs
  fighters/wario/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/wario/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#1698 Bowser's Big Blast
  dynamic/src/consts.rs
  fighters/koopa/src/acmd/aerials.rs
  fighters/koopa/src/acmd/ground.rs
  fighters/koopa/src/acmd/other.rs
  fighters/koopa/src/acmd/specials.rs
  fighters/koopa/src/lib.rs
  fighters/koopa/src/opff.rs
  fighters/koopa/src/status.rs
  romfs/source/fighter/koopa/motion/body/motion_patch.yaml
  romfs/source/fighter/koopa/motion/breath/motion_patch.yaml
  romfs/source/fighter/koopa/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1699 Krool armor overhaul
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/common/src/misc.rs
  fighters/krool/src/acmd/aerials.rs
  fighters/krool/src/acmd/ground.rs
  fighters/krool/src/acmd/other.rs
  fighters/krool/src/acmd/smashes.rs
  fighters/krool/src/acmd/specials.rs
  fighters/krool/src/acmd/throws.rs
  fighters/krool/src/acmd/tilts.rs
  fighters/krool/src/lib.rs
  fighters/krool/src/opff.rs
  fighters/krool/src/status.rs
  fighters/krool/src/status/special_lw.rs
  fighters/krool/src/vtable_hook.rs
  romfs/source/fighter/krool/motion/body/motion_patch.yaml
  romfs/source/fighter/krool/param/hdr.xml
  romfs/source/fighter/krool/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1421 Rob changes
  dynamic/src/consts.rs
  fighters/robot/src/acmd/aerials.rs
  fighters/robot/src/acmd/specials.rs
  fighters/robot/src/acmd/throws.rs
  fighters/robot/src/acmd/tilts.rs
  fighters/robot/src/opff.rs
  romfs/source/fighter/robot/motion/body/motion_patch.yaml
  romfs/source/fighter/robot/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1797 MK followup adjustments
  fighters/metaknight/src/acmd/aerials.rs
  fighters/metaknight/src/acmd/specials.rs
  fighters/metaknight/src/acmd/throws.rs
  fighters/metaknight/src/acmd/tilts.rs
  romfs/source/fighter/metaknight/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#1762 Mii Brawler adjustments
  fighters/miifighter/src/acmd/aerials.rs
  fighters/miifighter/src/acmd/ground.rs
  fighters/miifighter/src/acmd/smashes.rs
  fighters/miifighter/src/acmd/specials.rs
  fighters/miifighter/src/acmd/throws.rs
  fighters/miifighter/src/acmd/tilts.rs
  fighters/miifighter/src/opff.rs
Labels: character change, semver:patch, backroom approved

#1822 Pichu balance changes
  fighters/pichu/src/acmd/aerials.rs
  fighters/pichu/src/acmd/ground.rs
  fighters/pichu/src/acmd/other.rs
  fighters/pichu/src/acmd/smashes.rs
  fighters/pichu/src/acmd/specials.rs
Labels: character change, semver:patch, backroom approved

#1820 Add blue DI line GFX on non-tumble DI
  fighters/common/src/general_statuses/mod.rs
  fighters/common/src/opff/tech.rs
Labels: engine, semver:patch

#1770 Ness Adjustments and effects cleanup.
  fighters/ness/src/acmd/aerials.rs
  fighters/ness/src/acmd/ground.rs
  fighters/ness/src/acmd/smashes.rs
  fighters/ness/src/acmd/specials.rs
  fighters/ness/src/acmd/throws.rs
  fighters/ness/src/opff.rs
Labels: character change, semver:patch
