Repository HDR-Development/HewDraw-Remix, pull requests merged in 2023-03, with the labels that each got.

#1359 Some changes to Mario's Firebrand
  fighters/mario/src/acmd/specials.rs
Labels: character change, semver:patch, backroom approved

#1407 Add platdrop momentum transfer
  fighters/common/src/function_hooks/edge_slipoffs.rs
  fighters/common/src/general_statuses/mod.rs
Labels: engine, semver:patch

#1402 Aegis Adjustments
  fighters/eflame/src/acmd/aerials.rs
  fighters/eflame/src/acmd/ground.rs
  fighters/eflame/src/acmd/smashes.rs
  fighters/eflame/src/acmd/tilts.rs
  fighters/elight/src/acmd/aerials.rs
  fighters/elight/src/acmd/ground.rs
  fighters/elight/src/acmd/smashes.rs
  fighters/elight/src/acmd/tilts.rs
Labels: character change, semver:patch, backroom approved

#1375 Mewtwo Adjustments
  fighters/common/src/opff/floats.rs
  fighters/mewtwo/src/acmd/aerials.rs
  fighters/mewtwo/src/acmd/ground.rs
  fighters/mewtwo/src/acmd/specials.rs
  fighters/mewtwo/src/acmd/throws.rs
  fighters/mewtwo/src/acmd/tilts.rs
  fighters/mewtwo/src/opff.rs
Labels: character change, semver:patch, backroom approved, includes assets

#1410 Fix Ivysaur & Joker upB teleports
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/mod.rs
Labels: bug, semver:patch

#1403 Hero adjustments
  fighters/brave/src/acmd/aerials.rs
  fighters/brave/src/acmd/ground.rs
  fighters/brave/src/acmd/other.rs
  fighters/brave/src/acmd/smashes.rs
  fighters/brave/src/acmd/specials.rs
  fighters/brave/src/acmd/tilts.rs
  romfs/source/fighter/brave/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1404 Sheik adjustments
  fighters/common/src/function_hooks/edge_slipoffs.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/sheik/src/acmd/aerials.rs
  fighters/sheik/src/acmd/ground.rs
  fighters/sheik/src/acmd/other.rs
  fighters/sheik/src/acmd/smashes.rs
  fighters/sheik/src/acmd/specials.rs
  fighters/sheik/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/sheik/param/vl.prcxml
  romfs/source/item/common/param/param.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1428 resolving issues with tourney config
  utils/src/modules/param.rs
Labels: semver:patch

#1430 Further fixes to tourney mode config
  romfs/source/ui/script_patch/common/stage_select_actor3.tourney.lua
  utils/build.rs
  utils/src/modules/param.rs
Labels: infrastructure, semver:patch

#1429 Reset projectile lifetime on parry
  fighters/common/src/function_hooks/mod.rs
  romfs/source/fighter/common/param/battle_object.prcxml
Labels: engine, semver:patch

#1434 Mario - fix upB landing
  fighters/mario/src/acmd/specials.rs
Labels: bug, semver:patch

#1288 System Changes (+ Wolf adjustments)
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/src/lib.rs
  fighters/wolf/Cargo.toml
  fighters/wolf/src/acmd/specials.rs
  fighters/wolf/src/lib.rs
  fighters/wolf/src/opff.rs
  fighters/wolf/src/status.rs
  fighters/wolf/src/status/special_s.rs
  plugin/src/lib.rs
  romfs/source/fighter/wolf/param/vl.prcxml
  utils/src/modules/meter.rs
Labels: character change, engine, semver:patch

#1438 Bowser Jr. - fix electric knockback bug
  fighters/koopajr/src/opff.rs
  fighters/koopajr/src/status.rs
Labels: bug, semver:patch

#1435 Pyra - remove rising upB ledgesnap
  fighters/common/src/function_hooks/ledges.rs
Labels: bug, semver:patch

#1415 Mario PM Fireball
  romfs/source/fighter/mario/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1420 Mario - Forward Air Effect Changes
  fighters/mario/src/acmd/aerials.rs
Labels: aesthetics, character change, semver:patch, backroom approved

#1419 Fix Cloud Air Cross Slash
  fighters/cloud/src/acmd/specials.rs
Labels: character change, semver:patch, backroom approved

#1443 Allow common OPFF to be placed on Exec status
  fighters/common/src/lib.rs
  fighters/common/src/opff/mod.rs
  fighters/common/src/opff/other.rs
Labels: bug, infrastructure, semver:patch

#1437 Steve - fix Minecart bugs
  fighters/common/src/function_hooks/mod.rs
Labels: bug, semver:patch

#1412 Order of Operations bugfixes
  fighters/common/src/function_hooks/change_motion.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/falco/src/opff.rs
  fighters/falco/src/status.rs
  fighters/falco/src/status/special_hi.rs
  fighters/fox/src/opff.rs
  fighters/fox/src/status.rs
  fighters/fox/src/status/special_hi.rs
  romfs/source/fighter/edge/param/vl.prcxml
  romfs/source/fighter/miigunner/param/vl.prcxml
  romfs/source/fighter/wolf/param/vl.prcxml
Labels: bug, engine, semver:patch

#1389 Peach and Daisy Sideb WallBounce
  dynamic/src/consts.rs
  fighters/daisy/src/opff.rs
  fighters/peach/src/opff.rs
Labels: character change, semver:patch, backroom approved

#1431 Sheik Cleanup
  fighters/sheik/src/acmd/smashes.rs
  fighters/sheik/src/acmd/specials.rs
  fighters/sheik/src/opff.rs
  romfs/source/fighter/sheik/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1433 Teleport wallride logic improvement
  fighters/mewtwo/src/opff.rs
  fighters/palutena/src/opff.rs
  fighters/sheik/src/opff.rs
  fighters/zelda/src/opff.rs
Labels: engine, semver:patch

#1446 Fix hitlag movement bug
  fighters/common/src/function_hooks/mod.rs
Labels: bug, engine, semver:patch

#1425 Wario Touch-Up
  fighters/wario/src/acmd/aerials.rs
  fighters/wario/src/acmd/ground.rs
  fighters/wario/src/acmd/smashes.rs
  fighters/wario/src/acmd/tilts.rs
Labels: character change, semver:patch, backroom approved

#1448 testing build changes
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
  scripts/extract_lvd_data.sh
Labels: semver:patch

#1449 fixes
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#1450 Update extract_lvd_data.sh
  scripts/extract_lvd_data.sh
Labels: semver:patch

#1451 Update extract_lvd_data.sh
  scripts/extract_lvd_data.sh
Labels: semver:patch

#1452 more build changes
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#1453 Update extract_lvd_data.sh
  scripts/extract_lvd_data.sh
Labels: semver:patch

#1454 Update extract_lvd_data.sh
  scripts/extract_lvd_data.sh
Labels: semver:patch

#1455 changing the order of ops
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#1456 Update extract_lvd_data.sh
  scripts/extract_lvd_data.sh
Labels: semver:patch

#1457 feat: move CSS before SSS
  plugin/src/lib.rs
Labels: aesthetics, semver:feature

#1439 Fix hanging on Salty Runback/Quick Exit inputs
  fighters/common/src/opff/mod.rs
Labels: bug, semver:patch

#1462 feat: add 0/1 player smash and remove no contest screen
  plugin/src/lib.rs
Labels: semver:feature

#1440 Spacies Effect/Misc Cleanup
  fighters/falco/src/acmd/specials.rs
  fighters/fox/src/acmd/specials.rs
  fighters/wolf/src/acmd/specials.rs
  fighters/wolf/src/acmd/tilts.rs
Labels: aesthetics, character change, semver:patch, backroom approved

#1465 Even more order of operations bugfixes
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/general_statuses/turn.rs
  fighters/simon/src/opff.rs
Labels: bug, crash, semver:patch

#1468 Captain Falcon - fix upB landing bug
  fighters/captain/src/acmd/specials.rs
Labels: bug, semver:patch

#1467 Fix training mode crash
  plugin/src/lib.rs
Labels: crash, semver:patch

#1460 Zelda - fix teleport wallride
  fighters/zelda/src/opff.rs
Labels: bug, semver:patch

#1436 Fix plat cancel leniency
  romfs/source/fighter/common/hdr/param/common.xml
Labels: engine, semver:patch

#1459 Bowser Jr. - fix hitstun bug
  fighters/koopajr/src/opff.rs
Labels: bug, semver:patch

#1470 Remove remaining held jabs
  fighters/donkey/src/acmd/ground.rs
  fighters/peach/src/acmd/ground.rs
  fighters/pitb/src/acmd/ground.rs
  fighters/shulk/src/acmd/ground.rs
Labels: character change, semver:patch

#1469 Ridley - fix downB aerial stalling bug
  fighters/ridley/src/status.rs
Labels: bug, semver:patch

#1473 Fix training mode reset
  plugin/src/lib.rs
Labels: bug, semver:patch

#1474 Fix minmin frfr
  fighters/common/src/function_hooks/mod.rs
Labels: crash, semver:patch

#1478 Fix Min Min frfrfr
  fighters/common/src/function_hooks/energy/motion.rs
  fighters/common/src/function_hooks/mod.rs
Labels: bug, semver:patch

#1481 Charizard Wavedash Fix
  fighters/plizardon/src/acmd/other.rs
Labels: aesthetics, semver:patch

#1483 Lingering GFX bugs cleanup
  fighters/common/src/function_hooks/change_motion.rs
  fighters/common/src/function_hooks/mod.rs
Labels: bug, semver:patch

#1475 Nerf knockback smoke even more
  fighters/common/src/general_statuses/damage.rs
  romfs/source/fighter/common/param/effect.prcxml
Labels: aesthetics, engine, semver:patch

#1477 Double air traction when above max jump speed
  fighters/common/src/function_hooks/energy/control.rs
Labels: engine, semver:patch

#1482 remove meta quick
  dynamic/src/consts.rs
  fighters/metaknight/src/acmd/other.rs
  fighters/metaknight/src/lib.rs
  fighters/metaknight/src/meta_quick.rs
  fighters/metaknight/src/opff.rs
  fighters/src/lib.rs
Labels: character change, semver:patch, backroom approved

#1480 Bowser Tough Guy Removal
  romfs/source/fighter/koopa/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1484 Sheik - fix jump cancel & reinstate airdodge cancel on Bouncing Fish return
  fighters/sheik/src/opff.rs
Labels: bug, semver:patch

#1444 Sonic - Very small eagle kick changes
  fighters/sonic/src/acmd/aerials.rs
Labels: character change, semver:patch, backroom approved

#1418 Sephiroth Balance Adjustments
  fighters/edge/src/acmd/aerials.rs
  fighters/edge/src/acmd/ground.rs
  fighters/edge/src/acmd/smashes.rs
  fighters/edge/src/acmd/tilts.rs
  fighters/edge/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#1488 Mii Gunner bugfixes
  fighters/common/src/function_hooks/mod.rs
  fighters/miigunner/src/acmd/other.rs
  fighters/miigunner/src/opff.rs
Labels: bug, semver:patch

#1490 Implement select_cliff_hangdata_from_name boma ext
  dynamic/src/ext.rs
Labels: infrastructure, semver:patch

#1491 Wario - chomp crash fix
  fighters/wario/src/opff.rs
Labels: crash, semver:patch

#1486 Kirby - remove rising upB ledgesnap
  fighters/kirby/src/acmd/specials.rs
Labels: bug, semver:patch

#1363 Zelda Cohesiveness Adjustment : Phantom Hitcancel, Dins Fire, Ftilt Normalization
  dynamic/src/consts.rs
  fighters/zelda/src/acmd/aerials.rs
  fighters/zelda/src/acmd/other.rs
  fighters/zelda/src/acmd/smashes.rs
  fighters/zelda/src/acmd/tilts.rs
  fighters/zelda/src/opff.rs
  fighters/zelda/src/status.rs
  fighters/zelda/src/status/phantom.rs
  romfs/source/fighter/zelda/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1408 Corrin recovery adjustments
  fighters/kamui/src/acmd/specials.rs
Labels: character change

#1489 Temporarily revert CSS/SSS switch and 0p smash
  plugin/src/lib.rs
Labels: bug, crash, semver:patch

#1500 Revert Meta Knight
  fighters/metaknight/src/lib.rs
Labels: bug, semver:patch

#1502 Mii Gunner hotfix
  romfs/source/fighter/miigunner/param/vl.prcxml
Labels: bug, semver:patch

#1498 Greninja - fix sideB reappearance
  fighters/common/src/function_hooks/mod.rs
Labels: bug, semver:patch

#1505 Little Mac - fix KO Punch
  fighters/littlemac/src/acmd/specials.rs
Labels: bug, semver:patch

#1508 Fix buffered actions out of jumpsquat
  fighters/common/src/function_hooks/change_motion.rs
  fighters/common/src/function_hooks/mod.rs
Labels: bug, engine, semver:patch

#1510 Fix Isabelle Lloid graphical issue
  fighters/common/src/function_hooks/change_motion.rs
Labels: bug, semver:patch
