Repository HDR-Development/HewDraw-Remix, pull requests merged in 2023-01, with the labels that each got.

#1271 ZSS - adjust uair gfx for adjusted anim
  fighters/szerosuit/src/acmd/aerials.rs
Labels: aesthetics, semver:patch

#1272 Samus - adjust bair gfx for adjusted animation
  fighters/samus/src/acmd/aerials.rs
Labels: aesthetics, semver:patch

#1273 update dep for release downloader action
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
Labels: semver:patch

#1274 Quick Draw Fix
  fighters/ike/src/opff.rs
Labels: bug, semver:patch

#1275 Missed a Transition Term for Jump Cancel boma ext
  dynamic/src/ext.rs
Labels: bug, semver:patch

#1259 Ridley rework
  dynamic/src/consts.rs
  fighters/ridley/src/acmd/aerials.rs
  fighters/ridley/src/acmd/ground.rs
  fighters/ridley/src/acmd/other.rs
  fighters/ridley/src/acmd/smashes.rs
  fighters/ridley/src/acmd/specials.rs
  fighters/ridley/src/acmd/tilts.rs
  fighters/ridley/src/lib.rs
  fighters/ridley/src/opff.rs
  fighters/ridley/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/ridley/param/vl.prcxml
Labels: character change, semver:patch

#1258 Lucina Adjustments
  fighters/lucina/src/acmd/aerials.rs
  fighters/lucina/src/acmd/ground.rs
  fighters/lucina/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/lucina/param/vl.prcxml
Labels: character change, semver:patch

#1276 Further missing transition terms from the jump cancel boma extension
  dynamic/src/ext.rs
Labels: bug, semver:patch

#1163 Banjo new tricks
  .gitignore
  dynamic/src/consts.rs
  fighters/buddy/src/acmd/aerials.rs
  fighters/buddy/src/acmd/ground.rs
  fighters/buddy/src/acmd/other.rs
  fighters/buddy/src/acmd/smashes.rs
  fighters/buddy/src/acmd/specials.rs
  fighters/buddy/src/acmd/throws.rs
  fighters/buddy/src/acmd/tilts.rs
  fighters/buddy/src/opff.rs
  fighters/buddy/src/status.rs
  romfs/source/fighter/buddy/param/vl.prcxml
Labels: character change, semver:patch

#1277 Allow three intangible ledge grabs and remove ledge grab limit
  fighters/common/src/opff/mod.rs
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#1283 simplifying backroom approval process
  .github/workflows/backroom_approval.yml
  .github/workflows/on_comment.yml
  .github/workflows/semver_label_check.yml
Labels: semver:patch

#1280 Removes the grab timer
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#1295 Remove Skewer trip chance
  fighters/ridley/src/acmd/specials.rs
Labels: bug, semver:patch

#1266 Properly Aggregate Nana BattleObject When Getting All Players
  dynamic/src/util.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/function_hooks/ledges.rs
  utils/src/game_modes/airdash.rs
  utils/src/game_modes/hitfall.rs
  utils/src/game_modes/turbo.rs
Labels: bug, semver:patch

#1278 Banjo Overhaul Fixes
  fighters/buddy/src/acmd/specials.rs
  fighters/buddy/src/opff.rs
  fighters/buddy/src/status.rs
Labels: bug, semver:patch

#1282 Spikes cause knockdown splat rather than ground bounce
  fighters/common/src/general_statuses/mod.rs
Labels: engine, semver:patch

#1293 Mewtwo Hurtbox Fix
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/mewtwo/src/acmd/aerials.rs
  fighters/mewtwo/src/acmd/tilts.rs
  romfs/source/fighter/mewtwo/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1279 dk adjustments
  dynamic/src/consts.rs
  fighters/donkey/src/acmd/aerials.rs
  fighters/donkey/src/acmd/ground.rs
  fighters/donkey/src/acmd/other.rs
  fighters/donkey/src/acmd/specials.rs
  fighters/donkey/src/acmd/tilts.rs
  fighters/donkey/src/opff.rs
  fighters/donkey/src/status/special_lw.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#1286 Bayonetta Jab123 Fix
  fighters/bayonetta/src/acmd/ground.rs
Labels: character change, semver:patch, backroom approved

#1269 Rise-And-Dive Up B Cancel Behavior Change
  dynamic/src/consts.rs
  fighters/chrom/src/opff.rs
  fighters/gaogaen/src/acmd/specials.rs
  fighters/gaogaen/src/opff.rs
  fighters/kirby/src/opff.rs
Labels: character change, semver:patch, backroom approved

#1290 Disallow projectiles during aegis reflector
  fighters/common/src/function_hooks/transition.rs
  romfs/source/fighter/palutena/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1287 Fix Byleth up special command grab still spiking
  fighters/master/src/acmd/specials.rs
Labels: bug, semver:patch

#1321 Removed Spin Dash B Reverse
  fighters/sonic/src/status.rs
Labels: bug, semver:patch

#1328 Revert "Spikes cause knockdown splat rather than ground bounce"
  fighters/common/src/general_statuses/mod.rs
Labels: semver:patch

#1291 Ground bounce adjustments
  fighters/common/src/general_statuses/damageflyreflect.rs
  fighters/common/src/general_statuses/mod.rs
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#1324 Alolan Whip cleanup
  fighters/gaogaen/src/acmd/specials.rs
Labels: bug, semver:patch

#1318 Version info on arena
  plugin/Cargo.toml
  plugin/src/lib.rs
  plugin/src/online.rs
Labels: enhancement, semver:patch

#1297 Zelda - Gfx/hitbox/set play refinement
  dynamic/src/consts.rs
  fighters/zelda/src/acmd/aerials.rs
  fighters/zelda/src/acmd/other.rs
  fighters/zelda/src/acmd/specials.rs
  romfs/source/fighter/zelda/param/vl.prcxml
Labels: aesthetics, character change, semver:patch, backroom approved

#1289 Newer Lucas Just Dropped
  dynamic/src/consts.rs
  fighters/lucas/src/acmd/aerials.rs
  fighters/lucas/src/acmd/smashes.rs
  fighters/lucas/src/acmd/specials.rs
  fighters/lucas/src/acmd/throws.rs
  fighters/lucas/src/lib.rs
  fighters/lucas/src/opff.rs
  fighters/lucas/src/status.rs
  fighters/ness/src/lib.rs
  fighters/ness/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/lucas/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1316 Lucina Adjustments cont.
  dynamic/src/consts.rs
  fighters/lucina/src/acmd/aerials.rs
  fighters/lucina/src/acmd/specials.rs
  fighters/lucina/src/acmd/tilts.rs
  fighters/lucina/src/opff.rs
  fighters/lucina/src/status.rs
Labels: aesthetics, character change, semver:patch, backroom approved, includes assets

#1317 Banjo Tweaks
  fighters/buddy/src/acmd/aerials.rs
  fighters/buddy/src/acmd/ground.rs
  fighters/buddy/src/acmd/smashes.rs
  fighters/buddy/src/acmd/tilts.rs
Labels: character change, semver:patch, backroom approved

#1320 Remove launcher hitbox from Ganon uspecial
  fighters/ganon/src/acmd/specials.rs
Labels: character change, semver:patch, backroom approved

#1330 Further Joker Adjustments
  fighters/jack/src/acmd/aerials.rs
  fighters/jack/src/acmd/ground.rs
  fighters/jack/src/acmd/smashes.rs
  fighters/jack/src/acmd/tilts.rs
  romfs/source/fighter/jack/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1323 Decrease knockdown bounce heights globally
  dynamic/src/consts.rs
  fighters/common/src/opff/other.rs
Labels: engine, semver:patch

#1309 Mii Gunner small adjustments
  dynamic/src/consts.rs
  fighters/miigunner/src/acmd/aerials.rs
  fighters/miigunner/src/acmd/other.rs
  fighters/miigunner/src/acmd/specials.rs
  fighters/miigunner/src/acmd/tilts.rs
  fighters/miigunner/src/opff.rs
Labels: character change, semver:patch, backroom approved

#1335 fixes drift di for ground and air meteors
  fighters/common/src/function_hooks/directional_influence.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/opff/tech.rs
Labels: engine, semver:patch

#1340 Lucario Recovery Changes
  fighters/lucario/src/opff.rs
Labels: character change, semver:feature

#1339 Squirtle Recovery Changes
  fighters/pzenigame/src/acmd/specials.rs
  fighters/pzenigame/src/opff.rs
  romfs/source/fighter/pzenigame/param/vl.prcxml
Labels: character change, semver:feature

#1333 Minor throw adjustments
  fighters/mario/src/acmd/throws.rs
  fighters/mariod/src/acmd/throws.rs
Labels: character change, semver:patch

#1298 Rosalina hitbox edits
  fighters/rosetta/src/acmd/aerials.rs
  fighters/rosetta/src/acmd/ground.rs
  fighters/rosetta/src/acmd/tilts.rs
  romfs/source/fighter/rosetta/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1319 Allow bypassing of platform cancels
  fighters/common/src/opff/physics.rs
Labels: engine, semver:patch

#1336 Global air acceleration nerfs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch

#1325 Chrom - revert upB cancel behavior
  fighters/chrom/src/opff.rs
Labels: character change, semver:patch, backroom approved

#1314 Megaman Adjustments
  fighters/rockman/src/acmd/aerials.rs
  fighters/rockman/src/acmd/ground.rs
  fighters/rockman/src/acmd/other.rs
  fighters/rockman/src/acmd/specials.rs
  fighters/rockman/src/acmd/tilts.rs
  fighters/rockman/src/opff.rs
Labels: character change, semver:patch, backroom approved

#1301 Simon's Non-invasive Fix-Buff-Patch-Stuff
  fighters/simon/src/acmd/aerials.rs
  fighters/simon/src/acmd/specials.rs
  fighters/simon/src/opff.rs
Labels: character change, semver:patch, backroom approved

#1334 Fix Ledgehogging for PT/Aegis & Other Bugs
  dynamic/src/util.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/function_hooks/ledges.rs
  utils/src/game_modes/airdash.rs
  utils/src/game_modes/hitfall.rs
  utils/src/game_modes/turbo.rs
Labels: bug, semver:patch

#1337 Zelda Din now properly despawns on input
  fighters/zelda/src/status.rs
Labels: bug, semver:patch
