Repository HDR-Development/HewDraw-Remix, pull requests merged in 2023-11, with the labels that each got.

#2049 Remove Gatlings
  fighters/common/src/general_statuses/attack/attackdash.rs
Labels: engine, semver:patch, backroom approved

#2050 fix build script caching issue
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
  .github/workflows/pr_build.yml
  scripts/pkgutil.py
Labels: semver:patch

#2054 PTrainer - Hold to Backwards Switch
  .gitignore
  dynamic/src/consts.rs
  fighters/common/src/misc.rs
  fighters/pfushigisou/src/opff.rs
  fighters/pfushigisou/src/status.rs
  fighters/plizardon/src/opff.rs
  fighters/plizardon/src/status.rs
  fighters/pzenigame/src/opff.rs
  fighters/pzenigame/src/status.rs
Labels: character change, semver:patch, backroom approved

#2052 Amsah tech fix
  fighters/common/src/general_statuses/passive.rs
Labels: engine, semver:patch

#2036 Dark Samus Changes 2: Phazon Boogaloo
  fighters/samusd/src/acmd/aerials.rs
  fighters/samusd/src/acmd/ground.rs
  fighters/samusd/src/acmd/tilts.rs
  fighters/samusd/src/opff.rs
Labels: character change, semver:patch, backroom approved, includes assets

#2015 Pichu Tune-ups
  fighters/pichu/src/acmd/aerials.rs
  fighters/pichu/src/acmd/smashes.rs
Labels: character change, semver:patch, backroom approved

#1954 Steve Adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/pickel/src/acmd/aerials.rs
  fighters/pickel/src/acmd/other.rs
  fighters/pickel/src/lib.rs
  fighters/pickel/src/opff.rs
  fighters/pickel/src/status.rs
  romfs/source/fighter/pickel/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#2033 Sora/Steve follow-up fixes
  fighters/pickel/src/opff.rs
  fighters/trail/src/acmd/specials.rs
Labels: bug, character change, semver:patch, backroom approved

#2010 Dedede followup changes: Tennis edition
  fighters/dedede/src/acmd/other.rs
  fighters/dedede/src/acmd/specials.rs
  fighters/dedede/src/opff.rs
  romfs/source/fighter/dedede/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1893 Ken Followup Changes & Ryu Cleanup
  fighters/ken/src/acmd/finals.rs
  fighters/ken/src/acmd/ground.rs
  fighters/ken/src/acmd/other.rs
  fighters/ken/src/acmd/specials.rs
  fighters/ken/src/acmd/tilts.rs
  fighters/ken/src/lib.rs
  fighters/ken/src/opff.rs
  fighters/ken/src/status.rs
  fighters/ken/src/status/finals.rs
  fighters/ken/src/status/special_cmd4.rs
  fighters/ken/src/status/special_lw.rs
  fighters/ken/src/status/special_s.rs
  fighters/ryu/src/lib.rs
  fighters/ryu/src/opff.rs
  fighters/ryu/src/status.rs
  fighters/ryu/src/status/finals.rs
  fighters/ryu/src/status/special_s.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/ken/motion/body/motion_patch.yaml
  romfs/source/fighter/ken/param/vl.prcxml
  romfs/source/fighter/ryu/param/vl.prcxml
Labels: bug, character change, semver:patch, backroom approved, includes assets

#2024 Yoshi - adjusted jabs & dash attack
  fighters/yoshi/src/acmd/ground.rs
Labels: character change, semver:patch, backroom approved, includes assets

#2065 ken/ryu hotfix
  fighters/ken/src/acmd/specials.rs
  fighters/ryu/src/opff.rs
Labels: character change, semver:patch, backroom approved

#1980 Marth redesign (Continuation)
  fighters/marth/src/acmd/aerials.rs
  fighters/marth/src/acmd/specials.rs
  fighters/marth/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/marth/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2016 Link - New dash attack (+more!)
  fighters/link/src/acmd/aerials.rs
  fighters/link/src/acmd/ground.rs
  romfs/source/fighter/link/motion/body/motion_patch.yaml
Labels: semver:patch, includes assets

#2017 Zelda Power-Shift by Zhime
  dynamic/src/consts.rs
  fighters/zelda/src/acmd/aerials.rs
  fighters/zelda/src/acmd/other.rs
  fighters/zelda/src/acmd/smashes.rs
  fighters/zelda/src/acmd/specials.rs
  fighters/zelda/src/acmd/throws.rs
  fighters/zelda/src/acmd/tilts.rs
  fighters/zelda/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/zelda/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#2075 Mii Swordfighter Warrior Wave Beam effect reduction
  fighters/miiswordsman/src/acmd/other.rs
Labels: bug, semver:patch

#2044 Piranha Plant changes pt. 3.5
  dynamic/src/consts.rs
  fighters/packun/src/acmd/other.rs
  fighters/packun/src/opff.rs
Labels: character change, semver:patch, backroom approved

#2032 Remove 5f tap buffer extension during tumble
  fighters/common/src/general_statuses/mod.rs
Labels: engine, semver:patch

#2059 Once-per-airtime adjustments
  dynamic/src/consts.rs
  fighters/daisy/src/status/mod.rs
  fighters/daisy/src/status/special_s.rs
  fighters/inkling/src/status.rs
  fighters/inkling/src/status/special_s.rs
  fighters/koopajr/src/status.rs
  fighters/lucario/src/status.rs
  fighters/mario/src/acmd/specials.rs
  fighters/mario/src/status.rs
  fighters/mariod/src/acmd/specials.rs
  fighters/mariod/src/status.rs
  fighters/peach/src/status/mod.rs
  fighters/peach/src/status/special_s.rs
  fighters/pickel/src/status.rs
Labels: character change, semver:patch, backroom approved

#2061 Actionable upB behavior change
  dynamic/src/consts.rs
  fighters/brave/src/opff.rs
  fighters/buddy/src/opff.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/demon/src/opff.rs
  fighters/elight/src/status.rs
  fighters/elight/src/status/special_hi_finish2.rs
  fighters/elight/src/status/special_hi_jump.rs
  fighters/mewtwo/src/opff.rs
  fighters/palutena/src/opff.rs
  fighters/reflet/src/opff.rs
  fighters/rockman/src/opff.rs
  fighters/sonic/src/opff.rs
Labels: engine, semver:patch

#2069 Added landing effect to grounded Min Min tether
  fighters/tantan/src/acmd/specials.rs
Labels: good first issue, aesthetics, semver:patch

#2074 Misc 3.5
  fighters/diddy/src/status/special_s_jump.rs
  fighters/kirby/src/opff.rs
Labels: bug, semver:patch

#2081 Phantom Cancel Bug Fix
  dynamic/src/consts.rs
  fighters/zelda/src/acmd/other.rs
  fighters/zelda/src/opff.rs
Labels: bug, semver:patch

#2094 Fix Inkling roller flick
  fighters/inkling/src/status/special_s.rs
Labels: bug, semver:patch

#2095 Mythra upB freefall bugfix
  fighters/eflame/src/status.rs
Labels: bug, semver:patch

#2092 Charge cancel bugfix
  fighters/common/src/function_hooks/is_flag.rs
Labels: bug, semver:patch
