Repository HDR-Development/HewDraw-Remix, pull requests merged in 2023-02, with the labels that each got.

#1315 Dash attack speed/distance adjustments
  fighters/bayonetta/src/acmd/ground.rs
  fighters/dedede/src/acmd/ground.rs
  fighters/duckhunt/src/acmd/ground.rs
  fighters/edge/src/acmd/ground.rs
  fighters/elight/src/acmd/ground.rs
  fighters/falco/src/acmd/ground.rs
  fighters/ganon/src/acmd/ground.rs
  fighters/gaogaen/src/acmd/ground.rs
  fighters/ike/src/acmd/ground.rs
  fighters/inkling/src/acmd/ground.rs
  fighters/jack/src/acmd/ground.rs
  fighters/ken/src/acmd/ground.rs
  fighters/koopa/src/acmd/ground.rs
  fighters/krool/src/acmd/ground.rs
  fighters/littlemac/src/acmd/ground.rs
  fighters/luigi/src/acmd/ground.rs
  fighters/mariod/src/acmd/ground.rs
  fighters/metaknight/src/acmd/ground.rs
  fighters/metaknight/src/meta_quick.rs
  fighters/mewtwo/src/acmd/ground.rs
  fighters/miigunner/src/acmd/ground.rs
  fighters/nana/src/acmd/ground.rs
  fighters/packun/src/acmd/ground.rs
  fighters/pichu/src/acmd/ground.rs
  fighters/pikachu/src/acmd/ground.rs
  fighters/pit/src/acmd/ground.rs
  fighters/pitb/src/acmd/ground.rs
  fighters/popo/src/acmd/ground.rs
  fighters/pzenigame/src/acmd/ground.rs
  fighters/ridley/src/acmd/ground.rs
  fighters/samusd/src/acmd/ground.rs
  fighters/tantan/src/acmd/ground.rs
  fighters/trail/src/acmd/ground.rs
  fighters/wario/src/acmd/ground.rs
  fighters/wiifit/src/acmd/ground.rs
  fighters/yoshi/src/acmd/ground.rs
Labels: engine, semver:patch

#1356 Revert "Simon's Non-invasive Fix-Buff-Patch-Stuff"
  fighters/simon/src/acmd/aerials.rs
  fighters/simon/src/acmd/specials.rs
  fighters/simon/src/opff.rs
Labels: semver:patch

#1357 Revert "Revert "Simon's Non-invasive Fix-Buff-Patch-Stuff""
  fighters/simon/src/acmd/aerials.rs
  fighters/simon/src/acmd/specials.rs
  fighters/simon/src/opff.rs
Labels: semver:patch

#1360 Fixed an issue causing Pichu Dash Attack to panic
  fighters/pichu/src/acmd/ground.rs
Labels: bug, semver:patch

#1361 update our packaged smashline hook
  scripts/full_package.py
Labels: infrastructure, semver:patch

#1313 Jigglypuff tweaks and turnaround bair removals
  fighters/purin/src/acmd/aerials.rs
  fighters/purin/src/acmd/specials.rs
  fighters/purin/src/acmd/throws.rs
  fighters/purin/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/purin/param/vl.prcxml
Labels: aesthetics, character change, semver:patch, backroom approved, includes assets

#1322 Dedede Tweaks
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/dedede/src/acmd/ground.rs
  fighters/dedede/src/acmd/other.rs
  fighters/dedede/src/acmd/smashes.rs
  fighters/dedede/src/acmd/specials.rs
  fighters/dedede/src/acmd/tilts.rs
  romfs/source/fighter/dedede/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1354 Further air acceleration adjustments
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#1343 WaveLand and WaveDash Improvements
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/collision.rs
  fighters/common/src/general_statuses/jumpsquat.rs
Labels: engine, semver:patch

#1365 ICs followup adjustments
  fighters/nana/src/acmd/aerials.rs
  fighters/nana/src/acmd/throws.rs
  fighters/popo/src/acmd/aerials.rs
  fighters/popo/src/acmd/throws.rs
Labels: bug, character change, semver:patch, backroom approved, includes assets

#1368 Quick Riposte and Dancing Blade Adjustments
  fighters/lucina/src/acmd/specials.rs
  fighters/lucina/src/status.rs
Labels: character change, semver:patch, backroom approved

#1374 Jigglypuff visual cleanup
  fighters/purin/src/acmd/aerials.rs
  fighters/purin/src/acmd/specials.rs
  fighters/purin/src/acmd/throws.rs
Labels: aesthetics, semver:patch, includes assets

#1364 nerfs to some small things on dk
  fighters/donkey/src/acmd/specials.rs
  fighters/donkey/src/acmd/throws.rs
  romfs/source/fighter/common/param/common.prcxml
Labels: character change, semver:patch, backroom approved

#1232 Little Mac adjustments
  dynamic/src/consts.rs
  fighters/littlemac/src/acmd/aerials.rs
  fighters/littlemac/src/acmd/ground.rs
  fighters/littlemac/src/acmd/smashes.rs
  fighters/littlemac/src/acmd/specials.rs
  fighters/littlemac/src/acmd/throws.rs
  fighters/littlemac/src/acmd/tilts.rs
  fighters/littlemac/src/lib.rs
  fighters/littlemac/src/opff.rs
  fighters/littlemac/src/status.rs
  fighters/littlemac/src/status/special_n_cancel.rs
  fighters/src/lib.rs
  romfs/source/fighter/littlemac/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1382 Mega Man adjustments
  fighters/rockman/src/acmd/aerials.rs
  fighters/rockman/src/acmd/ground.rs
  fighters/rockman/src/acmd/other.rs
  fighters/rockman/src/acmd/tilts.rs
  fighters/rockman/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#1391 Remove heavy tornado fr fr
  fighters/miiswordsman/src/acmd/specials.rs
Labels: bug, semver:patch

#1401 small batch of hotfixes
  fighters/buddy/src/acmd/ground.rs
  fighters/buddy/src/opff.rs
  fighters/buddy/src/status.rs
  fighters/common/src/general_statuses/damage.rs
  fighters/littlemac/src/opff.rs
  fighters/littlemac/src/status/special_n_cancel.rs
  fighters/lucas/src/acmd/throws.rs
  fighters/marth/src/acmd/smashes.rs
  fighters/miiswordsman/src/acmd/specials.rs
  fighters/purin/src/acmd/aerials.rs
  fighters/purin/src/acmd/ground.rs
  fighters/purin/src/acmd/specials.rs
  fighters/rockman/src/acmd/aerials.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: bug, semver:patch

#1349 Little Mac Recovery Adjustments
  fighters/littlemac/src/acmd/specials.rs
  romfs/source/fighter/littlemac/param/vl.prcxml
Labels: character change

#1405 Fix banjo dair bounce
  fighters/buddy/src/opff.rs
Labels: bug, semver:patch

#1385 Pichu - Discharge buffs
  dynamic/src/consts.rs
  fighters/pichu/src/acmd/specials.rs
  romfs/source/fighter/pichu/param/hdr.xml
Labels: character change, semver:patch, backroom approved

#1406 Tether trump adjustments
  fighters/common/src/opff/ledges.rs
  romfs/source/fighter/common/hdr/param/common.xml
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#1394 Remove magnifying glass shrinking
  romfs/source/ui/param/info/hud_param.prcxml
Labels: aesthetics, semver:patch

#1346 Luigi Recovery Adustments
  fighters/luigi/src/acmd/specials.rs
  fighters/luigi/src/opff.rs
  romfs/source/fighter/luigi/param/vl.prcxml
Labels: character change

#1398 Gnw adjustments
  fighters/gamewatch/src/acmd/aerials.rs
  fighters/gamewatch/src/acmd/ground.rs
  fighters/gamewatch/src/acmd/smashes.rs
  fighters/gamewatch/src/acmd/specials.rs
  fighters/gamewatch/src/acmd/throws.rs
  fighters/gamewatch/src/acmd/tilts.rs
  fighters/gamewatch/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#1417 Fixes Dash Back > Shield for FGCs
  fighters/common/src/general_statuses/dash.rs
Labels: bug, semver:patch
