Repository HDR-Development/HewDraw-Remix, pull requests merged in 2023-08, with the labels that each got.

#1864 Fixes Shotos Crashing the Game
  fighters/diddy/src/status/special_n.rs
  fighters/dolly/src/opff.rs
  fighters/donkey/src/status/link_event.rs
  fighters/eflame/src/acmd/specials.rs
  fighters/littlemac/src/status/special_n_cancel.rs
  fighters/packun/src/acmd/tilts.rs
  fighters/wolf/src/status/special_s.rs
Labels: semver:patch

#1867 Nerf Wolf Aerial Shine Active Frames
  fighters/wolf/src/acmd/specials.rs
Labels: character change, semver:patch, backroom approved

#1796 Fix DACUS input with Tilt button
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/transition.rs
  fighters/common/src/general_statuses/dash.rs
  utils/src/modules/input.rs
Labels: bug, engine, semver:patch

#1861 ROB Bugfix
  fighters/robot/src/opff.rs
  romfs/source/fighter/robot/param/vl.prcxml
Labels: bug, semver:patch

#1859 Sliding move bugfixes
  romfs/source/fighter/daisy/motion/body/motion_patch.yaml
  romfs/source/fighter/peach/motion/body/motion_patch.yaml
  romfs/source/fighter/plizardon/motion/body/motion_patch.yaml
  romfs/source/fighter/shulk/motion/body/motion_patch.yaml
  romfs/source/fighter/wiifit/motion/body/motion_patch.yaml
Labels: bug, semver:patch

#1841 Bayonetta - jump momentum bugfix
  fighters/bayonetta/src/status/attackair.rs
  fighters/bayonetta/src/status/mod.rs
Labels: bug, semver:patch

#1848 Little Mac - fix Straight Lunge out of jump squat
  fighters/common/src/function_hooks/mod.rs
  fighters/littlemac/src/status/special_n_cancel.rs
Labels: bug, semver:patch

#1684 Robin Thunder Rework
  dynamic/src/consts.rs
  fighters/robin/src/acmd/other.rs
  fighters/robin/src/status.rs
  romfs/source/fighter/reflet/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1873 Fix Terry/Ken/Ryu/Yoshi shield release FAF
  fighters/dolly/src/status.rs
  fighters/ken/src/status.rs
  fighters/ryu/src/status.rs
  fighters/yoshi/src/status.rs
Labels: bug, semver:patch

#1767 Dedede nerfs/followup changes
  fighters/dedede/src/acmd/aerials.rs
  fighters/dedede/src/acmd/ground.rs
  fighters/dedede/src/acmd/other.rs
  fighters/dedede/src/acmd/smashes.rs
  fighters/dedede/src/acmd/specials.rs
  fighters/dedede/src/acmd/tilts.rs
  romfs/source/fighter/dedede/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#1805 Mii Gunner adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/miigunner/src/acmd/aerials.rs
  fighters/miigunner/src/acmd/ground.rs
  fighters/miigunner/src/acmd/other.rs
  fighters/miigunner/src/acmd/smashes.rs
  fighters/miigunner/src/acmd/specials.rs
  fighters/miigunner/src/acmd/throws.rs
  fighters/miigunner/src/acmd/tilts.rs
  fighters/miigunner/src/opff.rs
  fighters/miigunner/src/status.rs
  fighters/rom_watch.txt
  romfs/config.json
  romfs/source/fighter/miigunner/param/hdr.xml
  romfs/source/fighter/miigunner/param/vl.prcxml
  utils/agent_params.txt
Labels: character change, semver:patch, backroom approved

#1810 Lucina Follow up Adjustments
  dynamic/src/consts.rs
  fighters/lucina/src/acmd/aerials.rs
  fighters/lucina/src/acmd/ground.rs
  fighters/lucina/src/acmd/smashes.rs
  fighters/lucina/src/acmd/specials.rs
  fighters/lucina/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#1837 Corrin adjustments
  dynamic/src/consts.rs
  fighters/kamui/src/acmd/aerials.rs
  fighters/kamui/src/acmd/ground.rs
  fighters/kamui/src/acmd/other.rs
  fighters/kamui/src/acmd/smashes.rs
  fighters/kamui/src/acmd/specials.rs
  fighters/kamui/src/acmd/throws.rs
  fighters/kamui/src/acmd/tilts.rs
  fighters/kamui/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/kamui/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#1849 Dr. Mario adjustments
  dynamic/src/consts.rs
  fighters/mariod/src/acmd/aerials.rs
  fighters/mariod/src/acmd/ground.rs
  fighters/mariod/src/acmd/smashes.rs
  fighters/mariod/src/acmd/specials.rs
  fighters/mariod/src/acmd/throws.rs
  fighters/mariod/src/acmd/tilts.rs
  fighters/mariod/src/lib.rs
  fighters/mariod/src/opff.rs
  fighters/mariod/src/status.rs
  fighters/mariod/src/status/special_n.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/mariod/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#1839 Wii Fit Trainer adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/wiifit/Cargo.toml
  fighters/wiifit/src/acmd/aerials.rs
  fighters/wiifit/src/acmd/ground.rs
  fighters/wiifit/src/acmd/smashes.rs
  fighters/wiifit/src/acmd/specials.rs
  fighters/wiifit/src/acmd/tilts.rs
  fighters/wiifit/src/opff.rs
  romfs/source/fighter/wiifit/motion/body/motion_patch.yaml
  romfs/source/fighter/wiifit/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1862 Remove Drift DI
  fighters/common/src/opff/tech.rs
  romfs/source/fighter/common/hdr/param/common.xml
Labels: engine, semver:patch

#1878 Update DamageFlyTop gravity values to reflect current gravity values
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: engine, semver:patch

#1884 More sliding/disjointed move bugfixes
  romfs/source/fighter/cloud/motion/body/motion_patch.yaml
  romfs/source/fighter/dedede/motion/body/motion_patch.yaml
  romfs/source/fighter/donkey/motion/body/motion_patch.yaml
  romfs/source/fighter/ganon/motion/body/motion_patch.yaml
  romfs/source/fighter/inkling/motion/body/motion_patch.yaml
  romfs/source/fighter/lucario/motion/body/motion_patch.yaml
  romfs/source/fighter/mewtwo/motion/body/motion_patch.yaml
  romfs/source/fighter/murabito/motion/body/motion_patch.yaml
  romfs/source/fighter/packun/motion/body/motion_patch.yaml
  romfs/source/fighter/palutena/motion/body/motion_patch.yaml
  romfs/source/fighter/pfushigisou/motion/body/motion_patch.yaml
  romfs/source/fighter/pikmin/motion/body/motion_patch.yaml
  romfs/source/fighter/pit/motion/body/motion_patch.yaml
  romfs/source/fighter/pitb/motion/body/motion_patch.yaml
  romfs/source/fighter/plizardon/motion/body/motion_patch.yaml
  romfs/source/fighter/pzenigame/motion/body/motion_patch.yaml
  romfs/source/fighter/reflet/motion/body/motion_patch.yaml
  romfs/source/fighter/richter/motion/body/motion_patch.yaml
  romfs/source/fighter/ridley/motion/body/motion_patch.yaml
  romfs/source/fighter/samus/motion/body/motion_patch.yaml
  romfs/source/fighter/samusd/motion/body/motion_patch.yaml
  romfs/source/fighter/shizue/motion/body/motion_patch.yaml
  romfs/source/fighter/simon/motion/body/motion_patch.yaml
  romfs/source/fighter/wolf/motion/body/motion_patch.yaml
  romfs/source/fighter/yoshi/motion/body/motion_patch.yaml
  romfs/source/fighter/zelda/motion/body/motion_patch.yaml
Labels: bug, semver:patch

#1904 Resolve dependency error
  plugin/src/lib.rs
  plugin/src/online.rs
  plugin/src/updater.rs
Labels: bug, infrastructure, semver:patch

#1838 Gnw adjustments
  fighters/gamewatch/src/acmd/aerials.rs
  fighters/gamewatch/src/acmd/ground.rs
  fighters/gamewatch/src/acmd/smashes.rs
  fighters/gamewatch/src/acmd/specials.rs
  fighters/gamewatch/src/acmd/throws.rs
  fighters/gamewatch/src/acmd/tilts.rs
  fighters/gamewatch/src/opff.rs
  fighters/gamewatch/src/status.rs
  romfs/source/fighter/gamewatch/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#1464 Peach Tweaks
  fighters/peach/src/acmd/aerials.rs
  fighters/peach/src/acmd/ground.rs
  fighters/peach/src/acmd/mod.rs
  fighters/peach/src/acmd/specials.rs
  fighters/peach/src/acmd/throws.rs
  fighters/peach/src/acmd/tilts.rs
  romfs/source/fighter/peach/motion/body/motion_patch.yaml
  romfs/source/fighter/peach/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1763 Palutena Rework: Power Board
  dynamic/src/consts.rs
  dynamic/src/ui.rs
  fighters/common/src/function_hooks/transition.rs
  fighters/palutena/src/acmd/aerials.rs
  fighters/palutena/src/acmd/ground.rs
  fighters/palutena/src/acmd/smashes.rs
  fighters/palutena/src/acmd/specials.rs
  fighters/palutena/src/acmd/tilts.rs
  fighters/palutena/src/lib.rs
  fighters/palutena/src/opff.rs
  fighters/palutena/src/status.rs
  fighters/palutena/src/status/special_n.rs
  romfs/source/fighter/palutena/motion/body/motion_patch.yaml
  romfs/source/fighter/palutena/param/vl.prcxml
  utils/src/ui.rs
  utils/src/ui/power_board.rs
Labels: character change, semver:patch, backroom approved, includes assets

#1907 Restores Ryu/Ken's Fixed Jump Arcs
  fighters/common/src/function_hooks/energy/control.rs
Labels: bug, semver:patch

#1863 C-stick fixes
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/controls.rs
  fighters/common/src/function_hooks/jumps.rs
  fighters/common/src/general_statuses/jumpsquat.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/common/src/opff/mod.rs
  fighters/common/src/opff/other.rs
Labels: bug, engine, semver:patch

#1901 Falco - fix Shine stall off respawn plat
  fighters/falco/src/status.rs
Labels: bug, semver:patch

#1913 WorkModule::count_down_int fix for updated signature
  fighters/bayonetta/src/status/attack.rs
  fighters/common/src/general_statuses/attack/attack.rs
  fighters/common/src/general_statuses/attack/attackdash.rs
  fighters/common/src/general_statuses/shield/guard_damage/exec.rs
  fighters/common/src/general_statuses/shield/guard_damage/main.rs
  fighters/common/src/shoto_status.rs
Labels: semver:patch

#1916 Implement Blast Attack
  dynamic/src/consts.rs
  fighters/kirby/src/status.rs
  fighters/kirby/src/status/sonic.rs
  fighters/sonic/src/acmd/specials.rs
  fighters/sonic/src/status.rs
  fighters/sonic/src/status/special_n.rs
  romfs/source/fighter/sonic/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1882 Extend Jump Cancels To Include USmash
  dynamic/src/ext.rs
  fighters/brave/src/opff.rs
  fighters/buddy/src/opff.rs
  fighters/chrom/src/opff.rs
  fighters/donkey/src/opff.rs
  fighters/edge/src/opff.rs
  fighters/falco/src/status/special_lw.rs
  fighters/fox/src/opff.rs
  fighters/fox/src/status/special_lw.rs
  fighters/gamewatch/src/opff.rs
  fighters/gekkouga/src/opff.rs
  fighters/ike/src/opff.rs
  fighters/inkling/src/opff.rs
  fighters/kirby/src/opff.rs
  fighters/koopa/src/opff.rs
  fighters/krool/src/opff.rs
  fighters/lucario/src/opff.rs
  fighters/lucas/src/opff.rs
  fighters/lucina/src/opff.rs
  fighters/miifighter/src/opff.rs
  fighters/miigunner/src/opff.rs
  fighters/miiswordsman/src/opff.rs
  fighters/miiswordsman/src/status.rs
  fighters/ness/src/opff.rs
  fighters/pichu/src/opff.rs
  fighters/pikachu/src/opff.rs
  fighters/pit/src/opff.rs
  fighters/pitb/src/opff.rs
  fighters/pzenigame/src/opff.rs
  fighters/robot/src/opff.rs
  fighters/rockman/src/opff.rs
  fighters/ryu/src/opff.rs
  fighters/sheik/src/opff.rs
  fighters/shizue/src/opff.rs
  fighters/sonic/src/status/special_s.rs
  fighters/szerosuit/src/opff.rs
  fighters/trail/src/opff.rs
  fighters/wolf/src/opff.rs
  fighters/wolf/src/status/special_lw.rs
  fighters/yoshi/src/opff.rs
Labels: engine, semver:patch

#1896 Various special refresh fixes
  fighters/diddy/src/status.rs
  fighters/dolly/src/status.rs
  fighters/elight/src/status.rs
  fighters/ganon/src/status.rs
  fighters/ken/src/status.rs
  fighters/murabito/src/status.rs
  fighters/pickel/src/status.rs
  fighters/plizardon/src/status.rs
  fighters/ryu/src/status.rs
Labels: bug, semver:patch

#1809 Minmin doubledragon
  dynamic/src/consts.rs
  fighters/tantan/src/acmd/other.rs
  fighters/tantan/src/acmd/smashes.rs
  fighters/tantan/src/acmd/specials.rs
  fighters/tantan/src/acmd/tilts.rs
  fighters/tantan/src/lib.rs
  fighters/tantan/src/opff.rs
  fighters/tantan/src/status.rs
  romfs/source/fighter/tantan/motion/body/motion_patch.yaml
  romfs/source/fighter/tantan/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1877 Remove fastfall from some specials
  fighters/buddy/src/opff.rs
  fighters/captain/src/opff.rs
  fighters/cloud/src/opff.rs
  fighters/diddy/src/opff.rs
  fighters/eflame/src/opff.rs
  fighters/elight/src/opff.rs
  fighters/fox/src/opff.rs
  fighters/kamui/src/opff.rs
  fighters/link/src/opff.rs
  fighters/luigi/src/opff.rs
  fighters/mariod/src/opff.rs
  fighters/mewtwo/src/opff.rs
  fighters/miiswordsman/src/opff.rs
  fighters/pacman/src/opff.rs
  fighters/palutena/src/opff.rs
  fighters/pfushigisou/src/opff.rs
  fighters/pikachu/src/opff.rs
  fighters/purin/src/opff.rs
  fighters/robin/src/opff.rs
  fighters/simon/src/opff.rs
  fighters/toonlink/src/opff.rs
  fighters/trail/src/opff.rs
  fighters/wiifit/src/opff.rs
  fighters/wolf/src/opff.rs
  fighters/younglink/src/opff.rs
Labels: bug, character change, semver:patch

#1854 Bowser - Inside Story Punch
  dynamic/src/consts.rs
  fighters/koopa/src/acmd/smashes.rs
  fighters/koopa/src/opff.rs
  romfs/source/fighter/koopa/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#1858 Steve - Crafting Table Rework
  dynamic/src/consts.rs
  fighters/pickel/src/lib.rs
  fighters/pickel/src/opff.rs
  romfs/source/fighter/pickel/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1870 Dedede fair rework
  fighters/dedede/src/acmd/aerials.rs
  romfs/source/fighter/dedede/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#1836 Mario PM Dair + Galaxy spin
  dynamic/src/consts.rs
  fighters/mario/src/acmd/aerials.rs
  fighters/mario/src/acmd/other.rs
  fighters/mario/src/acmd/specials.rs
  fighters/mario/src/opff.rs
  fighters/mario/src/status.rs
  romfs/source/fighter/mario/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#1829 Piranha Plant Changes pt 3
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/packun/src/acmd/aerials.rs
  fighters/packun/src/acmd/ground.rs
  fighters/packun/src/acmd/mod.rs
  fighters/packun/src/acmd/other.rs
  fighters/packun/src/acmd/smashes.rs
  fighters/packun/src/acmd/specials.rs
  fighters/packun/src/acmd/tilts.rs
  fighters/packun/src/lib.rs
  fighters/packun/src/opff.rs
  romfs/source/fighter/packun/motion/poisonbreath/motion_patch.yaml
  romfs/source/fighter/packun/motion/spikeball/motion_patch.yaml
  romfs/source/fighter/packun/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1910 Bowser adjustments
  fighters/koopa/src/acmd/aerials.rs
  fighters/koopa/src/acmd/ground.rs
  fighters/koopa/src/acmd/other.rs
  fighters/koopa/src/acmd/smashes.rs
  fighters/koopa/src/acmd/specials.rs
  fighters/koopa/src/acmd/throws.rs
  fighters/koopa/src/acmd/tilts.rs
  fighters/koopa/src/opff.rs
  fighters/koopa/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/koopa/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#1895 Dark Pit adjustments
  fighters/pitb/src/acmd/aerials.rs
  fighters/pitb/src/acmd/ground.rs
  fighters/pitb/src/acmd/other.rs
  fighters/pitb/src/acmd/smashes.rs
  fighters/pitb/src/acmd/specials.rs
  fighters/pitb/src/acmd/throws.rs
  fighters/pitb/src/acmd/tilts.rs
  fighters/pitb/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/pitb/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#1894 Pit adjustments
  fighters/pit/src/acmd/aerials.rs
  fighters/pit/src/acmd/ground.rs
  fighters/pit/src/acmd/other.rs
  fighters/pit/src/acmd/smashes.rs
  fighters/pit/src/acmd/specials.rs
  fighters/pit/src/acmd/throws.rs
  fighters/pit/src/acmd/tilts.rs
  fighters/pit/src/opff.rs
  fighters/pit/src/status/mod.rs
  fighters/pit/src/status/special_s.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/pit/motion/body/motion_patch.yaml
  romfs/source/fighter/pit/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1826 Add debug_draw support
  dynamic/src/util.rs
Labels: enhancement, semver:patch

#1912 Mii Swordfighter Warrior Wave Effect Adjustments
  fighters/miiswordsman/src/acmd/other.rs
  fighters/miiswordsman/src/acmd/specials.rs
  romfs/source/fighter/miiswordsman/param/vl.prcxml
Labels: aesthetics, semver:patch

#1922 Pit hotfix
  romfs/source/fighter/pit/motion/body/motion_patch.yaml
Labels: bug, semver:patch

#1925 Platdrop fastfall bugfix
  fighters/common/src/function_hooks/init_settings.rs
Labels: bug, engine, semver:patch

#1666 Lucario's New Aura
  dynamic/src/consts.rs
  dynamic/src/ui.rs
  fighters/common/src/function_hooks/aura.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/general_statuses/shield/guard_damage/init.rs
  fighters/lucario/src/acmd/aerials.rs
  fighters/lucario/src/acmd/ground.rs
  fighters/lucario/src/acmd/mod.rs
  fighters/lucario/src/acmd/other.rs
  fighters/lucario/src/acmd/smashes.rs
  fighters/lucario/src/acmd/specials.rs
  fighters/lucario/src/acmd/throws.rs
  fighters/lucario/src/acmd/tilts.rs
  fighters/lucario/src/lib.rs
  fighters/lucario/src/opff.rs
  fighters/lucario/src/status.rs
  fighters/lucario/src/status/attack_air.rs
  fighters/lucario/src/status/attack_hi4.rs
  fighters/lucario/src/status/special_hi.rs
  fighters/lucario/src/status/special_lw.rs
  fighters/lucario/src/status/special_n.rs
  fighters/lucario/src/status/special_s.rs
  romfs/source/fighter/lucario/motion/body/motion_patch.yaml
  romfs/source/fighter/lucario/param/hdr.xml
  romfs/source/fighter/lucario/param/vl.prcxml
  utils/src/ui.rs
  utils/src/ui/aura_meter.rs
Labels: character change, semver:patch, backroom approved, includes assets

#1918 Metaknight P+ Bair + animation/sfx tweaks
  fighters/metaknight/src/acmd/aerials.rs
  fighters/metaknight/src/acmd/smashes.rs
  romfs/source/fighter/metaknight/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#1927 Palutena bugfix
  fighters/palutena/src/status/special_n.rs
Labels: bug, semver:patch
