Repository HDR-Development/HewDraw-Remix, pull requests merged in 2023-06, with the labels that each got.

#1522 Lucas Grab Fix + Small Tweaks
  fighters/lucas/src/acmd/aerials.rs
  fighters/lucas/src/acmd/specials.rs
  fighters/lucas/src/acmd/throws.rs
  fighters/lucas/src/acmd/tilts.rs
Labels: aesthetics, character change, semver:patch, backroom approved

#1643 Dash attack input improvements
  fighters/common/src/general_statuses/dash.rs
Labels: engine, semver:patch

#1653 Install stage api callbacks only if TourneyConfig is valid
  utils/src/modules/param.rs
Labels: semver:patch

#1620 Give Bowser Jr. an ECB offset
  fighters/koopajr/src/status.rs
  romfs/source/fighter/koopajr/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1578 Remove PT Automatic Switch On Death
  fighters/pfushigisou/src/lib.rs
  fighters/pfushigisou/src/status.rs
Labels: character change, semver:patch, backroom approved

#1413 Robin Linking Improvements, UAir/DAir Levin Change, Throw FAF Decrease
  fighters/robin/src/acmd/aerials.rs
  fighters/robin/src/acmd/ground.rs
  fighters/robin/src/acmd/other.rs
  fighters/robin/src/acmd/smashes.rs
  fighters/robin/src/acmd/specials.rs
  fighters/robin/src/acmd/throws.rs
  fighters/robin/src/lib.rs
  romfs/source/fighter/reflet/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1543 ZSS Tweaks
  fighters/szerosuit/src/acmd/aerials.rs
  fighters/szerosuit/src/acmd/ground.rs
  fighters/szerosuit/src/acmd/other.rs
  fighters/szerosuit/src/acmd/smashes.rs
  fighters/szerosuit/src/acmd/specials.rs
  fighters/szerosuit/src/acmd/throws.rs
  fighters/szerosuit/src/acmd/tilts.rs
  fighters/szerosuit/src/lib.rs
  romfs/source/fighter/szerosuit/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1567 Mythra Side B Rework (Repost) + Neutral B backhit removed
  dynamic/src/consts.rs
  fighters/elight/src/acmd/specials.rs
  fighters/elight/src/opff.rs
Labels: aesthetics, character change, semver:patch, backroom approved, includes assets

#1591 Meter Sweep
  dynamic/src/consts.rs
  dynamic/src/modules/meter.rs
  fighters/common/src/opff/shotos.rs
  fighters/dolly/src/acmd/ground.rs
  fighters/dolly/src/acmd/smashes.rs
  fighters/dolly/src/acmd/specials.rs
  fighters/dolly/src/opff.rs
  fighters/ken/src/opff.rs
  fighters/pichu/src/acmd/smashes.rs
  fighters/pichu/src/acmd/specials.rs
  fighters/pichu/src/lib.rs
  fighters/pichu/src/opff.rs
  fighters/ryu/src/acmd/aerials.rs
  fighters/ryu/src/acmd/ground.rs
  fighters/ryu/src/acmd/smashes.rs
  fighters/ryu/src/acmd/specials.rs
  fighters/ryu/src/opff.rs
  utils/src/modules/meter.rs
Labels: enhancement, character change, engine, semver:patch, backroom approved

#1519 Dark Pit - nair rework, shine jc during orbitar release
  fighters/pitb/src/acmd/aerials.rs
  fighters/pitb/src/opff.rs
Labels: character change, semver:patch, backroom approved

#1609 Dins Fire - Further Review/Revert
  fighters/zelda/src/acmd/other.rs
  romfs/source/fighter/zelda/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1611 Falcon Kick/Wizard's Foot/Power Thrust adjustments
  fighters/captain/src/acmd/specials.rs
  fighters/captain/src/lib.rs
  fighters/captain/src/status/mod.rs
  fighters/captain/src/status/special_lw.rs
  fighters/common/src/function_hooks/edge_slipoffs.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/ganon/src/acmd/specials.rs
  fighters/ganon/src/status/special_lw.rs
  fighters/miiswordsman/src/status.rs
  romfs/source/fighter/miiswordsman/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1662 Robin Bug Fix: Tilt inputs correctly use bronze sword
  fighters/robin/src/acmd/ground.rs
  fighters/robin/src/lib.rs
  fighters/robin/src/status.rs
Labels: bug, semver:patch

#1331 Bayonetta Rework
  dynamic/src/consts.rs
  fighters/bayonetta/src/acmd/aerials.rs
  fighters/bayonetta/src/acmd/ground.rs
  fighters/bayonetta/src/acmd/other.rs
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/acmd/throws.rs
  fighters/bayonetta/src/acmd/tilts.rs
  fighters/bayonetta/src/opff.rs
  fighters/bayonetta/src/status.rs
  romfs/source/fighter/bayonetta/param/vl.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1517 Link Adjustments
  fighters/common/src/function_hooks/ledges.rs
  fighters/link/src/acmd/aerials.rs
  fighters/link/src/acmd/ground.rs
  fighters/link/src/acmd/other.rs
  fighters/link/src/acmd/smashes.rs
  fighters/link/src/acmd/specials.rs
  fighters/link/src/acmd/tilts.rs
  fighters/link/src/opff.rs
  fighters/link/src/status.rs
  romfs/source/fighter/link/param/hdr.xml
  romfs/source/fighter/link/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1626 MK Rewrite
  fighters/metaknight/src/acmd/aerials.rs
  fighters/metaknight/src/acmd/ground.rs
  fighters/metaknight/src/acmd/smashes.rs
  fighters/metaknight/src/acmd/specials.rs
  fighters/metaknight/src/acmd/throws.rs
  fighters/metaknight/src/acmd/tilts.rs
  fighters/metaknight/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/metaknight/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1633 Captain Falcon Tweaks
  fighters/captain/src/acmd/aerials.rs
  fighters/captain/src/acmd/ground.rs
  fighters/captain/src/acmd/smashes.rs
  fighters/captain/src/acmd/specials.rs
  fighters/captain/src/acmd/tilts.rs
Labels: character change, semver:patch, backroom approved

#1493 Joker Gameplay Adjustments
  fighters/jack/src/acmd/aerials.rs
  fighters/jack/src/acmd/ground.rs
  fighters/jack/src/acmd/smashes.rs
  fighters/jack/src/acmd/specials.rs
  fighters/jack/src/acmd/tilts.rs
  fighters/jack/src/opff.rs
  romfs/source/fighter/jack/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1637 Kirby adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/energy/motion.rs
  fighters/kirby/src/acmd/aerials.rs
  fighters/kirby/src/acmd/ground.rs
  fighters/kirby/src/acmd/smashes.rs
  fighters/kirby/src/acmd/specials.rs
  fighters/kirby/src/acmd/throws.rs
  fighters/kirby/src/acmd/tilts.rs
  fighters/kirby/src/lib.rs
  fighters/kirby/src/opff.rs
  fighters/kirby/src/status.rs
  fighters/kirby/src/status/special_hi_h.rs
Labels: character change, semver:patch, backroom approved, includes assets

#1556 Duck Hunt Adjustments
  fighters/duckhunt/src/acmd/aerials.rs
  fighters/duckhunt/src/acmd/ground.rs
  fighters/duckhunt/src/acmd/other.rs
  fighters/duckhunt/src/acmd/specials.rs
  fighters/duckhunt/src/acmd/tilts.rs
  fighters/duckhunt/src/lib.rs
  fighters/duckhunt/src/status/mod.rs
  fighters/duckhunt/src/status/special_n.rs
  fighters/duckhunt/src/status/special_s.rs
  romfs/source/fighter/duckhunt/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1617 Ken's Overhaul
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/function_hooks/shotos.rs
  fighters/common/src/opff/shotos.rs
  fighters/ken/src/acmd/aerials.rs
  fighters/ken/src/acmd/finals.rs
  fighters/ken/src/acmd/ground.rs
  fighters/ken/src/acmd/mod.rs
  fighters/ken/src/acmd/other.rs
  fighters/ken/src/acmd/smashes.rs
  fighters/ken/src/acmd/specials.rs
  fighters/ken/src/acmd/throws.rs
  fighters/ken/src/acmd/tilts.rs
  fighters/ken/src/opff.rs
  fighters/ken/src/status.rs
  fighters/ryu/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/ken/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1647 Yoshi - P+ ftilt & upB slipoff
  fighters/common/src/function_hooks/edge_slipoffs.rs
  fighters/yoshi/src/acmd/tilts.rs
Labels: character change, semver:patch, backroom approved, includes assets

#1652 Recovery touchups
  fighters/common/src/function_hooks/edge_slipoffs.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/diddy/src/opff.rs
  fighters/diddy/src/status.rs
  fighters/diddy/src/status/special_hi.rs
  fighters/edge/src/acmd/specials.rs
  fighters/falco/src/status/special_hi.rs
  fighters/fox/src/status/special_hi.rs
  fighters/ganon/src/acmd/specials.rs
  fighters/littlemac/src/acmd/specials.rs
  fighters/littlemac/src/status.rs
  fighters/littlemac/src/status/special_hi.rs
  fighters/luigi/src/opff.rs
  fighters/metaknight/src/acmd/specials.rs
  fighters/pacman/src/opff.rs
  fighters/pacman/src/status/special_s.rs
  fighters/rosetta/src/opff.rs
  fighters/rosetta/src/status.rs
  fighters/rosetta/src/status/special_hi.rs
  fighters/sheik/src/opff.rs
  fighters/wario/src/acmd/specials.rs
  fighters/wario/src/status/special_hi.rs
  fighters/wolf/src/acmd/specials.rs
  fighters/wolf/src/opff.rs
  fighters/wolf/src/status/special_hi.rs
  romfs/config.json
  romfs/source/fighter/captain/param/vl.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/edge/param/hdr.xml
  romfs/source/fighter/edge/param/vl.prcxml
  romfs/source/fighter/falco/param/vl.prcxml
  romfs/source/fighter/fox/param/vl.prcxml
  romfs/source/fighter/ganon/param/hdr.xml
  romfs/source/fighter/ganon/param/vl.prcxml
  romfs/source/fighter/link/param/vl.prcxml
  romfs/source/fighter/lucas/param/vl.prcxml
  romfs/source/fighter/luigi/param/hdr.xml
  romfs/source/fighter/ness/param/vl.prcxml
  romfs/source/fighter/pacman/param/hdr.xml
  romfs/source/fighter/rosetta/param/vl.prcxml
  romfs/source/fighter/wolf/param/vl.prcxml
  utils/agent_params.txt
  utils/rom_watch.txt
Labels: bug, character change, semver:patch, backroom approved

#1660 Cloud - usmash hitlag reversion
  fighters/cloud/src/acmd/smashes.rs
Labels: aesthetics, semver:patch

#1562 Sephiroth Uptilt Hotfix
  fighters/edge/src/acmd/tilts.rs
Labels: bug, semver:patch

#1671 Duck Hunt - Clay Pigeon bugfix
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/duckhunt/src/acmd/specials.rs
  fighters/duckhunt/src/status/special_n.rs
  fighters/duckhunt/src/status/special_s.rs
Labels: bug, semver:patch

#1629 Wolf Adjustments
  fighters/wolf/src/acmd/aerials.rs
  fighters/wolf/src/acmd/ground.rs
  fighters/wolf/src/acmd/other.rs
  fighters/wolf/src/acmd/smashes.rs
  fighters/wolf/src/acmd/specials.rs
  fighters/wolf/src/acmd/tilts.rs
  fighters/wolf/src/opff.rs
  fighters/wolf/src/status/special_s.rs
Labels: character change, semver:patch, backroom approved, includes assets

#1657 Changed Weapon Catch Behavior
  fighters/common/src/function_hooks/mod.rs
  fighters/eflame/src/lib.rs
  fighters/krool/src/lib.rs
  fighters/krool/src/vtable_hook.rs
Labels: character change, semver:patch, backroom approved, includes assets

#1654 MinMin HotFix
  fighters/tantan/src/acmd/smashes.rs
  fighters/tantan/src/status.rs
Labels: bug, semver:patch

#1641 Hero followup adjustments
  fighters/brave/src/acmd/specials.rs
  fighters/brave/src/opff.rs
  romfs/source/fighter/brave/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1640 Manual parry aesthetic adjustments
  fighters/common/src/general_statuses/run.rs
  fighters/common/src/general_statuses/shield/guard_damage/init.rs
  fighters/common/src/general_statuses/shield/guard_off/main.rs
  fighters/dolly/src/status.rs
  fighters/ken/src/acmd/other.rs
  fighters/ken/src/status.rs
  fighters/ryu/src/acmd/other.rs
  fighters/ryu/src/status.rs
  fighters/yoshi/src/acmd/other.rs
  fighters/yoshi/src/status.rs
Labels: aesthetics, engine, semver:patch

#1674 Fix g2a momentum transfer for some characters
  fighters/common/src/general_statuses/jump.rs
Labels: bug, engine, semver:patch

#1661 Rosalina teleport adjustment
  dynamic/src/consts.rs
  fighters/rosetta/src/opff.rs
Labels: character change, semver:patch, backroom approved

#1645 Mii Brawler followup adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/miifighter/src/acmd/specials.rs
  fighters/miifighter/src/lib.rs
  fighters/miifighter/src/opff.rs
  romfs/config.json
  romfs/source/fighter/miifighter/param/hdr.xml
  utils/agent_params.txt
  utils/rom_watch.txt
Labels: character change, semver:patch, backroom approved

#1658 Fix smash stick up out of dash
  fighters/common/src/general_statuses/dash.rs
Labels: bug, engine, semver:patch

#1632 Megaman Minor Buffs
  fighters/rockman/src/acmd/aerials.rs
  romfs/source/fighter/rockman/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1548 Bowser Jr Re-evaluation
  fighters/koopajr/src/acmd/aerials.rs
  fighters/koopajr/src/acmd/ground.rs
  fighters/koopajr/src/acmd/specials.rs
  fighters/koopajr/src/acmd/throws.rs
  fighters/koopajr/src/acmd/tilts.rs
Labels: character change, semver:patch, backroom approved

#1683 Rosalina teleport hotfix
  fighters/rosetta/src/opff.rs
Labels: bug, semver:patch

#1630 Port of AParticularUser's PM Snake moveset & various nerfs
  dynamic/src/consts.rs
  fighters/snake/src/acmd/aerials.rs
  fighters/snake/src/acmd/ground.rs
  fighters/snake/src/acmd/other.rs
  fighters/snake/src/acmd/smashes.rs
  fighters/snake/src/acmd/specials.rs
  fighters/snake/src/acmd/tilts.rs
  fighters/snake/src/lib.rs
  fighters/snake/src/opff.rs
  fighters/snake/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/snake/param/vl.prcxml
Labels: aesthetics, character change, semver:patch, backroom approved, includes assets

#1679 Yoshi/Mewtwo - fix DJC override aerial arcs
  fighters/mewtwo/src/acmd/aerials.rs
  fighters/yoshi/src/acmd/aerials.rs
Labels: bug, semver:patch

#1689 Cappy hitbox
  fighters/mario/src/acmd/other.rs
Labels: character change, semver:patch, backroom approved

#1677 Isabelle mine nerf
  romfs/source/fighter/shizue/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1668 Small Pit/DPit Fixes
  fighters/pit/src/acmd/aerials.rs
  fighters/pitb/src/acmd/aerials.rs
  fighters/pitb/src/acmd/specials.rs
Labels: character change, semver:patch, backroom approved

#1685 Plant Adjustments
  fighters/packun/src/acmd/ground.rs
  fighters/packun/src/acmd/other.rs
  fighters/packun/src/acmd/specials.rs
  fighters/packun/src/opff.rs
Labels: character change, semver:patch, backroom approved, includes assets

#1656 Diddy - implement Popgun cancel animation
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/diddy/src/acmd/specials.rs
  fighters/diddy/src/lib.rs
  fighters/diddy/src/opff.rs
  fighters/diddy/src/status.rs
  fighters/diddy/src/status/special_n.rs
  fighters/src/lib.rs
Labels: enhancement, semver:patch

#1670 Villager Small Adjustments
  dynamic/src/consts.rs
  fighters/murabito/src/acmd/aerials.rs
  fighters/murabito/src/acmd/other.rs
  fighters/murabito/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/murabito/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1642 Gordo redesign and dedede adjustments
  fighters/dedede/src/acmd/aerials.rs
  fighters/dedede/src/acmd/other.rs
  fighters/dedede/src/acmd/smashes.rs
  fighters/dedede/src/acmd/specials.rs
  fighters/dedede/src/acmd/tilts.rs
  fighters/dedede/src/opff.rs
  romfs/source/fighter/dedede/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1383 DK Dspecial replaced entirely with barrel mechanics
  dynamic/Cargo.toml
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/function_hooks/edge_slipoffs.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/misc.rs
  fighters/donkey/src/acmd/aerials.rs
  fighters/donkey/src/acmd/ground.rs
  fighters/donkey/src/acmd/other.rs
  fighters/donkey/src/acmd/specials.rs
  fighters/donkey/src/acmd/throws.rs
  fighters/donkey/src/acmd/tilts.rs
  fighters/donkey/src/lib.rs
  fighters/donkey/src/opff.rs
  fighters/donkey/src/status.rs
  fighters/donkey/src/status/cargo_carry.rs
  fighters/donkey/src/status/item_throw_heavy.rs
  fighters/donkey/src/status/shoulder.rs
  fighters/donkey/src/status/special_lw.rs
  fighters/donkey/src/status/super_lift.rs
  romfs/source/fighter/donkey/param/vl.prcxml
  romfs/source/item/barrel/param/param.prcxml
  romfs/source/item/common/param/param.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#1669 Small Falco Adjustments
  fighters/falco/src/acmd/aerials.rs
  fighters/falco/src/acmd/ground.rs
  fighters/falco/src/acmd/other.rs
  fighters/falco/src/acmd/tilts.rs
Labels: character change, semver:patch, backroom approved

#1672 Ness - single hit uair
  fighters/ness/src/acmd/aerials.rs
  fighters/ness/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#1675 Byleth Tone-Down
  fighters/master/src/acmd/aerials.rs
  fighters/master/src/acmd/ground.rs
  fighters/master/src/acmd/specials.rs
  fighters/master/src/acmd/throws.rs
  fighters/master/src/acmd/tilts.rs
Labels: character change, semver:patch, backroom approved

#1676 Small Ewgf Rework
  fighters/demon/src/acmd/specials.rs
Labels: character change, semver:patch, backroom approved

#1682 Pyra - remove added hitstun on specials
  fighters/eflame/src/acmd/other.rs
  fighters/eflame/src/acmd/specials.rs
Labels: character change, semver:patch, backroom approved

#1692 Recovery adjustments again again
  fighters/common/src/function_hooks/edge_slipoffs.rs
  fighters/edge/src/lib.rs
  fighters/edge/src/status/mod.rs
  fighters/edge/src/status/special_hi.rs
  fighters/ike/src/acmd/specials.rs
  fighters/ike/src/opff.rs
  fighters/ike/src/status.rs
  fighters/ike/src/status/special_s.rs
  fighters/plizardon/src/opff.rs
  fighters/ridley/src/acmd/specials.rs
  fighters/sheik/src/lib.rs
  fighters/sheik/src/status/mod.rs
  fighters/sheik/src/status/special_hi.rs
  romfs/config.json
  romfs/source/fighter/donkey/param/hdr.xml
  romfs/source/fighter/donkey/param/vl.prcxml
  romfs/source/fighter/eflame/param/vl.prcxml
  romfs/source/fighter/miiswordsman/param/vl.prcxml
  romfs/source/fighter/sheik/param/hdr.xml
  utils/agent_params.txt
  utils/rom_watch.txt
Labels: character change, semver:patch, backroom approved

#1686 Meta Knight - Brawl jab
  fighters/metaknight/src/acmd/ground.rs
  fighters/metaknight/src/opff.rs
  fighters/metaknight/src/status/attack_100.rs
  fighters/metaknight/src/status/mod.rs
Labels: character change, semver:patch, backroom approved, includes assets

#1701 Bowser Jr. - bair visual adjustment
  fighters/koopajr/src/acmd/aerials.rs
Labels: aesthetics, semver:patch

#1688 Incineroar small adjustments
  fighters/gaogaen/src/acmd/specials.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#1705 Metaknight Followups
  fighters/metaknight/src/acmd/ground.rs
  fighters/metaknight/src/acmd/tilts.rs
  fighters/metaknight/src/opff.rs
Labels: bug, semver:patch

#1691 Inkling Up B Landing Lag Reduction
  romfs/source/fighter/inkling/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#1712 Tiny Snake adjustments
  fighters/snake/src/acmd/other.rs
  fighters/snake/src/acmd/smashes.rs
  fighters/snake/src/acmd/specials.rs
Labels: character change, semver:patch, backroom approved

#1713 Meta Knight hotfix
  fighters/metaknight/src/acmd/aerials.rs
  fighters/metaknight/src/acmd/ground.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#1678 Manual parry bugfixes/refinements
  fighters/common/src/function_hooks/controls.rs
  fighters/common/src/general_statuses/shield/guard_damage/pre.rs
  fighters/common/src/opff/other.rs
  fighters/yoshi/src/status.rs
  plugin/src/lua.rs
Labels: bug, engine, crash, semver:patch

#1687 Sonic Side Special - Spin Boost
  dynamic/src/consts.rs
  fighters/sonic/src/acmd/specials.rs
  fighters/sonic/src/status.rs
  fighters/sonic/src/status/dash.rs
  fighters/sonic/src/status/special_lw_hold.rs
  fighters/sonic/src/status/special_s.rs
  fighters/sonic/src/status/special_s_dash.rs
Labels: character change, semver:patch, backroom approved, includes assets

#1714 Reduce screenshake intensity
  fighters/common/src/function_hooks/camera.rs
Labels: aesthetics, engine, semver:patch

#1721 Update Box Fair ACMD
  fighters/gamewatch/src/acmd/aerials.rs
  fighters/gamewatch/src/opff.rs
Labels: aesthetics, semver:patch, includes assets

#1719 Spin Boost Adjustments
  dynamic/src/consts.rs
  fighters/sonic/src/acmd/specials.rs
  fighters/sonic/src/status/special_s.rs
Labels: character change, semver:patch, backroom approved

#1708 Tumble knockback bugfixes
  fighters/common/src/function_hooks/collision.rs
  fighters/common/src/function_hooks/transition.rs
  fighters/common/src/general_statuses/damagefall.rs
  fighters/common/src/opff/tech.rs
Labels: bug, engine, semver:patch
