Repository HDR-Development/HewDraw-Remix, pull requests merged in 2023-04, with the labels that each got.

#1511 Kazuya - fix Hell Sweep crash
  fighters/demon/src/opff.rs
Labels: crash, semver:patch

#1512 Simple fixes
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/dash.rs
  fighters/common/src/opff/other.rs
Labels: engine, semver:patch

#1514 Revert "Simple fixes"
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/dash.rs
  fighters/common/src/opff/other.rs
Labels: engine, semver:patch

#1497 Inkling/K. Rool/Plant/Squirtle DACUS nerfs
  fighters/inkling/src/acmd/ground.rs
  fighters/krool/src/acmd/ground.rs
  fighters/packun/src/acmd/ground.rs
  fighters/pzenigame/src/acmd/ground.rs
Labels: character change, semver:patch

#1521 Fix Isa lloid fr
  fighters/common/src/function_hooks/mod.rs
  fighters/shizue/src/status/clayrocket.rs
Labels: bug, semver:patch

#1472 Fox up air hotfix
  fighters/fox/src/acmd/aerials.rs
Labels: character change, semver:patch, backroom approved

#1504 Fix remaining issues with projectiles despawning on plats
  fighters/common/src/function_hooks/collision.rs
  romfs/source/fighter/pikachu/param/vl.prcxml
Labels: engine, semver:patch

#1545 Fix dash grab jostle
  fighters/common/src/general_statuses/catch/catchdash.rs
Labels: bug, engine, semver:patch

#1530 Ike quickdraw bug fix
  fighters/ike/src/acmd/specials.rs
Labels: bug, aesthetics, semver:patch

#1547 Little Mac - grounded Jolt Haymaker bugfix
  fighters/littlemac/src/status.rs
  fighters/littlemac/src/status/special_s.rs
Labels: bug, semver:patch

#1550 Fix item tosses
  fighters/common/src/function_hooks/mod.rs
Labels: bug, engine, semver:patch

#1554 Fix roll/getup roll end momentum
  fighters/common/src/general_statuses/downstand.rs
  fighters/common/src/general_statuses/escape.rs
  fighters/common/src/general_statuses/mod.rs
Labels: bug, engine, semver:patch

#1569 Massive UI Overhaul
  romfs/source/ui/script/menu/main/main_menu_layer_other.lua
  romfs/source/ui/script/menu/main/main_menu_layer_top.lua
Labels: enhancement, aesthetics, semver:feature

#1537 Young Link Dash Attack Rumble
  fighters/younglink/src/acmd/ground.rs
Labels: aesthetics, semver:patch
