Repository HDR-Development/HewDraw-Remix, pull requests merged in 2023-12, with the labels that each got.

#2099 Remove Ganondorf
  romfs/source/ui/param/database/ui_chara_db.prcxml
Labels: bug, enhancement, good first issue, infrastructure, aesthetics, character change, engine, crash, semver:patch, backroom approved

#2097 Remove ledge option intangibility staling
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#2066 Dark Samus up tilt hotfix
  fighters/samusd/src/acmd/tilts.rs
Labels: bug, semver:patch

#2109 Fixed Flip Kick Logic
  fighters/diddy/src/status/special_s_jump.rs
Labels: bug, semver:patch

#2096 Global FAF ledgegrab
  fighters/common/src/opff/ledges.rs
  fighters/common/src/opff/mod.rs
Labels: engine, semver:patch

#2063 Ledgegrab box adjustments
  romfs/source/fighter/captain/param/hdr.xml
  romfs/source/fighter/falco/param/vl.prcxml
  romfs/source/fighter/fox/param/vl.prcxml
Labels: semver:patch

#2073 Robin adjustments
  fighters/common/src/opff/floats.rs
  fighters/reflet/src/acmd/aerials.rs
  fighters/reflet/src/acmd/tilts.rs
  romfs/source/fighter/reflet/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#2089 Gnw adjustments: Parachute Edition
  dynamic/src/consts.rs
  fighters/gamewatch/src/acmd/aerials.rs
  fighters/gamewatch/src/acmd/other.rs
  fighters/gamewatch/src/acmd/specials.rs
  fighters/gamewatch/src/acmd/tilts.rs
  fighters/gamewatch/src/opff.rs
  fighters/gamewatch/src/status.rs
  fighters/gamewatch/src/status/landing_attack_air.rs
  fighters/gamewatch/src/status/special_hi.rs
  fighters/gamewatch/src/status/special_hi_open.rs
  romfs/source/fighter/gamewatch/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#2090 Mario recovery bugfix/adjustments
  fighters/mario/src/acmd/specials.rs
  fighters/mario/src/lib.rs
  fighters/mario/src/opff.rs
  romfs/source/fighter/mario/param/vl.prcxml
Labels: bug, character change, semver:patch, backroom approved

#2087 Ganondorf adjustments
  fighters/ganon/src/acmd/specials.rs
  fighters/ganon/src/acmd/tilts.rs
  romfs/source/fighter/common/param/common.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2105 Revert "Remove Ganondorf"
  romfs/source/ui/param/database/ui_chara_db.prcxml
Labels: character change, semver:patch, stages, backroom approved

#2083 Make characters shut the fuck up
  dynamic/Cargo.toml
  dynamic/src/lib.rs
  dynamic/src/se.rs
  dynamic/src/util.rs
  fighters/common/src/function_hooks/sound.rs
Labels: aesthetics, semver:patch

#2098 Krool adjustments
  dynamic/src/consts.rs
  fighters/krool/src/acmd/aerials.rs
  fighters/krool/src/acmd/ground.rs
  fighters/krool/src/acmd/other.rs
  fighters/krool/src/acmd/specials.rs
  fighters/krool/src/lib.rs
  fighters/krool/src/opff.rs
  fighters/krool/src/status.rs
  fighters/krool/src/status/special_hi.rs
  fighters/krool/src/status/special_lw.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/krool/motion/body/motion_patch.yaml
  romfs/source/fighter/krool/param/hdr.xml
  romfs/source/fighter/krool/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2091 Mii Brawler: Soaring Axe Kick rework
  fighters/miifighter/src/acmd/specials.rs
  romfs/source/fighter/miifighter/param/hdr.xml
  romfs/source/fighter/miifighter/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2100 Revert Hero actionability
  fighters/brave/src/opff.rs
Labels: character change, semver:patch, backroom approved

#2111 Krool hotfix
  fighters/krool/src/status/special_hi.rs
Labels: bug, crash, semver:patch

#2072 Ganon Float Changes
  fighters/ganon/src/status/special_n.rs
  fighters/ganon/src/status/special_n_float.rs
  fighters/kirby/src/status/ganon_special_n.rs
  fighters/kirby/src/status/ganon_special_n_float.rs
Labels: bug, character change, semver:patch, backroom approved

#2101 Zelda Shorten Telecancel Clear Buffer Fix
  fighters/zelda/src/opff.rs
Labels: bug, semver:patch

#2107 Kirby NeutralB Bugfixes
  fighters/common/src/function_hooks/is_flag.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
Labels: bug, semver:patch

#2110 Jumpsquat adjustments
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#2085 Paisy - remove sideB fastfall
  fighters/daisy/src/opff.rs
  fighters/peach/src/opff.rs
Labels: character change, semver:patch

#2093 Marth - Smash 4 jab
  fighters/marth/src/acmd/ground.rs
Labels: character change, semver:patch, backroom approved, includes assets

#2080 Add sound effect to stage strike
  romfs/source/ui/script_patch/common/stage_select_actor3.lua
Labels: aesthetics, semver:patch

#2118 Pikachu adjustments
  dynamic/src/consts.rs
  fighters/pichu/src/opff.rs
  fighters/pikachu/src/acmd/aerials.rs
  fighters/pikachu/src/acmd/ground.rs
  fighters/pikachu/src/acmd/other.rs
  fighters/pikachu/src/acmd/smashes.rs
  fighters/pikachu/src/acmd/throws.rs
  fighters/pikachu/src/acmd/tilts.rs
  fighters/pikachu/src/opff.rs
  romfs/source/fighter/pikachu/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2126 Steve - follow-up tweaks
  fighters/pickel/src/acmd/aerials.rs
  fighters/pickel/src/acmd/tilts.rs
Labels: character change, semver:patch, backroom approved

#2125 Isabelle adjustments
  dynamic/src/consts.rs
  fighters/shizue/src/acmd/other.rs
  fighters/shizue/src/acmd/specials.rs
  fighters/shizue/src/lib.rs
  fighters/shizue/src/opff.rs
  romfs/source/fighter/shizue/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#2055 Plant Changes pt. 4
  dynamic/src/consts.rs
  fighters/packun/src/acmd/aerials.rs
  fighters/packun/src/acmd/ground.rs
  fighters/packun/src/acmd/mod.rs
  fighters/packun/src/acmd/other.rs
  fighters/packun/src/acmd/smashes.rs
  fighters/packun/src/acmd/specials.rs
  fighters/packun/src/acmd/throws.rs
  fighters/packun/src/acmd/tilts.rs
  fighters/packun/src/opff.rs
  fighters/packun/src/status.rs
  fighters/packun/src/status/attack_s4.rs
  fighters/packun/src/status/special_s.rs
  romfs/source/fighter/packun/motion/body/motion_patch.yaml
  romfs/source/fighter/packun/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2127 Peach Dash Attack Linking Improvement
  fighters/peach/src/acmd/ground.rs
Labels: character change, semver:patch, backroom approved

#2128 Allow parry during runbrake
  fighters/common/src/general_statuses/run.rs
Labels: engine, semver:patch

#2129 K Rool - Up special visual adjustments
  fighters/krool/src/acmd/specials.rs
  fighters/krool/src/status/special_hi.rs
  romfs/source/fighter/krool/motion/backpack/motion_patch.yaml
  romfs/source/fighter/krool/motion/body/motion_patch.yaml
Labels: aesthetics, semver:patch, includes assets

#2103 Joker Adjustments
  dynamic/src/consts.rs
  fighters/jack/src/acmd/aerials.rs
  fighters/jack/src/acmd/ground.rs
  fighters/jack/src/acmd/other.rs
  fighters/jack/src/acmd/specials.rs
  fighters/jack/src/acmd/tilts.rs
  fighters/jack/src/opff.rs
  romfs/source/fighter/jack/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#2133 Fix parry GFX
  fighters/common/src/general_statuses/shield/guard_damage/main.rs
Labels: bug, aesthetics, semver:patch

#2135 Arsene BAIR Hotfix
  fighters/jack/src/acmd/aerials.rs
Labels: bug, semver:patch

#2134 Bowser Jr. - upB airdodge lockout
  fighters/common/src/function_hooks/change_status.rs
Labels: character change, semver:patch, backroom approved

#2004 Palutena changes pt. 2
  fighters/common/src/function_hooks/transition.rs
  fighters/palutena/src/acmd/aerials.rs
  fighters/palutena/src/acmd/ground.rs
  fighters/palutena/src/acmd/other.rs
  fighters/palutena/src/acmd/smashes.rs
  fighters/palutena/src/acmd/specials.rs
  fighters/palutena/src/acmd/tilts.rs
  fighters/palutena/src/lib.rs
  fighters/palutena/src/opff.rs
  romfs/source/fighter/palutena/motion/body/motion_patch.yaml
  romfs/source/fighter/palutena/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#2132 Banjo nerfs
  fighters/buddy/src/acmd/aerials.rs
  fighters/buddy/src/acmd/tilts.rs
Labels: aesthetics, semver:patch

#2138 Duck Hunt Hazards On
  fighters/common/src/function_hooks/stage_hazards.rs
Labels: semver:patch

#2124 Small Fixes
  dynamic/src/ui.rs
  fighters/dolly/src/opff.rs
  fighters/donkey/src/acmd/tilts.rs
  fighters/gamewatch/src/acmd/specials.rs
  fighters/gamewatch/src/opff.rs
  fighters/gamewatch/src/status/special_hi_open.rs
  fighters/gaogaen/src/acmd/smashes.rs
  fighters/kirby/src/acmd/specials.rs
  fighters/kirby/src/status/ganon_special_n_float.rs
  fighters/krool/src/acmd/smashes.rs
  fighters/marth/src/acmd/aerials.rs
  fighters/miifighter/src/acmd/specials.rs
  fighters/packun/src/acmd/specials.rs
  fighters/packun/src/acmd/tilts.rs
  fighters/packun/src/opff.rs
  fighters/peach/src/acmd/ground.rs
  fighters/pichu/src/acmd/specials.rs
  fighters/pikachu/src/acmd/specials.rs
  fighters/robot/src/acmd/aerials.rs
  fighters/robot/src/acmd/specials.rs
  fighters/samus/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  utils/src/ui.rs
  utils/src/ui/ex_meter.rs
  utils/src/ui/ff_meter.rs
  utils/src/ui/power_board.rs
Labels: bug, aesthetics, semver:patch

#2139 Remove NSpecial 1f Parry Forgiveness
  dynamic/src/consts.rs
  fighters/common/src/opff/other.rs
  fighters/lucario/src/opff.rs
  fighters/lucario/src/status/special_n.rs
Labels: bug, engine, semver:patch

#2142 Plant Changes Pt. 4.1
  fighters/packun/src/acmd/aerials.rs
Labels: semver:patch

#2144 Mega Man Adjustments
  fighters/rockman/src/acmd/aerials.rs
  fighters/rockman/src/acmd/other.rs
  fighters/rockman/src/vtable_hook.rs
Labels: character change, semver:patch, backroom approved

#2143 Fix Richter crouching ftilt
  fighters/richter/src/acmd/tilts.rs
  fighters/richter/src/status/attacks3.rs
  fighters/simon/src/status/attacks3.rs
Labels: bug, semver:patch

#2146 Small Things
  fighters/krool/src/status/special_hi.rs
  fighters/rockman/src/opff.rs
Labels: bug, semver:patch

#2147 Update whitespace
  fighters/mario/src/opff.rs
Labels: semver:patch
