Repository HDR-Development/HewDraw-Remix, pull requests merged in 2024-06, with the labels that each got.

#2426 Joker touchups
  fighters/jack/src/acmd/tilts.rs
  fighters/jack/src/opff.rs
  fighters/jack/src/status/mod.rs
  fighters/jack/src/status/special_lw.rs
Labels: character change, semver:patch, backroom approved

#2430 FGCs Specials Hotfix
  fighters/common/src/function_hooks/finals.rs
  romfs/source/fighter/common/param/common.prcxml
Labels: bug, engine, semver:patch

#2394 Lucas Effect Compatibility Fix
  fighters/lucas/src/acmd/specials.rs
Labels: aesthetics, semver:patch, includes assets

#2434 Even more rumble fixes
  fighters/buddy/src/acmd/ground.rs
  fighters/chrom/src/acmd/specials.rs
  fighters/edge/src/acmd/ground.rs
  fighters/edge/src/acmd/tilts.rs
  fighters/metaknight/src/acmd/aerials.rs
  fighters/pikmin/src/acmd/aerials.rs
  fighters/pikmin/src/acmd/tilts.rs
  fighters/richter/src/acmd/aerials.rs
  fighters/richter/src/acmd/ground.rs
  fighters/roy/src/acmd/aerials.rs
  fighters/roy/src/acmd/specials/special_s3.rs
  fighters/ryu/src/acmd/ground.rs
  fighters/ryu/src/acmd/tilts.rs
Labels: bug, semver:patch

#2391 Zelda Tweaks + Teleports
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/energy/stop.rs
  fighters/mewtwo/src/opff.rs
  fighters/palutena/src/opff.rs
  fighters/sheik/src/acmd/specials.rs
  fighters/sheik/src/opff.rs
  fighters/zelda/src/acmd/aerials.rs
  fighters/zelda/src/acmd/ground.rs
  fighters/zelda/src/acmd/other.rs
  fighters/zelda/src/acmd/specials.rs
  fighters/zelda/src/acmd/throws.rs
  fighters/zelda/src/acmd/tilts.rs
  fighters/zelda/src/dein/acmd.rs
  fighters/zelda/src/dein/status.rs
  fighters/zelda/src/dein_s/acmd.rs
  fighters/zelda/src/opff.rs
  fighters/zelda/src/phantom/acmd.rs
  fighters/zelda/src/phantom/opff.rs
  fighters/zelda/src/phantom/status.rs
  fighters/zelda/src/status/mod.rs
  fighters/zelda/src/status/special_hi.rs
  romfs/source/fighter/zelda/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#2440 Landing Lag Followup Adjustments
  fighters/daisy/src/acmd/aerials.rs
  fighters/dedede/src/acmd/aerials.rs
  fighters/duckhunt/src/acmd/aerials.rs
  fighters/elight/src/acmd/aerials.rs
  fighters/falco/src/acmd/aerials.rs
  fighters/fox/src/acmd/aerials.rs
  fighters/gamewatch/src/acmd/aerials.rs
  fighters/ganon/src/acmd/aerials.rs
  fighters/gekkouga/src/acmd/aerials.rs
  fighters/inkling/src/acmd/aerials.rs
  fighters/jack/src/acmd/aerials.rs
  fighters/kamui/src/acmd/aerials.rs
  fighters/kirby/src/acmd/aerials.rs
  fighters/koopajr/src/acmd/aerials.rs
  fighters/link/src/acmd/aerials.rs
  fighters/lucario/src/acmd/aerials.rs
  fighters/lucas/src/acmd/aerials.rs
  fighters/lucina/src/acmd/aerials.rs
  fighters/marth/src/acmd/aerials.rs
  fighters/master/src/acmd/aerials.rs
  fighters/metaknight/src/acmd/aerials.rs
  fighters/mewtwo/src/acmd/aerials.rs
  fighters/miigunner/src/acmd/aerials.rs
  fighters/miiswordsman/src/acmd/aerials.rs
  fighters/murabito/src/acmd/aerials.rs
  fighters/packun/src/acmd/aerials.rs
  fighters/palutena/src/acmd/aerials.rs
  fighters/pfushigisou/src/acmd/aerials.rs
  fighters/pichu/src/acmd/aerials.rs
  fighters/pikachu/src/acmd/aerials.rs
  fighters/pit/src/acmd/aerials.rs
  fighters/pitb/src/acmd/aerials.rs
  fighters/purin/src/acmd/aerials.rs
  fighters/pzenigame/src/acmd/aerials.rs
  fighters/ridley/src/acmd/aerials.rs
  fighters/robot/src/acmd/aerials.rs
  fighters/rockman/src/acmd/aerials.rs
  fighters/rosetta/src/acmd/aerials.rs
  fighters/roy/src/acmd/aerials.rs
  fighters/samus/src/acmd/aerials.rs
  fighters/samusd/src/acmd/aerials.rs
  fighters/sheik/src/acmd/aerials.rs
  fighters/simon/src/acmd/aerials.rs
  fighters/snake/src/acmd/aerials.rs
  fighters/szerosuit/src/acmd/aerials.rs
  fighters/toonlink/src/acmd/aerials.rs
  fighters/trail/src/acmd/aerials.rs
  fighters/wiifit/src/acmd/aerials.rs
  fighters/yoshi/src/acmd/aerials.rs
  fighters/younglink/src/acmd/aerials.rs
  fighters/zelda/src/acmd/aerials.rs
  romfs/source/fighter/common/param/common.prcxml
Labels: character change, engine, semver:patch, backroom approved

#2449 Ridley/Ike upB bugfix
  fighters/ike/src/opff.rs
  fighters/ridley/src/opff.rs
Labels: bug, semver:patch

#2411 ike.png
  dynamic/src/consts.rs
  fighters/ike/src/acmd/aerials.rs
  fighters/ike/src/acmd/ground.rs
  fighters/ike/src/acmd/other.rs
  fighters/ike/src/acmd/smashes.rs
  fighters/ike/src/acmd/specials.rs
  fighters/ike/src/acmd/tilts.rs
  fighters/ike/src/opff.rs
  fighters/ike/src/status/mod.rs
  fighters/ike/src/status/special_s.rs
  fighters/ike/src/sword/acmd.rs
Labels: character change, semver:patch, backroom approved

#2447 Platdrop Momentum Rewrite
  fighters/common/src/general_statuses/pass.rs
  romfs/source/fighter/common/hdr/param/fighter_param.xml
Labels: engine, semver:patch
