Repository HDR-Development/HewDraw-Remix, pull requests merged in 2024-09, with the labels that each got.

#2513 Zelda LC Nayru's Fix
  fighters/zelda/src/acmd/specials.rs
  fighters/zelda/src/opff.rs
Labels: bug, semver:patch

#2509 Fix custom game mode menu on specific emulators
  utils/src/game_modes.rs
Labels: bug, semver:patch

#2515 Allow most custom modes to run in local wireless multiplayer
  utils/src/game_modes.rs
Labels: enhancement, engine, semver:patch

#2473 Dedede Down B Rework and other adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/lua_bind_hook/ground.rs
  fighters/dedede/src/acmd/other.rs
  fighters/dedede/src/acmd/specials.rs
  fighters/dedede/src/acmd/throws.rs
  fighters/dedede/src/acmd/tilts.rs
  fighters/dedede/src/gordo/acmd.rs
  fighters/dedede/src/gordo/status.rs
  fighters/dedede/src/jethammer/acmd.rs
  fighters/dedede/src/jethammer/mod.rs
  fighters/dedede/src/lib.rs
  fighters/dedede/src/opff.rs
  fighters/dedede/src/status/mod.rs
  fighters/dedede/src/status/special_hi.rs
  fighters/dedede/src/status/special_lw.rs
  fighters/dedede/src/status/special_s.rs
  romfs/source/fighter/dedede/motion/body/motion_patch.yaml
  romfs/source/fighter/dedede/param/vl.prcxml
Labels: character change, semver:patch, balance approved, includes assets
