Repository HDR-Development/HewDraw-Remix, pull requests merged in 2024-08, with the labels that each got.

#2480 New hashes
  fighters/bayonetta/src/status/specialn.rs
  fighters/kirby/src/status/bayonetta_special_n_cancel.rs
  fighters/pacman/src/status/special_n.rs
  fighters/pikmin/src/status/attack_air.rs
Labels: infrastructure, semver:patch

#2481 ZSS Effect Trail Fixes
  fighters/szerosuit/src/acmd/aerials.rs
  fighters/szerosuit/src/acmd/tilts.rs
Labels: aesthetics, semver:patch

#2482 Bayonetta Side-B Hitcheck Fix
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/status/specials.rs
Labels: bug, semver:patch

#2479 Rumble fixes, mainly for Daisy
  fighters/daisy/src/acmd/smashes.rs
  fighters/daisy/src/acmd/specials.rs
  fighters/daisy/src/acmd/throws.rs
  fighters/daisy/src/acmd/tilts.rs
  fighters/iceclimber/src/acmd/aerials.rs
  fighters/kirby/src/acmd/copy/daisy.rs
  fighters/pacman/src/acmd/aerials.rs
Labels: bug, semver:patch

#2477 Byleth bugfix and adjustments
  fighters/master/src/acmd/aerials.rs
  fighters/master/src/acmd/specials.rs
  fighters/master/src/acmd/tilts.rs
  romfs/source/fighter/master/param/vl.prcxml
Labels: good first issue, character change, semver:patch, backroom approved

#2483 Hotfixes
  fighters/kirby/src/acmd/copy/daisy.rs
  fighters/kirby/src/acmd/copy/luigi.rs
  fighters/kirby/src/acmd/copy/mario.rs
  fighters/kirby/src/acmd/copy/mariod.rs
  fighters/kirby/src/acmd/copy/palutena.rs
  fighters/koopa/src/opff.rs
  fighters/koopa/src/status/mod.rs
  fighters/master/src/arrow2/acmd.rs
  fighters/pacman/src/status/special_n.rs
  fighters/richter/src/acmd/smashes.rs
Labels: bug, aesthetics, semver:patch

#2484 whitespace
  .github/workflows/build_nightly.yml
Labels: semver:patch

#2485 Migration Time
  .github/workflows/build_beta.yml
  .github/workflows/build_prerelease.yml
  .github/workflows/publish_lvd_nightly.yml
  scripts/get_build_type.py
  scripts/make_diff.py
Labels: infrastructure, semver:patch

#2487 it's back I guess
  .github/workflows/build_prerelease.yml
Labels: semver:patch

#2488 Bayonetta Fixes / Neutral B Slowdown Adj
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/opff.rs
  fighters/bayonetta/src/status/mod.rs
  fighters/bayonetta/src/status/specialn.rs
  fighters/bayonetta/src/status/wait.rs
  romfs/source/fighter/bayonetta/param/vl.prcxml
Labels: bug, character change, semver:patch, backroom approved

#2489 Small Workflows Update
  .github/workflows/pr_build.yml
  scripts/full_package.py
Labels: semver:patch

#2490 add secret token to build
  .github/workflows/build_beta.yml
Labels: semver:patch

#2491 ...
  .github/workflows/build_prerelease.yml
Labels: semver:patch

#2492 split romfs download out of python
  .github/workflows/build_prerelease.yml
  scripts/full_package.py
Labels: semver:patch

#2493 python script fix
  .github/workflows/build_prerelease.yml
  scripts/full_package.py
Labels: semver:patch

#2441 Mewtwo Concept
  fighters/mewtwo/src/acmd/aerials.rs
  fighters/mewtwo/src/acmd/tilts.rs
  fighters/mewtwo/src/bindball/acmd.rs
  fighters/mewtwo/src/opff.rs
  romfs/source/fighter/mewtwo/motion/body/motion_patch.yaml
  romfs/source/fighter/mewtwo/param/vl.prcxml
Labels: character change, semver:patch, balance approved

#2495 Robin Fixes + Thoron Conceptual
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/opff.rs
  fighters/bayonetta/src/status/mod.rs
  fighters/bayonetta/src/status/specialn.rs
  fighters/bayonetta/src/status/wait.rs
  fighters/reflet/src/acmd/ground.rs
  fighters/reflet/src/acmd/specials.rs
  fighters/reflet/src/acmd/tilts.rs
  fighters/reflet/src/opff.rs
  fighters/reflet/src/status/float.rs
  fighters/reflet/src/status/special_n.rs
  fighters/reflet/src/thunder/acmd.rs
  romfs/source/fighter/bayonetta/param/vl.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/reflet/motion/body/motion_patch.yaml
  romfs/source/fighter/reflet/param/vl.prcxml
Labels: character change, semver:patch, balance approved

#2504 PreRelease Followup
  fighters/falco/src/acmd/specials.rs
  fighters/ken/src/status/special_lw.rs
  fighters/koopajr/src/status/mod.rs
  fighters/koopajr/src/status/special_hi.rs
  fighters/metaknight/src/acmd/tilts.rs
  fighters/ryu/src/status/special_lw.rs
  romfs/source/fighter/common/param/battle_object.prcxml
Labels: aesthetics, character change, semver:patch, stages, balance approved

#2503 Jigglypuff Neutral Special Rework
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/attack.rs
  fighters/ness/src/pkfire/acmd.rs
  fighters/purin/src/acmd/specials.rs
  fighters/purin/src/disarmingvoice/acmd.rs
  fighters/purin/src/disarmingvoice/mod.rs
  fighters/purin/src/disarmingvoice/status.rs
  fighters/purin/src/lib.rs
  fighters/purin/src/opff.rs
  fighters/purin/src/status/mod.rs
  fighters/purin/src/status/special_n.rs
  romfs/source/fighter/purin/motion/body/motion_patch.yaml
  romfs/source/fighter/purin/param/vl.prcxml
Labels: character change, semver:patch, includes assets, discussion ongoing

#2506 workflow fixes
  .github/workflows/build_beta.yml
Labels: semver:patch
