Repository HDR-Development/HewDraw-Remix, pull requests merged in 2024-03, with the labels that each got.

#2293 Misc Fixes
  fighters/ike/src/status.rs
  fighters/koopajr/src/status.rs
  fighters/lucas/src/opff.rs
  fighters/lucas/src/status.rs
  fighters/mario/src/status.rs
  fighters/master/src/lib.rs
  fighters/master/src/status.rs
  fighters/ness/src/opff.rs
  fighters/ness/src/status.rs
  fighters/rockman/src/status.rs
  fighters/snake/src/status/mod.rs
  fighters/sonic/src/status/special_s.rs
  fighters/szerosuit/src/lib.rs
  fighters/szerosuit/src/status.rs
Labels: bug, crash, semver:patch

#2290 Small Fixes
  fighters/common/src/opff/floats.rs
  fighters/palutena/src/acmd/other.rs
  fighters/pzenigame/src/acmd/aerials.rs
  romfs/source/fighter/palutena/motion/body/motion_patch.yaml
Labels: bug, semver:patch

#2289 Ganondorf Adjustments
  fighters/ganon/src/acmd/ground.rs
  fighters/ganon/src/acmd/tilts.rs
  fighters/ganon/src/status/attack_lw3.rs
  romfs/source/fighter/ganon/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2261 PM x HDR Roy PR
  dynamic/src/consts.rs
  fighters/roy/src/acmd/aerials.rs
  fighters/roy/src/acmd/ground.rs
  fighters/roy/src/acmd/other.rs
  fighters/roy/src/acmd/smashes.rs
  fighters/roy/src/acmd/specials.rs
  fighters/roy/src/acmd/tilts.rs
  fighters/roy/src/opff.rs
  fighters/roy/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/roy/motion/body/motion_patch.yaml
  romfs/source/fighter/roy/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2295 Time to scream
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/vtables/mod.rs
  fighters/common/src/function_hooks/vtables/reflet.rs
  fighters/common/src/lib.rs
  fighters/koopa/src/opff.rs
  fighters/koopa/src/status.rs
  fighters/lucas/src/status.rs
  fighters/mariod/src/status.rs
  fighters/reflet/src/lib.rs
  fighters/roy/src/acmd/specials.rs
  fighters/ryu/src/status.rs
  fighters/trail/src/lib.rs
  fighters/trail/src/opff.rs
Labels: bug, semver:patch

#2286 Various Dedede Bugfixes
  fighters/dedede/src/acmd/other.rs
  fighters/dedede/src/acmd/specials.rs
  fighters/dedede/src/opff.rs
Labels: bug, semver:patch

#2137 Koopa Claw Side Special
  dynamic/src/consts.rs
  fighters/koopa/Cargo.toml
  fighters/koopa/src/acmd/specials.rs
  fighters/koopa/src/status.rs
  fighters/koopa/src/status/special_n.rs
  fighters/koopa/src/status/special_s.rs
  romfs/source/fighter/koopa/motion/body/motion_patch.yaml
  romfs/source/fighter/koopa/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2263 Sonic Up Tilt Rework
  fighters/sonic/src/acmd/tilts.rs
  romfs/source/fighter/sonic/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#2257 Mewtwo Adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/mewtwo/src/acmd/aerials.rs
  fighters/mewtwo/src/acmd/ground.rs
  fighters/mewtwo/src/acmd/smashes.rs
  fighters/mewtwo/src/acmd/specials.rs
  fighters/mewtwo/src/acmd/throws.rs
  fighters/mewtwo/src/acmd/tilts.rs
  fighters/mewtwo/src/opff.rs
  fighters/mewtwo/src/status.rs
  fighters/mewtwo/src/status/fall.rs
  fighters/mewtwo/src/status/float.rs
  fighters/mewtwo/src/status/special_n.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/mewtwo/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#2300 Float Followup Fixes
  fighters/common/src/general_statuses/float/main.rs
  fighters/daisy/src/status/attack_air.rs
  fighters/daisy/src/status/mod.rs
  fighters/daisy/src/status/uniq_float.rs
  fighters/daisy/src/status/uniq_float_start.rs
  fighters/peach/src/status/attack_air.rs
  fighters/peach/src/status/mod.rs
  fighters/peach/src/status/uniq_float.rs
  fighters/peach/src/status/uniq_float_start.rs
  fighters/reflet/src/acmd/aerials.rs
Labels: semver:patch

#2301 Mewtwo Unfloat Confusion Window fix
  fighters/common/src/opff/floats.rs
  fighters/common/src/opff/mod.rs
  fighters/mewtwo/src/status/attack_air.rs
  fighters/mewtwo/src/status/fall.rs
Labels: bug, semver:patch

#2303 Fix Custom Gamemodes
  fighters/common/src/function_hooks/attack.rs
  utils/src/game_modes.rs
  utils/src/offsets.rs
Labels: bug, semver:patch

#2313 SDI change
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#2316 edit the SDI values again
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#2324 More confirmed hashes
  fighters/demon/src/acmd/throws.rs
  fighters/edge/src/status/special_n.rs
  fighters/kirby/src/status/edge_special_n.rs
  fighters/kirby/src/status/littlemac_special_n.rs
  fighters/koopa/src/status/special_s.rs
  fighters/mariod/src/acmd/specials.rs
  fighters/pikmin/src/status/attack_air.rs
  fighters/pit/src/acmd/specials.rs
  fighters/pitb/src/acmd/specials.rs
  fighters/roy/src/acmd/specials.rs
Labels: infrastructure, semver:patch

#2265 Fix Mii Gunner Shine
  fighters/miigunner/src/opff.rs
Labels: character change, semver:patch, backroom approved

#2294 Bayonetta Tweaks
  dynamic/src/consts.rs
  fighters/bayonetta/src/acmd/ground.rs
  fighters/bayonetta/src/acmd/other.rs
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/acmd/tilts.rs
  fighters/bayonetta/src/opff.rs
  fighters/bayonetta/src/status/mod.rs
  fighters/bayonetta/src/status/specialn.rs
  fighters/bayonetta/src/status/specials.rs
  fighters/common/src/function_hooks/fighter_util.rs
  fighters/kirby/src/opff.rs
  fighters/kirby/src/status.rs
  fighters/kirby/src/status/bayonetta_special_n_cancel.rs
  romfs/source/fighter/bayonetta/motion/body/motion_patch.yaml
  romfs/source/fighter/bayonetta/param/vl.prcxml
  romfs/source/fighter/common/param/fighter_param_motion.prcxml
Labels: character change, semver:patch, backroom approved

#2314 Dark Samus QoL
  fighters/samusd/src/acmd/aerials.rs
  fighters/samusd/src/acmd/ground.rs
  fighters/samusd/src/opff.rs
  romfs/source/fighter/samusd/motion/body/motion_patch.yaml
  romfs/source/fighter/samusd/param/hdr.xml
  romfs/source/fighter/samusd/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#2277 Young link
  fighters/younglink/src/acmd/aerials.rs
  fighters/younglink/src/acmd/ground.rs
  fighters/younglink/src/acmd/other.rs
  fighters/younglink/src/acmd/smashes.rs
  fighters/younglink/src/acmd/specials.rs
  fighters/younglink/src/acmd/throws.rs
  fighters/younglink/src/acmd/tilts.rs
  fighters/younglink/src/opff.rs
  fighters/younglink/src/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/younglink/motion/body/motion_patch.yaml
  romfs/source/fighter/younglink/param/vl.prcxml
  romfs/source/item/common/param/param.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2285 Shulk Changes
  dynamic/src/consts.rs
  fighters/shulk/src/acmd/aerials.rs
  fighters/shulk/src/acmd/ground.rs
  fighters/shulk/src/acmd/other.rs
  fighters/shulk/src/acmd/smashes.rs
  fighters/shulk/src/acmd/specials.rs
  fighters/shulk/src/acmd/tilts.rs
  fighters/shulk/src/lib.rs
  fighters/shulk/src/opff.rs
  fighters/shulk/src/status.rs
  fighters/shulk/src/status/special_n.rs
  fighters/shulk/src/status/special_s.rs
  fighters/shulk/src/vtable_hook.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/shulk/motion/body/motion_patch.yaml
  romfs/source/fighter/shulk/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2299 Richter Rework
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/opff/gentleman.rs
  fighters/kirby/src/acmd/copyspecials.rs
  fighters/kirby/src/opff.rs
  fighters/richter/src/acmd/aerials.rs
  fighters/richter/src/acmd/ground.rs
  fighters/richter/src/acmd/other.rs
  fighters/richter/src/acmd/smashes.rs
  fighters/richter/src/acmd/specials.rs
  fighters/richter/src/acmd/throws.rs
  fighters/richter/src/acmd/tilts.rs
  fighters/richter/src/opff.rs
  fighters/richter/src/status/mod.rs
  fighters/richter/src/status/special_s.rs
  fighters/simon/src/acmd/ground.rs
  fighters/simon/src/opff.rs
  romfs/source/fighter/common/hdr/param/fighter_param.xml
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
  romfs/source/fighter/richter/motion/body/motion_patch.yaml
  romfs/source/fighter/richter/motion/whip/motion_patch.yaml
  romfs/source/fighter/richter/param/vl.prcxml
  romfs/source/fighter/simon/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#2305 Cloud Touch-ups
  fighters/cloud/src/acmd/aerials.rs
  fighters/cloud/src/acmd/smashes.rs
  fighters/cloud/src/acmd/specials.rs
  fighters/cloud/src/acmd/tilts.rs
  romfs/source/fighter/cloud/motion/body/motion_patch.yaml
  romfs/source/fighter/cloud/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#2308 Mario/Doc Aesthetic Tweaks
  fighters/mario/src/acmd/ground.rs
  fighters/mario/src/acmd/smashes.rs
  fighters/mariod/src/acmd/aerials.rs
  fighters/mariod/src/acmd/ground.rs
  fighters/mariod/src/acmd/other.rs
  fighters/mariod/src/acmd/smashes.rs
  fighters/mariod/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: aesthetics, semver:patch, includes assets

#2312 Implement knockback-based hitlag scaling
  fighters/common/src/function_hooks/attack.rs
Labels: engine, semver:patch

#2309 Restore Kill Screen
  dynamic/src/consts.rs
  fighters/common/src/lib.rs
  fighters/common/src/opff/other.rs
  romfs/source/fighter/brave/param/vl.prcxml
  romfs/source/fighter/captain/param/vl.prcxml
  romfs/source/fighter/chrom/param/vl.prcxml
  romfs/source/fighter/cloud/param/vl.prcxml
  romfs/source/fighter/dedede/param/vl.prcxml
  romfs/source/fighter/demon/param/vl.prcxml
  romfs/source/fighter/donkey/param/vl.prcxml
  romfs/source/fighter/gamewatch/param/vl.prcxml
  romfs/source/fighter/gaogaen/param/vl.prcxml
  romfs/source/fighter/ike/param/vl.prcxml
  romfs/source/fighter/kirby/param/vl.prcxml
  romfs/source/fighter/littlemac/param/vl.prcxml
  romfs/source/fighter/lucario/param/vl.prcxml
  romfs/source/fighter/lucina/param/vl.prcxml
  romfs/source/fighter/luigi/param/vl.prcxml
  romfs/source/fighter/marth/param/vl.prcxml
  romfs/source/fighter/master/param/vl.prcxml
  romfs/source/fighter/miifighter/param/vl.prcxml
  romfs/source/fighter/purin/param/vl.prcxml
  romfs/source/fighter/ridley/param/vl.prcxml
  romfs/source/fighter/roy/param/vl.prcxml
  romfs/source/fighter/wario/param/vl.prcxml
  romfs/source/item/pickelbomb/param/param.prcxml
  utils/src/lib.rs
  utils/src/modules/meter.rs
Labels: engine, semver:patch, includes assets

#2302 CC buff
  fighters/common/src/function_hooks/attack.rs
Labels: engine, semver:patch

#2315 B-Turnaround Fix
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#2327 Young Link - quick adjustments
  fighters/younglink/src/acmd/aerials.rs
  fighters/younglink/src/acmd/throws.rs
Labels: character change, semver:patch, backroom approved

#2325 Shulk hotfix
  fighters/shulk/src/acmd/aerials.rs
  fighters/shulk/src/acmd/smashes.rs
Labels: bug, semver:patch, includes assets

#2330 Hitlag scaling adjustments
  fighters/common/src/function_hooks/attack.rs
Labels: engine, semver:patch

#2331 Crash fix
  fighters/common/src/function_hooks/attack.rs
Labels: crash, semver:patch

#2334 restore hazards changes
  fighters/common/src/function_hooks/stage_hazards.rs
Labels: bug, enhancement, good first issue, infrastructure, aesthetics, engine, semver:patch, stages, backroom approved

#2336 new matchup screen
  .gitignore
  Cargo.lock
  Cargo.toml
  plugin/Cargo.lock
  src/lib.rs
  src/matchup.rs
  src/matchup/containers.rs
  src/matchup/types.rs
Labels: aesthetics, semver:patch

#2337 Item crash fix pt 2
  fighters/common/src/function_hooks/attack.rs
Labels: crash, semver:patch

#2335 Richter fixes
  fighters/kirby/src/opff.rs
  fighters/richter/src/acmd/aerials.rs
  fighters/richter/src/acmd/ground.rs
  fighters/richter/src/acmd/other.rs
  fighters/richter/src/acmd/smashes.rs
  fighters/richter/src/acmd/specials.rs
  fighters/richter/src/acmd/tilts.rs
  fighters/richter/src/opff.rs
  fighters/simon/src/acmd/ground.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
  romfs/source/fighter/richter/motion/body/motion_patch.yaml
  romfs/source/fighter/richter/param/hdr.xml
Labels: character change, semver:patch, backroom approved, includes assets

#2340 Kill Screen Fixes Part 1
  dynamic/src/consts.rs
  fighters/common/src/opff/other.rs
  utils/src/modules/meter.rs
Labels: engine, semver:patch

#2339 Matchup screen hotfixes
  src/matchup.rs
Labels: bug, semver:patch

#2343 Fix Lylat Background
  fighters/common/src/function_hooks/stage_hazards.rs
Labels: bug, semver:patch

#2342 Cap Maximum SDI Impulses At 11
  romfs/source/fighter/common/param/common.prcxml
Labels: engine, semver:patch

#2344 Nightly Roy Hotfix
  fighters/roy/src/acmd/aerials.rs
  fighters/roy/src/acmd/ground.rs
  fighters/roy/src/acmd/smashes.rs
  fighters/roy/src/acmd/specials.rs
  fighters/roy/src/acmd/throws.rs
  fighters/roy/src/acmd/tilts.rs
  romfs/source/fighter/common/hdr/param/fighter_param.xml
  romfs/source/fighter/roy/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2341 Yink Bair Nerf 2: this time it's personal
  fighters/younglink/src/acmd/aerials.rs
Labels: character change, semver:patch, backroom approved

#2329 Dark Samus Colored Trails
  fighters/samusd/src/acmd/aerials.rs
  fighters/samusd/src/acmd/ground.rs
  fighters/samusd/src/acmd/other.rs
  fighters/samusd/src/acmd/tilts.rs
Labels: aesthetics, semver:patch

#2351 Greninja Consistency
  fighters/gekkouga/src/acmd/aerials.rs
  fighters/gekkouga/src/acmd/ground.rs
  fighters/gekkouga/src/acmd/other.rs
  fighters/gekkouga/src/acmd/smashes.rs
Labels: character change, semver:patch, backroom approved, includes assets

#2348 Richter Adjustments
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/richter/src/acmd/aerials.rs
  fighters/richter/src/acmd/ground.rs
  fighters/richter/src/acmd/mod.rs
  fighters/richter/src/acmd/other.rs
  fighters/richter/src/acmd/smashes.rs
  fighters/richter/src/acmd/specials.rs
  fighters/richter/src/acmd/throws.rs
  fighters/richter/src/acmd/tilts.rs
  fighters/richter/src/axe/acmd.rs
  fighters/richter/src/axe/mod.rs
  fighters/richter/src/axe/opff.rs
  fighters/richter/src/lib.rs
  fighters/richter/src/opff.rs
  fighters/richter/src/status/attacklw3.rs
  fighters/richter/src/status/attacks3.rs
  fighters/richter/src/status/mod.rs
  fighters/richter/src/status/special_n.rs
  fighters/richter/src/status/special_s.rs
  fighters/richter/src/whip/acmd.rs
  fighters/richter/src/whip/mod.rs
  romfs/source/fighter/common/hdr/param/fighter_param.xml
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/richter/motion/body/motion_patch.yaml
  romfs/source/fighter/richter/param/hdr.xml
  romfs/source/fighter/richter/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2349 fix: Fix training modpack and reduce startup times by some
  utils/Cargo.toml
Labels: semver:patch

#2354 Fighter Crate Refactor Hotfixes
  fighters/edge/src/acmd/smashes.rs
  fighters/miiswordsman/src/lightshuriken/mod.rs
  fighters/palutena/src/acmd/specials/special_n_r.rs
  fighters/ryu/src/hadoken/acmd.rs
  fighters/samusd/src/acmd/aerials.rs
  fighters/samusd/src/acmd/ground.rs
  fighters/samusd/src/acmd/other.rs
  fighters/samusd/src/acmd/tilts.rs
  fighters/snake/src/acmd/specials.rs
Labels: bug, semver:patch
