Repository HDR-Development/HewDraw-Remix, pull requests merged in 2024-05, with the labels that each got.

#2387 Fix ZAir OOS Behavior
  fighters/common/src/general_statuses/mod.rs
Labels: bug, engine, semver:patch

#2382 Kirby Thoron Fix + Rounding Error
  dynamic/src/consts.rs
  fighters/kirby/src/status/mod.rs
  fighters/kirby/src/status/reflet_special_n.rs
  fighters/reflet/src/acmd/ground.rs
  fighters/reflet/src/status/special_n.rs
  fighters/reflet/src/thunder/acmd.rs
Labels: bug, semver:patch

#2381 Mewtwo fixes + Float Input Adjustment
  fighters/common/src/general_statuses/attack/attackair.rs
  fighters/kirby/src/opff/copy.rs
  fighters/mewtwo/src/acmd/aerials.rs
  fighters/mewtwo/src/acmd/tilts.rs
  fighters/reflet/src/status/float.rs
Labels: bug, semver:patch, includes assets

#2386 Killscreen Touchups 3.0
  dynamic/src/util.rs
  fighters/common/src/function_hooks/attack.rs
  fighters/common/src/function_hooks/killscreen.rs
  fighters/common/src/function_hooks/mod.rs
  utils/src/modules/meter.rs
Labels: bug, engine, semver:patch

#2388 Fix ZAir While Holding An Item
  dynamic/src/modules/input.rs
  fighters/common/src/function_hooks/controls.rs
  utils/src/modules/input.rs
Labels: bug, engine, semver:patch

#2384 Greninja dair changes 2 electicboogaloo
  fighters/gekkouga/src/acmd/aerials.rs
  fighters/gekkouga/src/acmd/other.rs
Labels: character change, semver:patch, backroom approved

#2393 Revert Halberd Hazards
  fighters/common/src/function_hooks/stage_hazards.rs
Labels: semver:patch, stages

#2396 Fix Accidental Parry/ZAir After Reset/Runback
  dynamic/src/ext.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/common/src/opff/other.rs
Labels: bug, engine, semver:patch

#2398 Platdrop Logic Rewrite
  fighters/common/src/general_statuses/mod.rs
  fighters/common/src/general_statuses/pass.rs
Labels: engine, semver:patch

#2392 Corrin Adjustments
  fighters/kamui/src/acmd/aerials.rs
  fighters/kamui/src/acmd/ground.rs
  fighters/kamui/src/acmd/smashes.rs
  fighters/kamui/src/acmd/specials.rs
  fighters/kamui/src/acmd/throws.rs
  fighters/kamui/src/ryusensya/acmd.rs
  romfs/source/fighter/kamui/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2390 Roy Misc changes
  fighters/roy/src/acmd/aerials.rs
  fighters/roy/src/acmd/specials/mod.rs
  fighters/roy/src/acmd/specials/special_s1.rs
  fighters/roy/src/acmd/specials/special_s2.rs
  fighters/roy/src/acmd/specials/special_s3.rs
  fighters/roy/src/acmd/specials/special_s4.rs
  fighters/roy/src/acmd/tilts.rs
Labels: character change, semver:patch, backroom approved

#2402 Grab Bag Touchups
  fighters/edge/src/flash/acmd.rs
  fighters/edge/src/flash/status.rs
  fighters/falco/src/status/special_lw.rs
  fighters/jack/src/status/dispatch.rs
  fighters/jack/src/status/summon.rs
  fighters/ken/src/acmd/finals.rs
  fighters/ken/src/opff.rs
  fighters/ken/src/status/mod.rs
  fighters/ryu/src/acmd/smashes.rs
  fighters/ryu/src/opff.rs
  fighters/ryu/src/shinkuhadoken/acmd.rs
  fighters/ryu/src/status/mod.rs
  romfs/source/fighter/ryu/motion/body/motion_patch.yaml
Labels: character change, crash, semver:patch, backroom approved

#2403 That Wall Jump Bug that I Hate
  fighters/common/src/function_hooks/controls.rs
Labels: bug, semver:patch

#2407 Platdrop Bugfix
  fighters/common/src/general_statuses/pass.rs
Labels: bug, semver:patch

#2408 Workflow Version Bump
  .github/workflows/build_beta.yml
  .github/workflows/build_nightly.yml
  .github/workflows/pr_build.yml
  .github/workflows/pr_comment.yml
  .github/workflows/publish_lvd_beta.yml
  .github/workflows/publish_lvd_nightly.yml
Labels: infrastructure, semver:patch

#2410 Platdrop Fix (Again)
  fighters/common/src/general_statuses/pass.rs
Labels: bug, semver:patch

#2420 Update pr_comment.yml
  .github/workflows/pr_comment.yml
Labels: infrastructure, semver:patch

#2421 Update pr_comment.yml
  .github/workflows/pr_comment.yml
Labels: infrastructure, semver:patch

#2412 Greninja DTaunt FAF Change
  romfs/source/fighter/gekkouga/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2409 Diddy Kong Specials Adjustments
  dynamic/src/consts.rs
  fighters/diddy/src/acmd/specials.rs
  fighters/diddy/src/barreljet/acmd.rs
  fighters/diddy/src/barreljet/mod.rs
  fighters/diddy/src/lib.rs
  fighters/diddy/src/status/mod.rs
  fighters/diddy/src/status/special_hi_upper.rs
  fighters/diddy/src/status/special_s_jump.rs
Labels: character change, semver:patch, backroom approved

#2422 Simon Tweaks
  fighters/simon/src/acmd/aerials.rs
  fighters/simon/src/acmd/smashes.rs
  fighters/simon/src/acmd/throws.rs
  fighters/simon/src/acmd/tilts.rs
Labels: character change, semver:patch, backroom approved, includes assets

#2424 Yoshi 1.8x multiplier on dair needs to go
  fighters/yoshi/src/acmd/aerials.rs
Labels: character change, semver:patch, backroom approved

#2425 Shotos hotfix
  fighters/common/src/function_hooks/finals.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/ken/src/hadoken/acmd.rs
  fighters/ken/src/opff.rs
  fighters/ken/src/status/mod.rs
  fighters/ryu/src/acmd/finals.rs
  fighters/ryu/src/hadoken/acmd.rs
  fighters/ryu/src/opff.rs
  fighters/ryu/src/shinkuhadoken/acmd.rs
  fighters/ryu/src/status/mod.rs
  romfs/source/fighter/ken/param/vl.prcxml
  romfs/source/fighter/ryu/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#2427 Misc Changes ft. Olimar
  fighters/common/src/function_hooks/lua_bind_hook/ground.rs
  fighters/ken/src/acmd/tilts.rs
  fighters/kirby/src/opff/copy.rs
  fighters/pikmin/src/acmd/specials.rs
  fighters/pikmin/src/opff.rs
  fighters/pikmin/src/pikmin/mod.rs
  fighters/pikmin/src/status/attack_air.rs
  fighters/ryu/src/acmd/tilts.rs
  romfs/source/fighter/pikmin/motion/body/motion_patch.yaml
  romfs/source/fighter/pikmin/param/vl.prcxml
Labels: character change, semver:patch, backroom approved
