Repository HDR-Development/HewDraw-Remix, pull requests merged in 2024-07, with the labels that each got.

#2455 Improve Wavedrop Max Speeds
  romfs/source/fighter/common/hdr/param/fighter_param.xml
Labels: character change, semver:patch, backroom approved

#2433 Ness Rework Concept
  dynamic/src/consts.rs
  fighters/ness/src/acmd/aerials.rs
  fighters/ness/src/acmd/ground.rs
  fighters/ness/src/acmd/smashes.rs
  fighters/ness/src/acmd/specials.rs
  fighters/ness/src/acmd/throws.rs
  fighters/ness/src/acmd/tilts.rs
  fighters/ness/src/opff.rs
  fighters/ness/src/pkflash/acmd.rs
  fighters/ness/src/pkthunder/acmd.rs
  fighters/ness/src/pkthunder/opff.rs
  fighters/ness/src/status/mod.rs
  fighters/ness/src/yoyohead/acmd.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/ness/motion/body/motion_patch.yaml
  romfs/source/fighter/ness/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2435 Copy Abilities Strike Again + Small Adjustments
  dynamic/src/consts.rs
  dynamic/src/ui.rs
  fighters/buddy/src/acmd/specials.rs
  fighters/kirby/src/acmd/aerials.rs
  fighters/kirby/src/acmd/copy/buddy.rs
  fighters/kirby/src/acmd/copy/lucas.rs
  fighters/kirby/src/acmd/copy/palutena.rs
  fighters/kirby/src/acmd/smashes.rs
  fighters/kirby/src/acmd/specials.rs
  fighters/kirby/src/acmd/throws.rs
  fighters/kirby/src/lib.rs
  fighters/kirby/src/opff.rs
  fighters/kirby/src/opff/copy.rs
  fighters/kirby/src/status/buddy_bayonet_end.rs
  fighters/kirby/src/status/mod.rs
  fighters/kirby/src/status/ridley_special_n.rs
  fighters/palutena/src/acmd/specials/mod.rs
  fighters/palutena/src/autoaimbullet/acmd.rs
  fighters/roy/src/acmd/specials/mod.rs
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
  romfs/source/fighter/kirby/param/vl.prcxml
  romfs/source/fighter/palutena/param/vl.prcxml
  utils/src/ui.rs
  utils/src/ui/cyan_meter.rs
Labels: bug, character change, semver:patch, backroom approved

#2451 Knockdown Neutral Getup With Shield
  fighters/common/src/general_statuses/down.rs
Labels: engine, semver:patch

#2419 The Pac is Back
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/killscreen.rs
  fighters/falco/src/opff.rs
  fighters/pacman/src/acmd/aerials.rs
  fighters/pacman/src/acmd/ground.rs
  fighters/pacman/src/acmd/smashes.rs
  fighters/pacman/src/acmd/specials.rs
  fighters/pacman/src/acmd/throws.rs
  fighters/pacman/src/acmd/tilts.rs
  fighters/pacman/src/firehydrant/acmd.rs
  fighters/pacman/src/firehydrant/mod.rs
  fighters/pacman/src/lib.rs
  fighters/pacman/src/opff.rs
  fighters/pacman/src/status/attack_air.rs
  fighters/pacman/src/status/mod.rs
  fighters/pacman/src/status/special_hi.rs
  fighters/pacman/src/status/special_lw.rs
  fighters/pacman/src/status/special_n.rs
  fighters/pacman/src/status/special_s.rs
  fighters/pacman/src/trampoline/acmd.rs
  fighters/pacman/src/trampoline/mod.rs
  fighters/pacman/src/trampoline/status.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/pacman/motion/body/motion_patch.yaml
  romfs/source/fighter/pacman/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2457 Falco Shine Fix
  fighters/falco/src/opff.rs
Labels: bug, semver:patch

#2444 Gentleman and Rapid Jab Overhaul
  .gitignore
  Cargo.lock
  fighters/common/src/general_statuses/attack/attack.rs
  fighters/common/src/opff/gentleman.rs
  fighters/common/src/opff/mod.rs
  fighters/dedede/src/acmd/ground.rs
  fighters/falco/src/acmd/ground.rs
  fighters/fox/src/acmd/ground.rs
  fighters/gamewatch/src/acmd/ground.rs
  fighters/kirby/src/acmd/ground.rs
  fighters/koopajr/src/acmd/ground.rs
  fighters/mewtwo/src/acmd/ground.rs
  fighters/miifighter/src/acmd/ground.rs
  fighters/pfushigisou/src/acmd/ground.rs
  fighters/sheik/src/acmd/ground.rs
  fighters/simon/src/acmd/ground.rs
  fighters/simon/src/whip/acmd.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/dedede/motion/body/motion_patch.yaml
  romfs/source/fighter/falco/motion/body/motion_patch.yaml
  romfs/source/fighter/fox/motion/body/motion_patch.yaml
  romfs/source/fighter/gamewatch/motion/body/motion_patch.yaml
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
  romfs/source/fighter/koopajr/motion/body/motion_patch.yaml
  romfs/source/fighter/mewtwo/motion/body/motion_patch.yaml
  romfs/source/fighter/miifighter/motion/body/motion_patch.yaml
  romfs/source/fighter/pfushigisou/motion/body/motion_patch.yaml
  romfs/source/fighter/sheik/motion/body/motion_patch.yaml
  romfs/source/fighter/simon/motion/body/motion_patch.yaml
  romfs/source/fighter/simon/motion/whip/motion_patch.yaml
Labels: engine, semver:patch

#2462 PK Freeze Effect Hotfix
  fighters/lucas/src/pkfire/acmd.rs
Labels: bug, aesthetics, semver:patch

#2461 Mini Misc
  dynamic/src/consts.rs
  fighters/captain/src/acmd/specials.rs
  fighters/donkey/src/acmd/smashes.rs
  fighters/gamewatch/src/acmd/aerials.rs
  fighters/gamewatch/src/status/mod.rs
  fighters/ken/src/acmd/aerials.rs
  fighters/ken/src/acmd/ground.rs
  fighters/ken/src/acmd/smashes.rs
  fighters/ken/src/acmd/specials/special_n.rs
  fighters/ken/src/hadoken/acmd.rs
  fighters/ken/src/opff.rs
  fighters/ken/src/status/special_n.rs
  fighters/koopa/src/acmd/aerials.rs
  fighters/koopa/src/breath/status.rs
  fighters/lucario/src/acmd/aerials.rs
  fighters/lucario/src/acmd/smashes.rs
  fighters/mewtwo/src/opff.rs
  fighters/mewtwo/src/status/mod.rs
  fighters/ness/src/acmd/ground.rs
  fighters/palutena/src/acmd/aerials.rs
  fighters/palutena/src/acmd/smashes.rs
  fighters/palutena/src/acmd/specials/special_n_b.rs
  fighters/palutena/src/acmd/specials/special_n_y.rs
  fighters/palutena/src/acmd/tilts.rs
  fighters/palutena/src/autoaimbullet/acmd.rs
  fighters/palutena/src/opff.rs
  fighters/palutena/src/reflectionboard/acmd.rs
  fighters/palutena/src/status/mod.rs
  fighters/palutena/src/status/special_n.rs
  fighters/peach/src/acmd/tilts.rs
  fighters/reflet/src/acmd/smashes.rs
  fighters/reflet/src/opff.rs
  fighters/ryu/src/acmd/aerials.rs
  fighters/ryu/src/acmd/ground.rs
  fighters/ryu/src/hadoken/acmd.rs
  fighters/shizue/src/acmd/specials.rs
  fighters/shizue/src/clayrocket/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/ken/motion/body/motion_patch.yaml
  romfs/source/fighter/ken/param/vl.prcxml
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
  romfs/source/fighter/lucario/motion/body/motion_patch.yaml
  romfs/source/fighter/palutena/motion/body/motion_patch.yaml
  romfs/source/fighter/palutena/param/vl.prcxml
  romfs/source/fighter/shulk/param/vl.prcxml
Labels: bug, character change, semver:patch, backroom approved, includes assets

#2406 Another Falco PR (feat. Fox)
  fighters/falco/src/acmd/aerials.rs
  fighters/falco/src/acmd/smashes.rs
  fighters/falco/src/acmd/specials.rs
  fighters/falco/src/acmd/tilts.rs
  fighters/falco/src/status/special_s.rs
  fighters/fox/src/status/special_s.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#2460 Recovery Adjustments
  fighters/common/src/function_hooks/lua_bind_hook/status.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/mario/src/opff.rs
  fighters/trail/src/status/special_s.rs
  romfs/source/fighter/common/param/common.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/common/param/fighter_param_motion.prcxml
  romfs/source/fighter/inkling/param/vl.prcxml
  romfs/source/fighter/koopajr/param/vl.prcxml
  romfs/source/fighter/pickel/param/vl.prcxml
  romfs/source/fighter/wario/param/vl.prcxml
Labels: character change, engine, semver:patch, backroom approved

#2439 Bayonetta Fixes + Adjustments
  dynamic/src/consts.rs
  fighters/bayonetta/src/acmd/aerials.rs
  fighters/bayonetta/src/acmd/ground.rs
  fighters/bayonetta/src/acmd/smashes.rs
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/acmd/throws.rs
  fighters/bayonetta/src/acmd/tilts.rs
  fighters/bayonetta/src/opff.rs
  fighters/bayonetta/src/specialn_bullet/acmd.rs
  fighters/bayonetta/src/status/attackair.rs
  fighters/bayonetta/src/status/jumpaerial.rs
  fighters/bayonetta/src/status/mod.rs
  fighters/bayonetta/src/status/specialairs.rs
  fighters/bayonetta/src/status/specialhi.rs
  fighters/bayonetta/src/status/specialn.rs
  fighters/bayonetta/src/status/specials.rs
  fighters/bayonetta/src/wickedweavearm/acmd.rs
  fighters/bayonetta/src/wickedweaveleg/acmd.rs
  fighters/rom_watch.txt
  romfs/agent_params.txt
  romfs/config.json
  romfs/source/fighter/bayonetta/motion/body/motion_patch.yaml
  romfs/source/fighter/bayonetta/param/hdr.xml
  romfs/source/fighter/bayonetta/param/vl.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2467 Revert Airdodge FAF Nerf
  romfs/source/fighter/common/param/fighter_param_motion.prcxml
Labels: character change, semver:patch, backroom approved

#2465 Mini Misc Fixes
  fighters/ken/src/acmd/smashes.rs
  fighters/koopajr/src/acmd/aerials.rs
  fighters/palutena/src/acmd/aerials.rs
  fighters/palutena/src/acmd/smashes.rs
  fighters/palutena/src/acmd/tilts.rs
  fighters/palutena/src/opff.rs
  romfs/source/fighter/jack/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2468 (Even More) Copy Ability Adjustments
  fighters/kirby/src/opff/copy.rs
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2466 Wavu Fix
  fighters/common/src/general_statuses/dash.rs
Labels: character change, semver:patch, backroom approved

#2469 Misc Is Back Again
  fighters/common/src/function_hooks/attack.rs
  fighters/common/src/function_hooks/iceclimber.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/function_hooks/vtables/mod.rs
  fighters/common/src/function_hooks/vtables/ryu_shinkuhadoken.rs
  fighters/common/src/general_statuses/shield/guard_off/main.rs
  fighters/iceclimber/src/acmd/aerials.rs
  fighters/iceclimber/src/acmd/ground.rs
  fighters/iceclimber/src/acmd/other.rs
  fighters/iceclimber/src/acmd/smashes.rs
  fighters/iceclimber/src/acmd/specials.rs
  fighters/iceclimber/src/acmd/throws.rs
  fighters/iceclimber/src/acmd/tilts.rs
  fighters/iceclimber/src/lib.rs
  fighters/iceclimber/src/status/mod.rs
  fighters/ken/src/acmd/finals.rs
  fighters/ken/src/acmd/specials/special_hi.rs
  fighters/ken/src/acmd/specials/special_s.rs
  fighters/ken/src/status/finals.rs
  fighters/ken/src/status/mod.rs
  fighters/ken/src/status/special_lw.rs
  fighters/ken/src/status/special_s.rs
  fighters/kirby/src/status/mod.rs
  fighters/kirby/src/status/palutena_special_n.rs
  fighters/littlemac/src/acmd/specials.rs
  fighters/lucario/src/acmd/specials.rs
  fighters/lucina/src/acmd/specials/mod.rs
  fighters/mario/src/acmd/specials.rs
  fighters/marth/src/acmd/specials/mod.rs
  fighters/palutena/src/status/mod.rs
  fighters/palutena/src/status/special_n.rs
  fighters/palutena/src/status/special_s.rs
  fighters/reflet/src/acmd/specials.rs
  fighters/ryu/src/acmd/finals.rs
  fighters/ryu/src/acmd/specials/special_hi.rs
  fighters/ryu/src/status/finals.rs
  fighters/samus/src/acmd/specials.rs
  fighters/samusd/src/acmd/specials.rs
  fighters/wario/src/acmd/aerials.rs
  fighters/wario/src/opff.rs
  fighters/wario/src/status/special_n.rs
  romfs/source/fighter/common/hdr/param/common.xml
  romfs/source/fighter/common/param/battle_object.prcxml
  romfs/source/fighter/common/param/common.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/lucario/motion/body/motion_patch.yaml
  romfs/source/fighter/nana/param/vl.prcxml
  romfs/source/fighter/popo/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2450 Greninja Down B - Substitute
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/item/doll.rs
  fighters/common/src/function_hooks/item/mod.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/function_hooks/vtables/gekkouga.rs
  fighters/common/src/function_hooks/vtables/mod.rs
  fighters/gekkouga/src/acmd/specials.rs
  fighters/gekkouga/src/lib.rs
  fighters/gekkouga/src/opff.rs
  fighters/gekkouga/src/status.rs
  fighters/gekkouga/src/status/special_lw.rs
  fighters/gekkouga/src/status/special_lw_jump.rs
  romfs/source/fighter/gekkouga/motion/body/motion_patch.yaml
  romfs/source/fighter/gekkouga/param/vl.prcxml
  utils/src/modules/var.rs
Labels: character change, semver:patch, backroom approved, includes assets

#2471 Substitute Hotfix
  fighters/gekkouga/src/acmd/specials.rs
Labels: bug, semver:patch

#2472 Daisy- Jump Momentum Fix
  fighters/daisy/src/status/attack_air.rs
Labels: bug, semver:patch

#2474 A Couple Things
  fighters/bayonetta/src/wickedweavearm/acmd.rs
  fighters/bayonetta/src/wickedweaveleg/acmd.rs
  fighters/captain/src/acmd/specials.rs
  fighters/captain/src/status/mod.rs
  fighters/captain/src/status/special_s.rs
  fighters/donkey/src/acmd/specials.rs
  fighters/koopa/src/status/special_hi.rs
Labels: character change, semver:patch, backroom approved

#2476 Whitespace update
  fighters/palutena/src/opff.rs
Labels: bug, enhancement, semver:patch
