Repository HDR-Development/HewDraw-Remix, pull requests merged in 2024-01, with the labels that each got.

#2153 Steve - mining bugfixes
  dynamic/src/consts.rs
  fighters/kirby/src/opff.rs
  fighters/pickel/src/material_table.rs
  fighters/pickel/src/status.rs
Labels: bug, semver:patch

#2154 Various Fixes
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/buddy/src/status.rs
  fighters/krool/src/acmd/specials.rs
  fighters/krool/src/status/special_hi.rs
  fighters/littlemac/src/opff.rs
  fighters/miifighter/src/acmd/specials.rs
  fighters/richter/src/opff.rs
  fighters/richter/src/status/attacks3.rs
  fighters/simon/src/opff.rs
  fighters/simon/src/status/attacks3.rs
  fighters/zelda/src/opff.rs
  romfs/source/fighter/krool/param/hdr.xml
  romfs/source/fighter/krool/param/vl.prcxml
Labels: bug, semver:patch

#2155 Fix Tags Releasing in Draft
  .github/workflows/build_beta.yml
Labels: bug, infrastructure, semver:patch

#2158 add CSS controls editing
  Cargo.toml
  src/controls.rs
  src/controls/css.rs
  src/controls/submenu.rs
  src/controls/swkbd.rs
  src/lib.rs
Labels: enhancement, semver:feature

#2130 Sheik adjustments
  fighters/sheik/src/acmd/aerials.rs
  fighters/sheik/src/acmd/specials.rs
  romfs/source/fighter/sheik/motion/body/motion_patch.yaml
Labels: character change, semver:patch, includes assets

#2164 feat: Add wario land and add back pirate ship
  fighters/common/src/function_hooks/stage_hazards.rs
Labels: semver:patch, stages

#2151 Mewtwo Adjustments
  fighters/mewtwo/src/acmd/aerials.rs
  fighters/mewtwo/src/acmd/ground.rs
  fighters/mewtwo/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/mewtwo/motion/body/motion_patch.yaml
  romfs/source/fighter/mewtwo/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2136 Banjo Adjustments
  fighters/buddy/src/acmd/aerials.rs
  fighters/buddy/src/acmd/other.rs
  fighters/buddy/src/acmd/smashes.rs
  fighters/buddy/src/acmd/specials.rs
  fighters/buddy/src/acmd/tilts.rs
  fighters/buddy/src/status.rs
  romfs/source/fighter/buddy/param/vl.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#2150 Killager
  fighters/murabito/src/acmd/aerials.rs
  fighters/murabito/src/acmd/ground.rs
  fighters/murabito/src/acmd/other.rs
  fighters/murabito/src/acmd/smashes.rs
  fighters/murabito/src/acmd/specials.rs
  fighters/murabito/src/lib.rs
  fighters/murabito/src/opff.rs
  romfs/source/fighter/murabito/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2169 Hitlag Buffer Improvements
  fighters/common/src/function_hooks/controls.rs
Labels: engine, semver:patch

#2156 Palutena Paralyze Attack fix
  fighters/palutena/src/acmd/other.rs
Labels: bug, semver:patch

#2162 Getup attack adjustments
  fighters/common/src/function_hooks/attack.rs
Labels: engine, semver:patch

#2180 Actionable upB freefall visual improvement
  romfs/source/fighter/buddy/motion/body/motion_patch.yaml
  romfs/source/fighter/demon/motion/body/motion_patch.yaml
  romfs/source/fighter/elight/motion/body/motion_patch.yaml
Labels: aesthetics, semver:patch

#2173 Ganondorf.
  fighters/ganon/src/acmd/ground.rs
  fighters/ganon/src/acmd/specials.rs
  fighters/ganon/src/acmd/tilts.rs
  fighters/ganon/src/lib.rs
  fighters/ganon/src/status.rs
  fighters/ganon/src/status/attack_lw3.rs
  fighters/ganon/src/status/special_air_s_catch.rs
  fighters/ganon/src/vtable_hook.rs
  romfs/source/fighter/common/param/common.prcxml
  romfs/source/fighter/ganon/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#2186 Diddy - no cap mode
  dynamic/src/consts.rs
  fighters/diddy/src/acmd/other.rs
  fighters/diddy/src/opff.rs
Labels: aesthetics, semver:patch

#2188 Fix Side Taunt charging Mega Buster
  fighters/rockman/src/vtable_hook.rs
Labels: bug, semver:patch

#2183 Incineroar recovery adjustment
  fighters/gaogaen/src/opff.rs
Labels: character change, semver:patch, backroom approved

#2191 Disable reverse hits on dash attacks
  fighters/brave/src/acmd/ground.rs
  fighters/buddy/src/acmd/ground.rs
  fighters/captain/src/acmd/ground.rs
  fighters/chrom/src/acmd/ground.rs
  fighters/daisy/src/acmd/ground.rs
  fighters/duckhunt/src/acmd/ground.rs
  fighters/eflame/src/acmd/ground.rs
  fighters/elight/src/acmd/ground.rs
  fighters/jack/src/acmd/ground.rs
  fighters/koopa/src/acmd/ground.rs
  fighters/krool/src/acmd/ground.rs
  fighters/lucina/src/acmd/ground.rs
  fighters/mario/src/acmd/ground.rs
  fighters/marth/src/acmd/ground.rs
  fighters/metaknight/src/acmd/ground.rs
  fighters/mewtwo/src/acmd/ground.rs
  fighters/miigunner/src/acmd/ground.rs
  fighters/miiswordsman/src/acmd/ground.rs
  fighters/pikachu/src/acmd/ground.rs
  fighters/richter/src/acmd/ground.rs
  fighters/roy/src/acmd/ground.rs
  fighters/samus/src/acmd/ground.rs
  fighters/shulk/src/acmd/ground.rs
  fighters/szerosuit/src/acmd/ground.rs
  fighters/toonlink/src/acmd/ground.rs
  fighters/wiifit/src/acmd/ground.rs
  fighters/wolf/src/acmd/ground.rs
  fighters/yoshi/src/acmd/ground.rs
  fighters/younglink/src/acmd/ground.rs
  fighters/zelda/src/acmd/ground.rs
Labels: character change, semver:patch, backroom approved

#2204 (even more) Copy Ability Adjustments
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/kirby/src/acmd/copyspecials.rs
  fighters/kirby/src/lib.rs
  fighters/kirby/src/opff.rs
  fighters/kirby/src/status.rs
  fighters/kirby/src/status/diddy_special_n_cancel.rs
  fighters/packun/src/acmd/other.rs
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2209 ROB 2.5: Meter and More
  dynamic/src/consts.rs
  dynamic/src/ui.rs
  fighters/robot/src/acmd/aerials.rs
  fighters/robot/src/acmd/specials.rs
  fighters/robot/src/lib.rs
  fighters/robot/src/opff.rs
  fighters/robot/src/status.rs
  utils/src/ui.rs
  utils/src/ui/robot_meter.rs
Labels: bug, aesthetics, character change, semver:patch, backroom approved

#2166 Float Input Adjustment + Mewtwo Fixes
  fighters/common/src/opff/floats.rs
  fighters/mewtwo/src/opff.rs
Labels: bug, engine, semver:patch

#2208 Wolf Upair Rework
  fighters/wolf/src/acmd/aerials.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#2199 Remove wallclings
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved

#2167 Misc adjustments 4
  dynamic/src/consts.rs
  fighters/cloud/src/acmd/ground.rs
  fighters/demon/src/opff.rs
  fighters/kamui/src/acmd/other.rs
  fighters/kamui/src/acmd/specials.rs
  fighters/koopajr/src/acmd/specials.rs
  fighters/koopajr/src/opff.rs
  fighters/lucina/src/opff.rs
  fighters/lucina/src/status.rs
  fighters/richter/src/status/attacks3.rs
  fighters/robot/src/acmd/aerials.rs
  fighters/simon/src/status/attacks3.rs
Labels: bug, character change, semver:patch, backroom approved, includes assets

#2215 Fixes ordering of figher_param.prcxml entries
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: bug, semver:patch

#2190 Sonic Animations
  dynamic/src/consts.rs
  fighters/sonic/src/acmd/specials.rs
  fighters/sonic/src/status.rs
  fighters/sonic/src/status/special_n_hit.rs
  romfs/source/fighter/sonic/motion/body/motion_patch.yaml
Labels: aesthetics, semver:patch, includes assets

#2170 DJC Leniency
  fighters/common/src/djc.rs
  fighters/peach/src/status/attack_air.rs
  fighters/trail/src/status/attack_air.rs
Labels: character change, engine, semver:patch, backroom approved, includes assets

#2185 Lucas Tweaks
  dynamic/src/consts.rs
  fighters/lucas/src/acmd/aerials.rs
  fighters/lucas/src/acmd/ground.rs
  fighters/lucas/src/acmd/other.rs
  fighters/lucas/src/acmd/specials.rs
  fighters/lucas/src/acmd/throws.rs
  fighters/lucas/src/acmd/tilts.rs
  fighters/lucas/src/status.rs
  romfs/source/fighter/lucas/motion/body/motion_patch.yaml
  romfs/source/fighter/lucas/param/vl.prcxml
Labels: aesthetics, character change, semver:patch, backroom approved, includes assets

#105 Arsene Rework
  dynamic/src/consts.rs
  dynamic/src/ext.rs
  fighters/common/src/function_hooks/fighterspecializer/jack.rs
  fighters/common/src/function_hooks/fighterspecializer/mod.rs
  fighters/common/src/function_hooks/misc.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/jack/src/acmd/aerials.rs
  fighters/jack/src/acmd/specials.rs
  fighters/jack/src/lib.rs
  fighters/jack/src/opff.rs
  fighters/jack/src/status.rs
  fighters/jack/src/status/dispatch.rs
  fighters/jack/src/status/doyle.rs
  fighters/jack/src/status/special_lw.rs
  fighters/jack/src/status/summon.rs
  romfs/source/fighter/jack/motion/body/motion_patch.yaml
  romfs/source/fighter/jack/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#2216 DJC PR Hotfix (sry)
  fighters/common/src/djc.rs
  fighters/trail/src/status/attack_air.rs
Labels: bug, semver:patch

#2068 Bayonetta Adjustments (Revisited)
  dynamic/src/consts.rs
  fighters/bayonetta/src/acmd/aerials.rs
  fighters/bayonetta/src/acmd/ground.rs
  fighters/bayonetta/src/acmd/other.rs
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/acmd/tilts.rs
  fighters/bayonetta/src/opff.rs
  fighters/bayonetta/src/status/attack.rs
  fighters/bayonetta/src/status/attackair.rs
  fighters/bayonetta/src/status/jumpaerial.rs
  fighters/bayonetta/src/status/mod.rs
  fighters/bayonetta/src/status/specialairs.rs
  fighters/bayonetta/src/status/specials.rs
  fighters/common/src/function_hooks/change_status.rs
  romfs/source/fighter/bayonetta/motion/body/motion_patch.yaml
  romfs/source/fighter/bayonetta/param/vl.prcxml
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2171 Peach Parasol Improvements
  fighters/peach/src/opff.rs
  fighters/peach/src/status/mod.rs
  fighters/peach/src/status/special_hi.rs
Labels: bug, character change, semver:patch, backroom approved

#2168 Lucina Adjustments
  fighters/lucina/src/acmd/aerials.rs
  fighters/lucina/src/acmd/ground.rs
  fighters/lucina/src/acmd/smashes.rs
  fighters/lucina/src/acmd/tilts.rs
  fighters/lucina/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/lucina/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#2203 Little Mac Rework!!
  dynamic/src/consts.rs
  fighters/common/src/misc.rs
  fighters/kirby/src/opff.rs
  fighters/kirby/src/status/littlemac_special_n_cancel.rs
  fighters/littlemac/src/acmd/aerials.rs
  fighters/littlemac/src/acmd/ground.rs
  fighters/littlemac/src/acmd/smashes.rs
  fighters/littlemac/src/acmd/specials.rs
  fighters/littlemac/src/acmd/tilts.rs
  fighters/littlemac/src/lib.rs
  fighters/littlemac/src/opff.rs
  fighters/littlemac/src/status.rs
  fighters/littlemac/src/status/special_lw.rs
  fighters/littlemac/src/status/special_lw_cancel.rs
  fighters/littlemac/src/status/special_n.rs
  fighters/littlemac/src/vtable_hook.rs
  romfs/source/fighter/littlemac/motion/body/motion_patch.yaml
  romfs/source/fighter/littlemac/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#2217 Ganondorf. 2.
  fighters/ganon/src/acmd/aerials.rs
  fighters/ganon/src/acmd/ground.rs
  fighters/ganon/src/acmd/specials.rs
  fighters/ganon/src/acmd/tilts.rs
  fighters/ganon/src/opff.rs
  romfs/source/fighter/ganon/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2222 Revert Joker Grappling Hook
  fighters/jack/src/acmd/specials.rs
Labels: character change, semver:patch, backroom approved

#2223 Revert Joker Grappling Hook 2
  fighters/jack/src/opff.rs
Labels: character change, semver:patch, backroom approved

#2225 DJC fix pr fix
  fighters/common/src/djc.rs
  fighters/peach/src/status/attack_air.rs
  fighters/trail/src/status/attack_air.rs
Labels: semver:patch

#2007 Sephiroth changes (actually for real this time)
  dynamic/src/consts.rs
  fighters/edge/src/acmd/aerials.rs
  fighters/edge/src/acmd/ground.rs
  fighters/edge/src/acmd/other.rs
  fighters/edge/src/acmd/smashes.rs
  fighters/edge/src/acmd/specials.rs
  fighters/edge/src/acmd/tilts.rs
  fighters/edge/src/lib.rs
  fighters/edge/src/opff.rs
  fighters/edge/src/status/special_hi.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/edge/motion/body/motion_patch.yaml
  romfs/source/fighter/edge/param/hdr.xml
  romfs/source/fighter/edge/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#2224 ICs DSmash & Grabs
  fighters/nana/src/acmd/other.rs
  fighters/nana/src/acmd/smashes.rs
  fighters/popo/src/acmd/other.rs
  fighters/popo/src/acmd/smashes.rs
Labels: character change, semver:patch, backroom approved, includes assets

#2161 Small Ledge Refactor
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/function_hooks/init_settings.rs
  fighters/common/src/function_hooks/ledges.rs
  fighters/common/src/general_statuses/cliff.rs
  fighters/common/src/lib.rs
  fighters/common/src/opff/ledges.rs
Labels: engine, semver:patch

#2175 Mario Tweaks
  fighters/mario/src/acmd/aerials.rs
  fighters/mario/src/acmd/ground.rs
  fighters/mario/src/acmd/other.rs
  fighters/mario/src/acmd/smashes.rs
  fighters/mario/src/acmd/specials.rs
  fighters/mario/src/acmd/throws.rs
  fighters/mario/src/acmd/tilts.rs
  fighters/mario/src/opff.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
  romfs/source/fighter/mario/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2218 Held-Float Re-Add (with delay,sry)
  fighters/common/src/opff/floats.rs
Labels: semver:patch

#2226 Ganondorf. 2.5.
  fighters/ganon/src/acmd/ground.rs
Labels: character change, semver:patch, backroom approved

#2211 Dark Samus Stat Adjustment + Nair Angle
  fighters/samusd/src/acmd/aerials.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/samusd/param/vl.prcxml
Labels: character change, semver:patch, backroom approved

#2221 Remove MSF unused motion entries
  romfs/source/fighter/miiswordsman/motion/body/motion_patch.yaml
Labels: semver:patch

#2234 Revert "reimplement can canceling"
  fighters/murabito/src/acmd/specials.rs
  fighters/murabito/src/opff.rs
Labels: bug, semver:patch

#2233 Lucario Meter Nerfs
  fighters/common/src/function_hooks/aura.rs
  fighters/lucario/src/acmd/aerials.rs
  fighters/lucario/src/acmd/other.rs
  fighters/lucario/src/acmd/smashes.rs
  fighters/lucario/src/acmd/specials.rs
  fighters/lucario/src/opff.rs
  fighters/lucario/src/status.rs
  romfs/source/fighter/lucario/param/hdr.xml
  romfs/source/fighter/lucario/param/vl.prcxml
  utils/src/ui/aura_meter.rs
Labels: character change, semver:patch, backroom approved
