Repository HDR-Development/HewDraw-Remix, pull requests merged in 2024-02, with the labels that each got.

#2232 Fox weight dependent shine/Upsmash FAF reduction. (slight weight adjustments)
  fighters/fox/src/acmd/smashes.rs
  fighters/fox/src/acmd/specials.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
Labels: bug, enhancement, good first issue, wontfix, infrastructure, aesthetics, character change, engine, crash, semver:patch, stages, for next beta, backroom approved, includes assets, discussion needed

#2206 Shield Mechanics Rewrite
  dynamic/src/consts.rs
  fighters/common/src/general_statuses/catch/mod.rs
  fighters/common/src/general_statuses/shield/fighter_status_guard/mod.rs
  fighters/common/src/general_statuses/shield/guard/end.rs
  fighters/common/src/general_statuses/shield/guard/exec.rs
  fighters/common/src/general_statuses/shield/guard/exit.rs
  fighters/common/src/general_statuses/shield/guard/init.rs
  fighters/common/src/general_statuses/shield/guard/main.rs
  fighters/common/src/general_statuses/shield/guard/mod.rs
  fighters/common/src/general_statuses/shield/guard/pre.rs
  fighters/common/src/general_statuses/shield/guard_damage/end.rs
  fighters/common/src/general_statuses/shield/guard_damage/exec.rs
  fighters/common/src/general_statuses/shield/guard_damage/exit.rs
  fighters/common/src/general_statuses/shield/guard_damage/init.rs
  fighters/common/src/general_statuses/shield/guard_damage/main.rs
  fighters/common/src/general_statuses/shield/guard_damage/pre.rs
  fighters/common/src/general_statuses/shield/guard_off/end.rs
  fighters/common/src/general_statuses/shield/guard_off/exit.rs
  fighters/common/src/general_statuses/shield/guard_off/init.rs
  fighters/common/src/general_statuses/shield/guard_off/main.rs
  fighters/common/src/general_statuses/shield/guard_off/mod.rs
  fighters/common/src/general_statuses/shield/guard_off/pre.rs
  fighters/common/src/general_statuses/shield/guard_on/end.rs
  fighters/common/src/general_statuses/shield/guard_on/exec.rs
  fighters/common/src/general_statuses/shield/guard_on/exit.rs
  fighters/common/src/general_statuses/shield/guard_on/init.rs
  fighters/common/src/general_statuses/shield/guard_on/main.rs
  fighters/common/src/general_statuses/shield/guard_on/mod.rs
  fighters/common/src/general_statuses/shield/guard_on/pre.rs
  fighters/common/src/general_statuses/shield/misc.rs
  fighters/common/src/general_statuses/shield/mod.rs
Labels: engine, semver:patch

#2176 Doc Tweaks
  fighters/mariod/src/acmd/aerials.rs
  fighters/mariod/src/acmd/ground.rs
  fighters/mariod/src/acmd/smashes.rs
  fighters/mariod/src/acmd/specials.rs
  fighters/mariod/src/acmd/throws.rs
  fighters/mariod/src/acmd/tilts.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/mariod/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2230 DJC hotfix's fix pr of the fix pr's fix pr
  fighters/common/src/djc.rs
  fighters/peach/src/status/attack_air.rs
  fighters/trail/src/status/attack_air.rs
Labels: bug, semver:patch

#2240 Bayonetta Improvements: Jab, Side and Up Special
  dynamic/src/consts.rs
  fighters/bayonetta/src/acmd/ground.rs
  fighters/bayonetta/src/acmd/specials.rs
  fighters/bayonetta/src/opff.rs
  fighters/bayonetta/src/status/specials.rs
  romfs/source/fighter/bayonetta/motion/body/motion_patch.yaml
Labels: semver:patch

#2229 Pacman adjustments
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/pacman/src/acmd/aerials.rs
Labels: character change, semver:patch, backroom approved, includes assets

#2238 Sora Re:Coded HD 358/2.8 Final Mix
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/change_status.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/trail/src/acmd/aerials.rs
  fighters/trail/src/acmd/ground.rs
  fighters/trail/src/acmd/smashes.rs
  fighters/trail/src/acmd/specials.rs
  fighters/trail/src/acmd/throws.rs
  fighters/trail/src/acmd/tilts.rs
  fighters/trail/src/opff.rs
  fighters/trail/src/status.rs
  fighters/trail/src/status/special_n.rs
  fighters/trail/src/status/special_s.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/trail/motion/body/motion_patch.yaml
  romfs/source/fighter/trail/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2245 Cloud Evaluation
  fighters/cloud/src/acmd/aerials.rs
  fighters/cloud/src/acmd/ground.rs
  fighters/cloud/src/acmd/smashes.rs
  fighters/cloud/src/acmd/tilts.rs
  romfs/source/fighter/cloud/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2246 Fix shield plat drop priority
  fighters/common/src/general_statuses/shield/misc.rs
Labels: bug, engine, semver:patch

#2243 Copy Ability Fixes
  fighters/kirby/src/opff.rs
  fighters/kirby/src/status.rs
Labels: bug, crash, semver:patch

#2163 Duck Hunt Buff
  fighters/captain/src/acmd/aerials.rs
  fighters/duckhunt/src/acmd/aerials.rs
  fighters/duckhunt/src/acmd/ground.rs
  fighters/duckhunt/src/acmd/other.rs
  fighters/duckhunt/src/acmd/smashes.rs
  fighters/duckhunt/src/acmd/specials.rs
  fighters/duckhunt/src/acmd/tilts.rs
  fighters/duckhunt/src/status/attacks3.rs
  fighters/duckhunt/src/status/mod.rs
  fighters/duckhunt/src/status/special_n.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/duckhunt/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#2212 Ness Tweaks: QoL
  dynamic/src/consts.rs
  fighters/ness/src/acmd/aerials.rs
  fighters/ness/src/acmd/ground.rs
  fighters/ness/src/acmd/other.rs
  fighters/ness/src/acmd/specials.rs
  fighters/ness/src/acmd/tilts.rs
  fighters/ness/src/status.rs
  romfs/source/fighter/ness/motion/body/motion_patch.yaml
  romfs/source/fighter/ness/param/vl.prcxml
Labels: character change, semver:patch, backroom approved, includes assets

#2259 Olimar Bugfixes
  dynamic/src/consts.rs
  fighters/pikmin/src/pikmin/mod.rs
  fighters/pikmin/src/pikmin/status.rs
  romfs/source/fighter/pikmin/param/vl.prcxml
Labels: bug, semver:patch

#2242 feat: Remove need for building PRCs at compile time
  Cargo.toml
  build.rs
  crates/build-tools/Cargo.toml
  crates/build-tools/src/lib.rs
  crates/build-tools/src/main.rs
  hdr-macros/src/lib.rs
  romfs/agent_params.txt
  romfs/config.json
  romfs/rom_watch.txt
  scripts/pkgutil.py
  utils/src/modules/param.rs
Labels: semver:patch

#2253 feat: Revert sheik U-Air back to multihit
  fighters/sheik/src/acmd/aerials.rs
  romfs/source/fighter/sheik/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2250 WuBoy Misc 2
  fighters/marth/src/acmd/specials.rs
  fighters/rockman/src/status/rockbuster/shoot_jump_squat.rs
  fighters/rockman/src/vtable_hook.rs
  fighters/sheik/src/acmd/aerials.rs
  romfs/source/fighter/rockman/motion/body/motion_patch.yaml
  romfs/source/fighter/sonic/motion/body/motion_patch.yaml
Labels: bug, semver:patch

#2256 Dark Pit side taunt fix
  fighters/pitb/src/acmd/other.rs
Labels: aesthetics, semver:patch, includes assets

#2247 Re-Disable 1f Float Glitch
  fighters/common/src/opff/floats.rs
Labels: bug, semver:patch

#2255 Sora run loop fix
  fighters/trail/src/acmd/other.rs
  fighters/trail/src/acmd/smashes.rs
  fighters/trail/src/opff.rs
Labels: aesthetics, semver:patch, includes assets

#2219 Kirby KO Punch + Little Mac adjustments
  dynamic/src/consts.rs
  fighters/common/src/misc.rs
  fighters/kirby/src/acmd/copyspecials.rs
  fighters/kirby/src/opff.rs
  fighters/kirby/src/status.rs
  fighters/kirby/src/status/littlemac_special_n.rs
  fighters/kirby/src/status/littlemac_special_n_cancel.rs
  fighters/littlemac/src/acmd/ground.rs
  fighters/littlemac/src/acmd/tilts.rs
  fighters/littlemac/src/opff.rs
  fighters/littlemac/src/vtable_hook.rs
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#2262 Sephiroth specials rework
  dynamic/src/consts.rs
  fighters/edge/src/acmd/aerials.rs
  fighters/edge/src/acmd/ground.rs
  fighters/edge/src/acmd/other.rs
  fighters/edge/src/acmd/specials.rs
  fighters/edge/src/acmd/throws.rs
  fighters/edge/src/acmd/tilts.rs
  fighters/edge/src/opff.rs
  fighters/edge/src/status/edge_fire_fly.rs
  fighters/edge/src/status/mod.rs
  fighters/edge/src/status/special_n.rs
  fighters/kirby/src/acmd/copyspecials.rs
  fighters/kirby/src/status.rs
  fighters/kirby/src/status/edge_special_n.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/edge/motion/body/motion_patch.yaml
  romfs/source/fighter/edge/param/hdr.xml
  romfs/source/fighter/edge/param/vl.prcxml
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved, includes assets

#2264 Cleanups and Corrections
  fighters/captain/src/acmd/aerials.rs
  fighters/cloud/src/acmd/tilts.rs
  fighters/common/src/function_hooks/set_fighter_status_data.rs
  fighters/diddy/src/acmd/aerials.rs
  fighters/duckhunt/src/acmd/smashes.rs
  fighters/falco/src/acmd/specials.rs
  fighters/fox/src/acmd/specials.rs
  fighters/gaogaen/src/acmd/specials.rs
  fighters/kirby/src/acmd/aerials.rs
  fighters/kirby/src/acmd/copyspecials.rs
  fighters/kirby/src/acmd/other.rs
  fighters/kirby/src/acmd/tilts.rs
  fighters/mario/src/status.rs
  fighters/mariod/src/acmd/tilts.rs
  fighters/palutena/src/status/special_n.rs
  fighters/ridley/src/status/special_n.rs
  fighters/rockman/src/status.rs
  fighters/trail/src/acmd/aerials.rs
  fighters/trail/src/acmd/smashes.rs
  fighters/wolf/src/acmd/specials.rs
  romfs/source/fighter/cloud/motion/body/motion_patch.yaml
  romfs/source/fighter/duckhunt/motion/body/motion_patch.yaml
  romfs/source/fighter/lucas/motion/body/motion_patch.yaml
  romfs/source/fighter/yoshi/param/vl.prcxml
Labels: bug, aesthetics, character change, semver:patch, backroom approved

#2266 suicide pact with wuboy
  dynamic/src/util.rs
  fighters/build.rs
  fighters/common/src/function_hooks/attack.rs
  fighters/common/src/function_hooks/aura.rs
  fighters/common/src/function_hooks/camera.rs
  fighters/common/src/function_hooks/collision.rs
  fighters/common/src/function_hooks/controls.rs
  fighters/common/src/function_hooks/energy/control.rs
  fighters/common/src/function_hooks/energy/mod.rs
  fighters/common/src/function_hooks/energy/motion.rs
  fighters/common/src/function_hooks/energy/stop.rs
  fighters/common/src/function_hooks/fighterspecializer/jack.rs
  fighters/common/src/function_hooks/fighterspecializer/pickel.rs
  fighters/common/src/function_hooks/hitstun.rs
  fighters/common/src/function_hooks/jumps.rs
  fighters/common/src/function_hooks/misc.rs
  fighters/common/src/function_hooks/mod.rs
  fighters/common/src/function_hooks/shotos.rs
  fighters/common/src/function_hooks/sound.rs
  fighters/common/src/function_hooks/stage_hazards.rs
  fighters/common/src/misc.rs
  fighters/donkey/src/status/link_event.rs
  fighters/eflame/src/lib.rs
  fighters/elight/src/lib.rs
  fighters/ganon/src/vtable_hook.rs
  fighters/inkling/src/opff.rs
  fighters/krool/src/lib.rs
  fighters/krool/src/vtable_hook.rs
  fighters/littlemac/src/vtable_hook.rs
  fighters/nana/src/lib.rs
  fighters/pickel/src/material_table.rs
  fighters/pickel/src/status.rs
  fighters/rockman/src/vtable_hook.rs
  fighters/wolf/src/status/special_s.rs
  scripts/full_package.py
  src/controls.rs
  src/controls/css.rs
  src/lib.rs
  src/lua.rs
  src/online.rs
  src/random.rs
  utils/src/modules/meter.rs
  utils/src/modules/param.rs
  utils/src/offsets.rs
  utils/src/ui.rs
Labels: bug, enhancement, good first issue, infrastructure, aesthetics, character change, engine, crash, semver:feature, stages, backroom approved

#2269 Suicide Pact with Myself
  fighters/littlemac/src/vtable_hook.rs
  src/controls.rs
Labels: bug, crash, semver:patch

#2270 More offset fixes
  fighters/common/src/function_hooks/controls.rs
  src/lua.rs
  src/online.rs
Labels: crash, semver:patch

#2273 Fixed Offsets Again
  src/online.rs
Labels: bug, crash, semver:patch

#2275 Random Hotfixes
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/attack.rs
  fighters/common/src/function_hooks/fighterspecializer/jack.rs
  fighters/common/src/function_hooks/get_param.rs
  fighters/common/src/function_hooks/hitstun.rs
  fighters/common/src/function_hooks/shotos.rs
  fighters/common/src/function_hooks/stage_hazards.rs
  fighters/common/src/general_statuses/shield/misc.rs
  fighters/lucario/src/status/special_hi.rs
  fighters/marth/src/acmd/aerials.rs
  fighters/pikmin/src/pikmin/acmd/specials.rs
  fighters/pikmin/src/pikmin/status.rs
Labels: bug, semver:patch

#2278 Chrom Adjustments
  dynamic/src/consts.rs
  fighters/chrom/src/acmd/aerials.rs
  fighters/chrom/src/acmd/ground.rs
  fighters/chrom/src/acmd/smashes.rs
  fighters/chrom/src/acmd/specials.rs
  fighters/chrom/src/acmd/tilts.rs
  fighters/chrom/src/opff.rs
  fighters/common/src/opff/fe.rs
  romfs/source/fighter/chrom/motion/body/motion_patch.yaml
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/kirby/motion/body/motion_patch.yaml
Labels: character change, semver:patch, backroom approved

#2280 Syntax Hotfix
  fighters/chrom/src/acmd/specials.rs
Labels: bug, semver:patch

#2282 Fix full_package.py
  scripts/full_package.py
Labels: semver:patch

#2283 Adds back c stick condition for tap jump shorthop
  fighters/common/src/general_statuses/jumpsquat.rs
Labels: bug, semver:patch

#2284 Smashline 2 Fixes
  fighters/buddy/src/opff.rs
  fighters/common/src/general_statuses/airdodge.rs
  fighters/common/src/general_statuses/attack/attackdash.rs
  fighters/common/src/general_statuses/attack/attackx4.rs
  fighters/common/src/general_statuses/damageflyreflect.rs
  fighters/common/src/general_statuses/jump.rs
  fighters/common/src/general_statuses/jumpsquat.rs
  fighters/common/src/general_statuses/run.rs
  fighters/common/src/general_statuses/turn.rs
  fighters/common/src/general_statuses/walk.rs
  fighters/inkling/src/opff.rs
  fighters/koopa/src/opff.rs
  fighters/lucario/src/status/attack_air.rs
  fighters/lucario/src/status/special_hi.rs
  fighters/palutena/src/opff.rs
  fighters/pickel/src/status.rs
  fighters/tantan/src/status.rs
  fighters/wolf/src/status/special_s.rs
Labels: semver:patch

#2287 Smashline 2 Fixes (Part 2)
  dynamic/src/consts.rs
  fighters/common/src/function_hooks/hitstun.rs
  fighters/common/src/function_hooks/stage_hazards.rs
  fighters/common/src/general_statuses/airdodge.rs
  fighters/common/src/general_statuses/attack/attackx4.rs
  fighters/common/src/general_statuses/jump.rs
  fighters/common/src/general_statuses/mod.rs
  fighters/common/src/general_statuses/run.rs
  fighters/common/src/general_statuses/turn.rs
  fighters/common/src/misc.rs
  fighters/gamewatch/src/status.rs
  fighters/mario/src/acmd/other.rs
  fighters/mario/src/opff.rs
Labels: bug, semver:patch

#2288 Smashline 2 Fixes Part 3
  Cargo.toml
  fighters/koopag/Cargo.toml
  fighters/koopag/src/opff.rs
  fighters/rosetta/src/status.rs
  fighters/ryu/src/status.rs
Labels: bug, semver:patch
