Repository HDR-Development/HewDraw-Remix, pull requests merged in 2025-09, with the labels that each got.

#2596 Chrom Special Trails
  fighters/chrom/src/acmd/specials/special_hi.rs
  fighters/chrom/src/acmd/specials/special_lw.rs
  fighters/chrom/src/acmd/specials/special_n.rs
  fighters/chrom/src/acmd/specials/special_s/special_s2.rs
Labels: aesthetics, semver:patch, includes assets

#2600 v0.49.3‐pre‐release
  fighters/chrom/src/acmd/specials/special_s/special_s2.rs
  fighters/chrom/src/acmd/specials/special_s/special_s3.rs
  fighters/chrom/src/acmd/specials/special_s/special_s4.rs
  fighters/dolly/src/status/special_lw.rs
  fighters/edge/src/fire/status.rs
  fighters/edge/src/flare1/status.rs
  fighters/eflame/src/acmd/specials.rs
  fighters/eflame/src/esword/acmd.rs
  fighters/elight/src/acmd/specials.rs
  fighters/elight/src/exprosiveshot/acmd.rs
  fighters/elight/src/exprosiveshot/status/fly.rs
  fighters/elight/src/status/special_hi.rs
  fighters/elight/src/status/special_hi_jump.rs
  fighters/elight/src/status/special_s_forward.rs
  fighters/kirby/src/acmd/tilts.rs
  fighters/kirby/src/opff.rs
  fighters/kirby/src/status/copy/richter_special_n.rs
  fighters/kirby/src/status/special_hi.rs
  fighters/koopa/src/acmd/specials/special_hi.rs
  fighters/koopa/src/acmd/specials/special_lw.rs
  fighters/koopa/src/acmd/tilts.rs
  fighters/koopa/src/opff.rs
  fighters/koopa/src/status/attack_lw3.rs
  fighters/koopa/src/status/mod.rs
  fighters/metaknight/src/opff.rs
  fighters/metaknight/src/status/mod.rs
  fighters/metaknight/src/status/special_lw.rs
  fighters/packun/src/opff.rs
  fighters/richter/src/status/special_n.rs
  fighters/rom_watch.txt
  romfs/agent_params.txt
  romfs/config.json
  romfs/source/fighter/cloud/param/vl.prcxml
  romfs/source/fighter/elight/param/vl.prcxml
  romfs/source/fighter/kirby/param/hdr.xml
  romfs/source/fighter/koopa/motion/body/motion_patch.yaml
  romfs/source/fighter/metaknight/param/hdr.xml
  romfs/source/fighter/metaknight/param/vl.prcxml
  romfs/source/ui/script_patch/common/stage_select_actor3.tourney.lua
Labels: bug, aesthetics, character change, semver:patch, stages, balance approved, includes assets

#2601 v0.49.4-pre-release (hotfix)
  fighters/chrom/src/acmd/specials/special_hi.rs
  fighters/chrom/src/acmd/specials/special_lw.rs
  fighters/chrom/src/acmd/specials/special_n.rs
  fighters/chrom/src/acmd/specials/special_s/special_s2.rs
Labels: bug, semver:patch

#2607 v0.49.6 hotfix
  dynamic/src/consts.rs
  fighters/bayonetta/src/status/specialn.rs
  fighters/ganon/src/acmd/specials.rs
  fighters/kirby/src/acmd/copy.rs
  fighters/kirby/src/acmd/copy/bayonetta.rs
  fighters/kirby/src/opff.rs
  fighters/kirby/src/status/copy/bayonetta_special_n_cancel.rs
  fighters/kirby/src/status/special_lw.rs
Labels: bug, character change, semver:patch, balance approved
