Repository HDR-Development/HewDraw-Remix, pull requests merged in 2025-08, with the labels that each got.

#2567 Link Adjustments Follow-up
  fighters/link/src/acmd/aerials.rs
  fighters/link/src/acmd/ground.rs
  fighters/link/src/acmd/other.rs
  fighters/link/src/acmd/smashes.rs
  fighters/link/src/acmd/specials.rs
  fighters/link/src/acmd/throws.rs
  fighters/link/src/acmd/tilts.rs
  romfs/source/fighter/common/hdr/param/fighter_param.xml
  romfs/source/fighter/link/motion/body/motion_patch.yaml
Labels: character change, semver:patch, balance approved, includes assets

#2586 Robot 3.0 - Robotic Uprising
  Cargo.toml
  fighters/robot/src/acmd/aerials.rs
  fighters/robot/src/acmd/ground.rs
  fighters/robot/src/acmd/other.rs
  fighters/robot/src/acmd/specials.rs
  fighters/robot/src/opff.rs
  fighters/robot/src/status/special_hi.rs
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/robot/motion/body/motion_patch.yaml
Labels: character change, semver:patch, balance approved

#2592 version bump
  README.md
Labels: semver:feature

#2594 v0.49.1-pre-release
  dynamic/src/consts.rs
  fighters/chrom/src/acmd/aerials.rs
  fighters/chrom/src/acmd/specials/special_hi.rs
  fighters/chrom/src/acmd/specials/special_n.rs
  fighters/chrom/src/acmd/specials/special_s/special_s2.rs
  fighters/chrom/src/acmd/specials/special_s/special_s3.rs
  fighters/chrom/src/acmd/specials/special_s/special_s4.rs
  fighters/chrom/src/acmd/tilts.rs
  fighters/chrom/src/status/mod.rs
  fighters/chrom/src/status/special_n.rs
  fighters/chrom/src/status/special_s.rs
  fighters/cloud/src/acmd/aerials.rs
  fighters/cloud/src/acmd/specials/speciallw.rs
  fighters/cloud/src/acmd/specials/specials.rs
  fighters/cloud/src/status/mod.rs
  fighters/common/src/function_hooks/controls.rs
  fighters/common/src/function_hooks/vtables/edge.rs
  fighters/common/src/general_statuses/itemthrow/itemthrow.rs
  fighters/common/src/general_statuses/itemthrow/itemthrowdash.rs
  fighters/common/src/misc.rs
  fighters/edge/src/fire/acmd.rs
  fighters/edge/src/fire/status.rs
  fighters/edge/src/flare1/status.rs
  fighters/edge/src/flash/acmd.rs
  fighters/edge/src/flash/mod.rs
  fighters/edge/src/flash/status.rs
  fighters/elight/src/acmd/specials.rs
  fighters/elight/src/exprosiveshot/acmd.rs
  fighters/elight/src/opff.rs
  fighters/elight/src/status/special_hi_finish2.rs
  fighters/elight/src/status/special_s_forward.rs
  fighters/gaogaen/src/status/attack_lw4.rs
  fighters/ike/src/acmd/specials.rs
  fighters/ike/src/opff.rs
  fighters/ike/src/status/special_s.rs
  fighters/krool/src/status/attack_lw4.rs
  fighters/pickel/src/acmd/specials/mod.rs
  fighters/wario/src/status/throw_kirby.rs
  romfs/source/fighter/cloud/param/vl.prcxml
  romfs/source/fighter/common/hdr/param/common.xml
  romfs/source/fighter/common/hdr/param/fighter_param.xml
  romfs/source/fighter/common/param/fighter_param.prcxml
  romfs/source/fighter/elight/param/vl.prcxml
  src/lua.rs
  utils/src/modules/param.rs
Labels: bug, aesthetics, character change, engine, crash, semver:patch, balance approved

#2595 Pre-Release Bugfixes
  fighters/edge/src/fire/acmd.rs
  fighters/edge/src/flare1/status.rs
Labels: bug, semver:patch
