Repository HDR-Development/HewDraw-Remix, pull requests merged in 2025-05, with the labels that each got.

#2566 v0.48.5-pre-release
  fighters/common/src/general_statuses/cliff.rs
  fighters/common/src/opff/other.rs
  fighters/master/src/acmd/specials.rs
  romfs/source/fighter/samus/param/vl.prcxml
  romfs/source/fighter/samusd/param/vl.prcxml
  romfs/source/ui/param/database/ui_bgm_db.prc
  romfs/source/ui/param/database/ui_gametitle_db.prc
Labels: bug, character change, semver:patch, stages, balance approved

#2568 v0.48.6-pre-release
  src/controls/submenu.rs
Labels: bug, semver:patch, stages

#2569 v0.48.8-pre-release (hotfix)
  src/controls/submenu.rs
Labels: bug, semver:patch

#2571 v0.48.10
  dynamic/src/consts.rs
  fighters/miifighter/src/acmd/specials/special_lw.rs
  fighters/miifighter/src/status/mod.rs
  fighters/miifighter/src/status/special_lw2.rs
Labels: bug, semver:patch
